import type { BlogPost } from './data';

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20', note: 'Use named ownership, protection, detection, response, and recovery outcomes when a routine touches business systems.' },
  { name: 'CISA More than a Password', url: 'https://www.cisa.gov/mfa', note: 'Protect work accounts with multi-factor authentication and an explicit recovery owner.' },
  { name: 'Google Search Central: Creating helpful, reliable, people-first content', url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', note: 'Make each operating record useful to the person who must review or act on it.' },
];

type Topic = {
  slug: string; title: string; lane: string; opening: string; finish: string;
  checks: string[]; boundary: string; failure: string; handoff: string;
};

const topics: Topic[] = [
  {slug:'virtual-assistant-founder-inbox-decision-digest',title:'A founder inbox decision digest that does not hide the difficult messages',lane:'founder inbox decision digest',opening:'A crowded inbox is rarely one problem. It contains routine replies, decisions only the founder can make, quiet risks, and messages that simply need filing.',finish:'a short digest that links each source message, states the requested decision, names the deadline, and separates drafts from owner-only calls',checks:['Group by decision owner, not by sender.','Quote the request briefly instead of rewriting its meaning.','Keep “no action” messages out of the decision list.'],boundary:'The assistant can classify, summarize, and draft. They should not accept terms, commit money, resolve a personnel matter, or speak for the founder without a written rule.',failure:'If the founder keeps reopening the inbox to understand the digest, sample five entries together. The likely repair is better context, not a longer report.',handoff:'End with decisions due today, replies ready for approval, waiting items, and the first item for tomorrow.'},
  {slug:'virtual-assistant-podcast-guest-booking-board',title:'Build a podcast guest booking board a producer can trust',lane:'podcast guest booking board',opening:'Guest booking goes sideways when pitches, availability, release forms, biographies, and recording links live in separate threads.',finish:'one board showing the guest, episode angle, approval state, time zone, recording status, required assets, and next owner',checks:['Preserve the guest’s preferred name and supplied biography.','Confirm time zones in the invitation and calendar record.','Treat a tentative date as tentative until both sides confirm.'],boundary:'The assistant may coordinate from approved templates. The host or producer chooses guests, approves editorial claims, and handles sensitive requests or contractual terms.',failure:'A full calendar with missing releases or unapproved angles is not a healthy pipeline. Review readiness by stage, not booking count alone.',handoff:'Send a weekly note covering confirmed recordings, decisions needed, missing assets, cancellations, and capacity for new outreach.'},
  {slug:'virtual-assistant-sales-proposal-follow-up-queue',title:'Run a sales proposal follow-up queue without inventing urgency',lane:'sales proposal follow-up queue',opening:'Proposal follow-up needs persistence, but it also needs restraint. A stale deal, an active legal review, and a prospect who declined are three different states.',finish:'a queue with the last customer signal, approved next message, due date, salesperson, consent or no-contact state, and unresolved question',checks:['Read the latest thread before drafting.','Stop sequences after an opt-out or clear decline.','Route pricing and scope changes to the salesperson.'],boundary:'The assistant keeps records current and prepares approved follow-ups. They do not negotiate, discount, manufacture scarcity, or claim a result the team cannot support.',failure:'If messages go out on time but prospects reply with confusion, inspect stage definitions and source notes before increasing cadence.',handoff:'The daily closeout lists replies needing judgment, messages sent, records corrected, no-contact updates, and tomorrow’s due items.'},
  {slug:'virtual-assistant-client-onboarding-dependency-map',title:'Map client onboarding dependencies before the kickoff call',lane:'client onboarding dependency map',opening:'Most onboarding delays are not caused by one large failure. They come from small prerequisites that nobody named: an owner, a login, a signed document, a data export, or a decision.',finish:'a dependency map that links each deliverable to its prerequisite, accountable owner, due date, status, and safe fallback',checks:['Distinguish “requested” from “received and checked.”','Put access requests beside the business purpose.','Show which missing item actually blocks the next step.'],boundary:'The assistant can collect, verify, and chase prerequisites. Contract changes, security exceptions, data-sharing approval, and launch acceptance remain with accountable owners.',failure:'When every item is marked urgent, the map has stopped helping. Reorder it around the critical path and document what can proceed safely.',handoff:'Before kickoff, circulate the confirmed inputs, open decisions, blocked activities, and named owners—without copying sensitive material into the summary.'},
  {slug:'virtual-assistant-customer-refund-evidence-packet',title:'Prepare a customer refund evidence packet without deciding the refund',lane:'customer refund evidence packet',opening:'A refund request often arrives as a frustrated message, while the decision depends on an order record, policy, delivery history, prior promises, and an authorized exception.',finish:'a compact packet with the customer request, order identifier, applicable approved policy, timeline, prior remedies, missing facts, and decision owner',checks:['Use the policy version that applied to the transaction.','Separate customer statements from system records.','Record previous credits or promises before routing.'],boundary:'The assistant gathers evidence and may send an approved holding reply. The authorized owner decides exceptions, financial remedies, and any legal or reputational response.',failure:'A fast packet is weak if the reviewer must rebuild the timeline. Sample returned packets and fix the field that repeatedly sends them back.',handoff:'Route the packet with a plain question, the response deadline, and any safe action already completed.'},
  {slug:'virtual-assistant-ecommerce-product-change-log',title:'Keep an ecommerce product change log that supports rollback',lane:'ecommerce product change log',opening:'A product page can change in seconds, yet a bad price, variant, claim, or image may take hours to trace if the old state was never recorded.',finish:'a change log with product identifier, requested edit, source approval, before state, after state, operator, check result, and rollback note',checks:['Preview mobile and desktop before publishing.','Verify price, currency, variants, and inventory behavior separately.','Link the approved copy or merchandising request.'],boundary:'The assistant implements approved changes and checks the result. Pricing strategy, regulated claims, promotions, and destructive catalog actions require the designated owner.',failure:'“Published” is not the finish line. If the live page differs from the request or breaks a variant, restore the approved state and escalate.',handoff:'At shift end, list completed changes, failed checks, rolled-back edits, and requests still waiting for approval.'},
  {slug:'virtual-assistant-recruiting-interview-day-brief',title:'Create an interview-day brief without scoring the candidate',lane:'recruiting interview-day brief',opening:'Interviewers need logistics and context, but an administrative brief can accidentally become an unsupported assessment of a candidate.',finish:'a factual brief with role, interview stage, schedule, approved interviewers, candidate-supplied materials, accommodations route, and open logistics',checks:['Use the candidate’s stated name and time zone.','Label missing information instead of guessing.','Keep interviewer notes in the authorized hiring system.'],boundary:'The assistant coordinates and verifies. They do not infer personality, rank candidates, ask unapproved screening questions, or make hiring decisions.',failure:'If interviewers ask the same logistics questions in chat, revise the brief. If they ask evaluative questions, route them to the hiring owner.',handoff:'Send only to approved participants and record schedule changes, acknowledgments, unresolved conflicts, and the recruiting owner.'},
  {slug:'virtual-assistant-bookkeeping-month-end-document-chase',title:'A month-end document chase that respects finance boundaries',lane:'month-end document chase',opening:'Month-end preparation slows when receipts, invoices, purchase references, and explanations arrive through several channels with no clear owner.',finish:'a document register showing what was requested, why it is needed, source period, responsible person, received state, discrepancy, and finance reviewer',checks:['Match documents to the correct entity and period.','Use a secure approved upload route.','Do not mark an unexplained difference as resolved.'],boundary:'The assistant requests, names, and organizes records. Coding choices, journal entries, tax treatment, payment approval, and financial sign-off belong to qualified finance owners.',failure:'More reminders will not repair an unclear request. When the same document is rejected, capture the reason and have finance clarify the requirement.',handoff:'The closeout separates complete packets, missing documents, discrepancies, and items awaiting finance judgment.'},
  {slug:'virtual-assistant-knowledge-base-broken-path-review',title:'Find broken knowledge-base paths, not just broken links',lane:'knowledge-base broken-path review',opening:'A help article can have perfect links and still fail because the reader cannot find it, lacks permission, sees an obsolete label, or reaches a dead end.',finish:'a test record for one real task, including the search phrase, path taken, page version, access context, result, blocker, and content owner',checks:['Test from the intended user’s starting point.','Check task completion as well as URL status.','Capture conflicting guidance instead of choosing one silently.'],boundary:'The assistant tests, inventories, and drafts corrections. Policy owners approve authoritative instructions, customer promises, and security-sensitive changes.',failure:'A rising page count is not success if common tasks still require private knowledge. Prioritize failed journeys and high-consequence contradictions.',handoff:'The weekly review lists repaired paths, owner decisions, unresolved conflicts, and searches that returned no approved answer.'},
  {slug:'virtual-assistant-crm-lost-lead-recovery-audit',title:'Audit lost CRM leads without rewriting sales history',lane:'CRM lost-lead recovery audit',opening:'A blank next step does not always mean a salesperson forgot the lead. The prospect may have declined, duplicated another record, changed ownership, or requested no contact.',finish:'a review queue with the original source, last verified interaction, current owner, consent status, proposed correction, and approval need',checks:['Read activity history before changing a stage.','Protect opt-outs and suppression records.','Propose duplicate merges with reversible evidence.'],boundary:'The assistant can identify gaps and prepare corrections. Sales owners decide qualification, territory, commercial terms, and whether an ambiguous relationship should be revived.',failure:'Do not reward the audit for creating tasks. Measure whether records become accurate and actionable without unwanted outreach.',handoff:'Report corrected records, owner decisions required, duplicates proposed, no-contact findings, and records that remain genuinely unresolved.'},
  {slug:'virtual-assistant-social-content-approval-calendar',title:'Use a social content approval calendar that preserves the final say',lane:'social content approval calendar',opening:'A publishing calendar is useful only when it distinguishes an idea, a working draft, approved copy, scheduled content, and a verified live post.',finish:'a calendar with channel, audience, draft owner, asset source, reviewer, approval timestamp, schedule, live URL, and correction status',checks:['Use only approved image inventory.','Check links and claims in the final rendered version.','Never treat an emoji reaction as approval unless policy says so.'],boundary:'The assistant prepares, schedules, and verifies approved content. Brand positions, sensitive replies, paid spend, legal claims, and crisis communication stay with their owners.',failure:'A green calendar can conceal deleted posts or outdated drafts. Sample live URLs and compare them with the approved version.',handoff:'The daily note covers items awaiting approval, scheduled posts, live checks, corrections, and decisions blocking the next slot.'},
  {slug:'virtual-assistant-vendor-renewal-fact-pack',title:'Prepare a vendor renewal fact pack before negotiation starts',lane:'vendor renewal fact pack',opening:'Renewals are easy to miss when dates sit in contracts, invoices, calendars, and individual memory. The administrative job is to assemble the facts early.',finish:'a fact pack with contract source, renewal and notice dates, current scope, authorized users, invoice history, service issues, owner, and open questions',checks:['Link the controlling document and note amendments.','Distinguish actual use from licensed quantity.','Flag conflicting dates for legal or procurement review.'],boundary:'The assistant compiles facts and coordinates review. They do not interpret legal obligations, accept terms, negotiate price, cancel service, or approve spend.',failure:'If the owner discovers a key term during negotiation, add that field to the next review rather than simply making the pack longer.',handoff:'Route the pack before the notice window with a decision date, identified reviewers, missing evidence, and no implied recommendation.'},
];

export const september4BlogPosts: BlogPost[] = topics.map((topic, index) => ({
  slug: topic.slug,
  featuredImage: '/featured/publishing-contingency-routine.png',
  title: topic.title,
  excerpt: `A practical ${topic.lane} routine for a Philippines-based virtual assistant, with evidence, checks, handoff rules, and a manager-owned decision boundary.`,
  minutes: 9,
  published: '2026-09-04', updated: '2026-09-04', displayDate: 'September 4, 2026',
  takeaways: [topic.finish, topic.checks[0], topic.boundary, topic.handoff],
  sections: [
    { heading: `Start with the real problem`, body: `${topic.opening} For Virtual Assistant Provider, the useful routine is the one that leaves the next person with a reliable record—not a vague “done” message.` },
    { heading: `Define a finish line`, body: `Treat the completed ${topic.lane} as ${topic.finish}. Write that definition beside the recurring task so the assistant and reviewer are checking the same outcome.` },
    { heading: `Run the work in a visible sequence`, body: `Begin from the approved source, record the current state, prepare the permitted action, run the checks, and preserve the result. When information conflicts or a required approval is absent, stop in a visible waiting state.`, bullets: topic.checks },
    { heading: `Keep judgment with its owner`, body: topic.boundary },
    { heading: `Review the first five examples`, body: `Demonstrate one example, then review the next four against the source. Record corrections by cause: missing input, unclear instruction, access gap, execution error, or late owner decision. ${topic.failure}` },
    { heading: `Protect accounts and source material`, body: `Use a named account, multi-factor authentication, and only the permissions the lane requires. Keep sensitive details in approved systems and link to them when possible. NIST’s framework is useful for assigning governance and response ownership; CISA’s guidance supports stronger sign-in controls.` },
    { heading: `Close the day with a usable handoff`, body: `${topic.handoff} The handoff should tell the next reader what changed, what remains safe to do, and which decision cannot be delegated.` },
  ],
  faq: [
    { question: `Who should own the ${topic.lane}?`, answer: `A virtual assistant can own repeatable preparation and checks. A named manager owns exceptions, approvals, and business judgment. ${topic.boundary}` },
    { question: 'What evidence should remain?', answer: 'Keep the source, action, check result, timestamp, exception, and reviewer decision. Store sensitive material only in its approved system.' },
    { question: 'When can review move from every item to a sample?', answer: 'Only after the lane is stable across normal and exception cases. Return to full review after a serious miss, instruction change, or permission change.' },
  ],
  sources,
  relatedServices: [],
  articleLinks: [
    { label: 'daily planning guide', href: '/blog/virtual-assistant-daily-planning-philippines' },
    { label: index % 2 === 0 ? 'handoff guide' : 'escalation rules guide', href: index % 2 === 0 ? '/blog/virtual-assistant-handoff-philippines' : '/blog/virtual-assistant-escalation-rules-philippines' },
    { label: 'NIST Cybersecurity Framework 2.0', href: sources[0].url, external: true },
  ],
}));
