import type { BlogPost } from './data';

const sourceSets = {
  access: [
    { name: 'NIST Access Control Project', url: 'https://csrc.nist.gov/projects/access-control', note: 'Limit actions to approved users and purposes.' },
    { name: 'CISA More than a Password', url: 'https://www.cisa.gov/more-password', note: 'Protect accounts that handle business and customer records.' },
  ],
  records: [
    { name: 'NIST Access Control Project', url: 'https://csrc.nist.gov/projects/access-control', note: 'Limit access to the records and actions required for the role.' },
    { name: 'Google Search Central: Creating helpful content', url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', note: 'Keep guidance useful, specific, and written for a real reader.' },
  ],
};

function makeArticle(input: {
  slug: string; published: string; title: string; topic: string; excerpt: string;
  detail: string; boundary: string; checklist: string[]; owner: string; sourceSet: keyof typeof sourceSets;
}): BlogPost {
  const { slug, published, title, topic, excerpt, detail, boundary, checklist, owner, sourceSet } = input;
  return {
    slug, published, updated: '2026-08-13', displayDate: 'August 13, 2026',
    featuredImage: '/featured/virtual-assistant-appointment-setting-philippines.png', title, excerpt, minutes: 10,
    takeaways: [detail, checklist[0], boundary],
    sections: [
      { heading: 'Start with the record, not a broad job title', body: `${detail} For a Philippines-based virtual assistant, define ${topic} as a small set of records with a clear source, expected output, and due point. The owner should provide one finished example and one example that must pause.`, bullets: checklist },
      { heading: 'Make the handoff readable', body: `A useful ${topic} handoff states what was checked, what remains uncertain, and the exact decision or action needed next. ${owner} should be able to review the record without recreating the assistant's research or searching across several tools.` },
      { heading: 'Protect the boundary', body: `${boundary} Give the role only the account and fields needed for its first lane. Keep a named reviewer, use a separate approval step, and record corrections where the next person will see them.` },
      { heading: 'Review before adding another lane', body: `Sample early ${topic} work for accuracy, completeness, source fidelity, and correct escalation. Expand only after the first set of records is dependable; when a source conflicts, preserve both values and ask ${owner} to decide.` },
    ],
    faq: [
      { question: `What should a VA do first with ${topic}?`, answer: `Begin with a small, repeatable record set, two examples, a reviewer, and a stop rule for incomplete or unusual cases.` },
      { question: 'Who decides an exception?', answer: `${owner} decides exceptions. The assistant should attach the record, explain what was checked, and identify the decision required.` },
    ],
    sources: sourceSets[sourceSet], relatedServices: [],
    articleLinks: [
      { label: 'onboarding checklist', href: '/blog/virtual-assistant-onboarding-checklist-philippines' },
      { label: 'access control guide', href: '/blog/virtual-assistant-access-control-philippines' },
      { label: 'NIST access control guidance', href: 'https://csrc.nist.gov/projects/access-control', external: true },
    ],
  };
}

export const august13BlogPosts: BlogPost[] = [
  makeArticle({ slug: 'virtual-assistant-client-portal-admin-philippines', published: '2026-08-13', title: 'Virtual assistant client portal administration Philippines: keep requests organized', topic: 'client portal administration', excerpt: 'A practical guide to organizing client requests, status notes, files, and owner approvals with a Philippines-based virtual assistant.', detail: 'Use one intake view, a status vocabulary, and a current-owner field so client requests do not disappear between messages.', boundary: 'Do not let support change commitments, remove records, or answer a disputed request without the responsible client owner.', checklist: ['Record the requester, received date, requested outcome, and next owner.', 'Separate new, waiting, approved, and closed states.', 'Attach the source file or message to each material change.'], owner: 'the client-service owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-contract-intake-philippines', published: '2026-08-13', title: 'Virtual assistant contract intake Philippines: prepare documents for review', topic: 'contract intake', excerpt: 'How to collect contract details and missing documents while leaving interpretation and acceptance with the responsible reviewer.', detail: 'A contract-intake lane can collect parties, dates, version labels, and open fields without pretending to give legal advice.', boundary: 'Do not interpret clauses, accept terms, or tell a customer that a document is binding.', checklist: ['Use a required-field list for parties, dates, and document version.', 'Flag missing signatures and conflicting names.', 'Keep the review request separate from the collected record.'], owner: 'the responsible legal or business owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-review-request-philippines', published: '2026-08-13', title: 'Virtual assistant review requests Philippines: send owners the right context', topic: 'review requests', excerpt: 'Build review requests that give a Philippines-based assistant a clear way to summarize evidence and give the owner a clear decision.', detail: 'A good review request is a compact packet: the question, the evidence, the attempted check, and the decision needed.', boundary: 'Do not hide uncertainty inside a polished summary or mark an item approved on the owner’s behalf.', checklist: ['Put one decision question in the subject or heading.', 'Link the exact record and identify its date.', 'State the consequence of waiting or choosing each option.'], owner: 'the person accountable for the decision', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-knowledge-transfer-philippines', published: '2026-08-13', title: 'Virtual assistant knowledge transfer Philippines: make role handoffs usable', topic: 'knowledge transfer', excerpt: 'A concrete way to move recurring role knowledge into examples, ownership notes, and searchable references for a Philippines-based assistant.', detail: 'Knowledge transfer works when it captures decisions, examples, exceptions, and where the source is maintained, not just a long narrative.', boundary: 'Do not treat an unverified note as policy or let the assistant rewrite a client’s rule without confirmation.', checklist: ['Capture one normal case and one exception case.', 'Name the source owner and last-confirmed date.', 'Mark questions that still need a subject-matter answer.'], owner: 'the role owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-renewal-tracking-philippines', published: '2026-08-13', title: 'Virtual assistant renewal tracking Philippines: surface dates before they matter', topic: 'renewal tracking', excerpt: 'Use a careful renewal register for supplier, software, and service dates without allowing a Philippines-based assistant to accept new terms.', detail: 'A renewal register should show the agreement, notice window, owner, next check, and evidence behind each date.', boundary: 'Do not renew, cancel, negotiate, or approve a commitment from a reminder list alone.', checklist: ['Record the source agreement and renewal or notice date.', 'Add a reminder before the decision window closes.', 'Route changed terms and missing documents to the owner.'], owner: 'the contract or budget owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-refund-request-routing-philippines', published: '2026-08-13', title: 'Virtual assistant refund request routing Philippines: preserve the customer record', topic: 'refund request routing', excerpt: 'Set up a fair record and escalation path for refund requests while a Philippines-based assistant prepares rather than decides.', detail: 'Refund support is clearer when the request, order facts, policy reference, and requested remedy remain together.', boundary: 'Do not promise a refund, invent an exception, or expose payment details outside approved systems.', checklist: ['Capture order identity, request date, reason, and policy link.', 'Separate preparation from approval and payment action.', 'Use a visible status for pending owner review.'], owner: 'the customer-service or finance owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-shipping-status-philippines', published: '2026-08-13', title: 'Virtual assistant shipping status Philippines: keep delivery questions current', topic: 'shipping status', excerpt: 'Organize delivery checks and customer updates with a Philippines-based virtual assistant while keeping carrier exceptions visible.', detail: 'A shipping-status lane needs a current tracking source, a checked-at time, and a response that does not promise what the carrier has not confirmed.', boundary: 'Do not change an address, promise a delivery date, or claim a parcel is lost without the owner’s rule.', checklist: ['Record tracking source, last scan, and check time.', 'Use approved language for delays and no-scan cases.', 'Escalate address changes and damaged-package reports.'], owner: 'the fulfillment or customer-service owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-returns-coordination-philippines', published: '2026-08-13', title: 'Virtual assistant returns coordination Philippines: make next steps clear', topic: 'returns coordination', excerpt: 'A bounded returns desk guide covering request details, labels, status updates, and owner decisions for a Philippines-based assistant.', detail: 'Returns coordination is mostly record discipline: match the order, approved window, item condition, carrier step, and next customer update.', boundary: 'Do not approve an exception, alter a product policy, or promise replacement stock without approval.', checklist: ['Match the return to the order and customer record.', 'Record the policy used and any exception requested.', 'Keep label, receipt, inspection, and decision statuses distinct.'], owner: 'the ecommerce owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-event-registration-philippines', published: '2026-08-13', title: 'Virtual assistant event registration Philippines: keep attendee records dependable', topic: 'event registration', excerpt: 'Plan attendee records, confirmation messages, and exception handling for a Philippines-based virtual assistant supporting an event team.', detail: 'Registration support should make it easy to answer who is registered, what they selected, and what still needs confirmation.', boundary: 'Do not disclose attendee lists, promise access, or change event terms without the event owner.', checklist: ['Use required fields and consent-aware notes.', 'Separate confirmed, waitlisted, cancelled, and duplicate records.', 'Route accessibility and special requests to a named owner.'], owner: 'the event owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-webinar-follow-up-philippines', published: '2026-08-13', title: 'Virtual assistant webinar follow-up Philippines: turn attendance into useful next steps', topic: 'webinar follow-up', excerpt: 'A practical handoff for attendance notes, approved follow-up, and unanswered questions handled by a Philippines-based assistant.', detail: 'Follow-up is more useful when each attendee has a source-backed status, a permitted next message, and a clear owner for questions.', boundary: 'Do not make claims about a participant’s interest, send unapproved offers, or treat attendance as permission for unrelated contact.', checklist: ['Reconcile the attendance record with the registration record.', 'Use separate paths for questions, resources, and owner follow-up.', 'Log the message and response status without unnecessary personal detail.'], owner: 'the marketing or event owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-membership-admin-philippines', published: '2026-08-13', title: 'Virtual assistant membership administration Philippines: keep access requests orderly', topic: 'membership administration', excerpt: 'Define a safe lane for membership records, access requests, and member questions handled by a Philippines-based assistant.', detail: 'Membership administration benefits from a current roster, a documented access rule, and a traceable response to every request.', boundary: 'Do not disclose private member information, change eligibility, or resolve disputes without the membership owner.', checklist: ['Match each request to a current member record.', 'Use approved answers for access and renewal questions.', 'Escalate identity conflicts, disputes, and unusual access requests.'], owner: 'the membership owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-customer-feedback-philippines', published: '2026-08-13', title: 'Virtual assistant customer feedback Philippines: sort signals without overclaiming', topic: 'customer feedback', excerpt: 'A grounded way to collect, tag, and route customer feedback with a Philippines-based virtual assistant.', detail: 'Feedback becomes useful when the original words, product context, date, and requested follow-up stay visible beside any tag.', boundary: 'Do not edit a complaint into a nicer story, promise a fix, or treat a small sample as a broad conclusion.', checklist: ['Preserve the original message and source channel.', 'Tag the topic only when the evidence supports it.', 'Route safety, privacy, and repeated-impact concerns promptly.'], owner: 'the product or customer owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-review-response-philippines', published: '2026-08-13', title: 'Virtual assistant review response Philippines: draft with a clear approval line', topic: 'review responses', excerpt: 'How to prepare thoughtful public-review drafts while keeping facts, tone, and approval with the business owner.', detail: 'A response lane should distinguish an observed order or service fact from a proposed apology, explanation, or next step.', boundary: 'Do not argue with a reviewer, reveal private details, or publish a response without the brand owner’s approval.', checklist: ['Link the internal record behind any factual statement.', 'Mark claims that need owner confirmation.', 'Keep private resolution details out of the public draft.'], owner: 'the brand or customer-service owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-order-reconciliation-philippines', published: '2026-08-13', title: 'Virtual assistant order reconciliation Philippines: compare records before escalating', topic: 'order reconciliation', excerpt: 'A practical record-comparison guide for matching orders, payments, shipments, and exceptions with a Philippines-based assistant.', detail: 'Reconciliation support is strongest when it compares named records and preserves the exact mismatch instead of silently correcting one side.', boundary: 'Do not alter financial records, issue credits, or decide which system is authoritative without the accountable owner.', checklist: ['Name the two records and the comparison date.', 'Classify missing, duplicate, timing, and value mismatches.', 'Attach evidence before asking for a correction decision.'], owner: 'the operations or finance owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-inventory-notes-philippines', published: '2026-08-13', title: 'Virtual assistant inventory notes Philippines: keep product records honest', topic: 'inventory notes', excerpt: 'Keep stock observations, supplier notes, and unresolved discrepancies useful without letting a Philippines-based assistant guess.', detail: 'Inventory notes should distinguish a counted quantity, a system quantity, a date, and the person who must resolve the difference.', boundary: 'Do not promise availability, change stock counts, or substitute a guess for a physical or system check.', checklist: ['Record source, location, quantity, and observation time.', 'Mark unverified values as unverified.', 'Escalate shortages, damaged items, and count conflicts.'], owner: 'the inventory or fulfillment owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-event-logistics-philippines', published: '2026-08-13', title: 'Virtual assistant event logistics Philippines: coordinate details without owning risk', topic: 'event logistics', excerpt: 'A role guide for venue notes, vendor confirmations, attendee details, and open decisions handled by a Philippines-based assistant.', detail: 'Logistics coordination works when every detail has an owner, deadline, confirmation source, and fallback question.', boundary: 'Do not sign agreements, commit funds, or make safety decisions from an incomplete vendor message.', checklist: ['Track vendor, contact, deliverable, due date, and confirmation source.', 'Separate confirmed details from proposed options.', 'Flag accessibility, safety, and cancellation questions to the event owner.'], owner: 'the event or operations owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-translation-coordination-philippines', published: '2026-08-13', title: 'Virtual assistant translation coordination Philippines: preserve meaning across handoffs', topic: 'translation coordination', excerpt: 'Set up translation requests, source versions, reviewer notes, and ambiguity flags for a Philippines-based assistant.', detail: 'Translation coordination should preserve the source text, target audience, language variant, and reviewer comments so meaning is not lost in a quick handoff.', boundary: 'Do not certify a translation, resolve an ambiguous legal or clinical phrase, or remove a caveat to make text shorter.', checklist: ['Keep source and translated versions paired.', 'Label terminology choices and unresolved ambiguity.', 'Route high-impact language to a qualified reviewer.'], owner: 'the subject-matter or language owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-recruiter-calendar-philippines', published: '2026-08-13', title: 'Virtual assistant recruiter calendar Philippines: protect candidate scheduling', topic: 'recruiter calendar support', excerpt: 'Coordinate interview times and candidate updates with a Philippines-based assistant while leaving selection decisions with the employer.', detail: 'Candidate scheduling needs accurate time zones, interview type, interviewer, accessibility notes, and a clear status after every change.', boundary: 'Do not rank candidates, infer suitability, or disclose one candidate’s information to another.', checklist: ['Confirm time zone and meeting owner before sending an invite.', 'Use neutral, approved status language.', 'Route accommodation requests and interview changes to the recruiter.'], owner: 'the recruiter or hiring manager', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-service-issue-log-philippines', published: '2026-08-13', title: 'Virtual assistant service issue logs Philippines: make recurring problems actionable', topic: 'service issue logs', excerpt: 'Create an issue record that preserves customer impact, evidence, owner, and next check for a Philippines-based assistant.', detail: 'An issue log should help a manager see pattern, impact, and the next decision without turning guesses into root-cause claims.', boundary: 'Do not assign blame, promise a resolution date, or close an issue because the conversation went quiet.', checklist: ['Record the symptom, affected record, and first observed time.', 'Separate confirmed fact from working hypothesis.', 'Add owner, next check, and customer-update status.'], owner: 'the service or operations owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-document-version-control-philippines', published: '2026-08-13', title: 'Virtual assistant document version control Philippines: stop teams using the wrong file', topic: 'document version control', excerpt: 'A practical file-control guide for a Philippines-based assistant who keeps shared documents labeled, current, and easy to review.', detail: 'Version control is more than naming: it pairs the file with an owner, effective date, approval state, and location of the current source.', boundary: 'Do not delete a superseded file, overwrite an owner’s document, or call a draft current without confirmation.', checklist: ['Use a consistent version and status label.', 'Keep an index that points to the approved source.', 'Record who confirmed the current version and when.'], owner: 'the document owner', sourceSet: 'access' }),
  makeArticle({ slug: 'virtual-assistant-client-feedback-summary-philippines', published: '2026-08-13', title: 'Virtual assistant client feedback summaries Philippines: make conversations useful', topic: 'client feedback summaries', excerpt: 'Turn client conversations into concise, checkable summaries without losing the customer’s request or the owner’s decision.', detail: 'A feedback summary should separate what the client said, what was checked, what was agreed, and what remains open.', boundary: 'Do not attribute a motive, soften a complaint until it changes meaning, or promise a change that was not approved.', checklist: ['Quote or link the source message when wording matters.', 'List agreed actions with an owner and date.', 'Mark unresolved questions instead of implying closure.'], owner: 'the account or service owner', sourceSet: 'records' }),
  makeArticle({ slug: 'virtual-assistant-supplier-onboarding-philippines', published: '2026-08-13', title: 'Virtual assistant supplier onboarding Philippines: collect setup details safely', topic: 'supplier onboarding', excerpt: 'Organize supplier contact, document, and setup information while keeping approval and commercial decisions with the owner.', detail: 'Supplier onboarding is clearer when required documents, bank or tax fields, system access, and approval status are kept separate.', boundary: 'Do not approve a supplier, change payment instructions, or verify identity from an untrusted message alone.', checklist: ['Use a required-document checklist and source link.', 'Confirm sensitive changes through the approved channel.', 'Keep submitted, verified, approved, and rejected states distinct.'], owner: 'the procurement or finance owner', sourceSet: 'access' }),
];
