import type { ResearchPost, ResearchSource } from './fleet-content';

type Topic = { slug: string; published: '2026-08-13'; keyword: string; title: string; excerpt: string; service: string; audience: string; question: string; finding: string; image: string; sources: ResearchSource[]; signals: string[] };
const S = {
  privacy: { id: 1, name: 'NIST Privacy Framework', organization: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', accessed: '2026-08-13' },
  access: { id: 2, name: 'Cybersecurity Performance Goals', organization: 'Cybersecurity and Infrastructure Security Agency', url: 'https://www.cisa.gov/cybersecurity-performance-goals', accessed: '2026-08-13' },
  wcag: { id: 3, name: 'Web Content Accessibility Guidelines', organization: 'W3C Web Accessibility Initiative', url: 'https://www.w3.org/TR/WCAG22/', accessed: '2026-08-13' },
  market: { id: 4, name: 'Market research and competitive analysis', organization: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis', accessed: '2026-08-13' },
  risk: { id: 5, name: 'Risk Management Framework', organization: 'National Institute of Standards and Technology', url: 'https://csrc.nist.gov/projects/risk-management', accessed: '2026-08-13' },
};
const topics: readonly Topic[] = [
  { slug: 'vendor-onboarding-virtual-assistant-philippines', published: '2026-08-13', keyword: 'vendor onboarding virtual assistant Philippines', title: 'Vendor onboarding with a Philippines-based virtual assistant: evidence for a controlled record', excerpt: 'How privacy, security, and risk principles shape bounded vendor intake without handing over approval or payment decisions.', service: 'vendor onboarding record preparation', audience: 'an operations owner', question: 'Which parts of vendor intake can be prepared remotely while approval and payment authority stay with the accountable owner?', finding: 'Vendor intake is safer when source documents, required fields, approval status, and exceptions are visible in one controlled record.', image: '/featured/virtual-assistant-reporting-template-philippines.png', sources: [S.privacy, S.wcag, S.access], signals: ['A complete intake packet is not an approved vendor.', 'A response window is not a promise of instant availability.', 'An escalation rule gives ambiguity a safe destination.'] },
  { slug: 'travel-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'travel research virtual assistant Philippines', title: 'Travel research in a Philippines-based support role: evidence and limits', excerpt: 'How to separate itinerary research and source checking from booking authority, personal data handling, and final travel decisions.', service: 'travel research and itinerary preparation', audience: 'an executive support buyer', question: 'What evidence supports delegating travel research while the traveler keeps control of commitments and purchases?', finding: 'Travel research is safest when sources, time zones, cancellation terms, traveler preferences, and owner-only decisions are explicit.', image: '/featured/virtual-assistant-appointment-setting-philippines.png', sources: [S.privacy, S.access, S.wcag], signals: ['A travel record contains personal and business context.', 'Time-zone labels prevent avoidable scheduling errors.', 'The owner remains accountable for sensitive commitments.'] },
  { slug: 'customer-feedback-analysis-virtual-assistant-philippines', published: '2026-08-13', keyword: 'customer feedback analysis virtual assistant Philippines', title: 'Customer-feedback analysis: evidence for a bounded Philippines-based support role', excerpt: 'How a support role can organize feedback without turning a coded theme into a causal claim or an automatic customer promise.', service: 'customer-feedback coding and analysis', audience: 'a customer-support owner', question: 'How can feedback be organized for a decision owner without overstating what a small set of comments proves?', finding: 'Feedback analysis is more useful when the sample, coding rule, missing responses, and distinction between observation and interpretation are visible.', image: '/featured/customer-support-qa-workflow.png', sources: [S.privacy, S.wcag, S.access], signals: ['A theme needs a coding rule and review owner.', 'Customer data should not be copied into general notes.', 'Unusual requests need a human decision path.'] },
  { slug: 'sales-operations-reporting-virtual-assistant-philippines', published: '2026-08-13', keyword: 'sales operations reporting virtual assistant Philippines', title: 'Sales-operations reporting in a Philippines-based support role: what the evidence permits', excerpt: 'How to prepare a reliable sales report while separating field definitions and source records from forecasting judgment and customer claims.', service: 'sales-operations reporting', audience: 'a sales-operations owner', question: 'Which reporting tasks can be delegated while pipeline meaning and customer commitments remain accountable?', finding: 'Sales reporting is defensible when metric definitions, source records, missing fields, and exception paths are visible to the reviewer.', image: '/featured/sales-support-crm-hygiene.png', sources: [S.privacy, S.market, S.access], signals: ['A clean field is not proof of a qualified lead.', 'Duplicate rules need an accountable owner.', 'Customer-facing claims require source records and approval.'] },
  { slug: 'product-data-enrichment-virtual-assistant-philippines', published: '2026-08-13', keyword: 'product data enrichment virtual assistant Philippines', title: 'Product-data enrichment: evidence for a Philippines-based catalog role', excerpt: 'A research-backed boundary between adding sourced product attributes and making claims about safety, performance, availability, or commercial terms.', service: 'product-data enrichment', audience: 'an ecommerce operator', question: 'What evidence supports delegating product-attribute research without delegating product claims or commercial decisions?', finding: 'Product-data support is strongest when every added attribute has a source, a reviewer, and a visible distinction between product fact and marketing claim.', image: '/featured/ecommerce-virtual-assistant-philippines.png', sources: [S.privacy, S.wcag, S.access], signals: ['Attribute fields need a source of truth.', 'Accessibility descriptions should describe the product rather than invent benefits.', 'Commercial changes need owner-approved rules.'] },
  { slug: 'accounts-payable-document-preparation-virtual-assistant-philippines', published: '2026-08-13', keyword: 'accounts payable document preparation virtual assistant Philippines', title: 'Accounts-payable document preparation: evidence for a bounded Philippines-based role', excerpt: 'How to organize invoice records while keeping accounting judgment, approvals, tax decisions, and money movement with qualified owners.', service: 'accounts-payable document preparation', audience: 'a small-business owner', question: 'Which accounts-payable preparation tasks can be supported without confusing organized records with accounting judgment?', finding: 'Preparation is safer when invoice sources, coding questions, approval status, and unresolved exceptions remain separate.', image: '/featured/bookkeeping-virtual-assistant-philippines.png', sources: [S.risk, S.privacy, S.access], signals: ['A complete packet is not a reconciled account.', 'Uncertain coding belongs in an exception queue.', 'Bank and payment permissions should be narrowly assigned.'] },
  { slug: 'real-estate-listing-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'real estate listing research virtual assistant Philippines', title: 'Real-estate listing research: evidence for a careful Philippines-based support role', excerpt: 'A bounded research view of listing-source checks, record accuracy, privacy, and decisions that should stay with a licensed or accountable professional.', service: 'real-estate listing research', audience: 'a real-estate team owner', question: 'How can support organize listing research while leaving property, legal, and client commitments with the responsible professional?', finding: 'Listing research should preserve each source, distinguish observed property details from interpretation, and route legal or property questions instead of guessing.', image: '/featured/real-estate-assistant-lead-follow-up.png', sources: [S.privacy, S.access, S.market], signals: ['A source log preserves the property question.', 'Approved language is narrower than professional judgment.', 'Privacy and fair-treatment duties need local review.'] },
  { slug: 'healthcare-referral-coordination-virtual-assistant-philippines', published: '2026-08-13', keyword: 'healthcare referral coordination virtual assistant Philippines', title: 'Healthcare referral coordination: evidence for a bounded Philippines-based role', excerpt: 'What privacy and risk principles imply for administrative referral support, minimum necessary access, patient communication, and escalation of clinical questions.', service: 'healthcare referral coordination', audience: 'a healthcare practice owner', question: 'Which referral tasks can be delegated without allowing administrative support to become clinical advice?', finding: 'Referral support should handle approved logistics with minimum necessary access and route symptoms, treatment, and urgent concerns to qualified staff.', image: '/featured/virtual-assistant-patient-scheduling-philippines.png', sources: [S.privacy, S.access, S.risk], signals: ['Referral data still deserves privacy controls.', 'An administrative script cannot answer a clinical question.', 'Urgent language needs a named escalation path.'] },
  { slug: 'executive-document-review-virtual-assistant-philippines', published: '2026-08-13', keyword: 'executive document review virtual assistant Philippines', title: 'Executive document review: evidence for a safer Philippines-based support role', excerpt: 'A practical evidence boundary for document triage, version tracking, access, and escalation when an assistant supports a busy executive.', service: 'executive document review', audience: 'an executive or founder', question: 'How can document support reduce administrative load while preserving confidentiality and decision ownership?', finding: 'Document review is safer when categories, delegated access, version labels, confidential handling, and owner-only decisions are defined before launch.', image: '/featured/executive-assistant-calendar-delegation.png', sources: [S.privacy, S.access, S.wcag], signals: ['Triage is different from making a commitment.', 'Delegated access is safer than a shared password.', 'Confidential documents need an explicit route.'] },
  { slug: 'competitor-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'competitor research virtual assistant Philippines', title: 'Competitor research: evidence for a decision-ready Philippines-based support role', excerpt: 'How a research-support role can make public competitor findings easier to check while leaving interpretation, strategy, and business decisions with the client.', service: 'competitor research and comparison', audience: 'a founder or strategy owner', question: 'What separates useful competitor research from a collection of untested links?', finding: 'A decision-ready competitor record states the question, comparison set, observation date, source limits, and exact inference the evidence permits.', image: '/featured/virtual-assistant-market-research-brief-philippines.png', sources: [S.market, S.privacy, S.wcag], signals: ['A source must match the claim and comparison set.', 'A finding needs a date and definition.', 'Recommendation is distinct from observed evidence.'] },
];

const makePost = (t: Topic): ResearchPost => {
  const ids = t.sources.map((s) => s.id);
  const paragraphs = [
    `This report examines ${t.service} for ${t.audience}. The question is narrow: ${t.question} The answer cannot come from a national statistic or a provider description. It requires a defined task, a safe sample, a named owner, and a record of what happened when the task became ambiguous.`,
    `${t.finding} That conclusion is a boundary, not a promise. The cited authorities describe privacy, security, accessibility, risk, or research principles; they do not measure a particular Philippines-based assistant, customer, practice, property, inbox, catalog, or account.`,
    'The useful unit of review is one work item. Identify its input, expected output, source of truth, permitted action, stop condition, and reviewer. Then ask whether another person could inspect the record later and understand what changed, why it changed, and what remained unresolved.',
    `${t.signals[0]} Put that requirement in the task brief and test it in a small sample using invented or redacted information. A fluent answer is not enough if the work cannot be traced back to its source.`,
    `${t.signals[1]} Separate a response target from an outcome guarantee. A calendar response can be timely without creating a good meeting; a CRM update can be complete without proving sales fit; a prepared document can be orderly without being an approved record.`,
    `${t.signals[2]} Escalation is not failure when the rule does not cover the case. It keeps a support role from silently making a legal, clinical, financial, commercial, or confidential decision.`,
    'A practical role brief lists recurring work, permitted fields or messages, systems, exception owner, review frequency, and offboarding action. Write an acceptable output and a stop-worthy output. This reduces disagreement during the first week because quality is described before it is scored.',
    'Access should follow the task rather than the title. Use named accounts, multi-factor authentication, minimum necessary permissions, and a documented recovery owner. Do not provide a shared administrator login for convenience. Remove unused access when the work changes, and confirm that exported files and notes have an owner when the assignment ends.',
    'The first test should resemble the real work but contain no live customer secrets, payment credentials, medical details, confidential negotiations, or irreversible actions. Score completeness, accuracy, source traceability, tone, question quality, and escalation. One exercise cannot prove long-term performance; use it to decide what to supervise next.',
    'For a Philippines-based arrangement, clarify hours, overlap, outage communication, equipment, holidays, data handling, and the person responsible for review. Country context can help plan the conversation, but it cannot establish an individual’s connection quality, schedule, education, language judgment, or fit. Ask for evidence at the role level.',
    'Review the first live set at a cadence matching the risk. A formatting queue may need sampling; a customer, healthcare, finance, or executive workflow may require approval before release. Ask: was the source right, was the field complete, was the boundary respected, and did the record make the next decision easier?',
    'The main limitation is transfer. Guidance about privacy or risk does not predict worker accuracy, and a clean sample does not establish future reliability. Results depend on source data, software, instructions, workload, and review capacity. Treat this as role-design guidance that must be tested in the actual setting.',
  ];
  return {
    slug: t.slug, featuredImage: t.image, primaryKeyword: t.keyword, title: t.title, metaTitle: t.title, excerpt: t.excerpt,
    published: t.published, updated: t.published, readingMinutes: 10, revision: `${t.published}-${t.slug}-v1`,
    takeaways: [t.finding, ...t.signals, 'Use role-level evidence and bounded access; do not turn general guidance into a guarantee.'],
    headlineStats: [
      { value: '1', label: 'Decision question', context: t.question, sourceIds: ids },
      { value: '3', label: 'Evidence boundaries', context: 'Source scope, task proof, and owner accountability must stay distinct.', sourceIds: ids },
      { value: '1', label: 'Named owner', context: 'Every exception needs an accountable person who can resolve it.', sourceIds: ids },
      { value: '0', label: 'Unsupported promises', context: 'The sources support boundaries and questions, not guaranteed results.', sourceIds: ids },
      { value: '1', label: 'Safe first lane', context: `Begin with a bounded ${t.service} assignment and review the evidence before widening scope.`, sourceIds: ids },
      { value: '6', label: 'Review dimensions', context: 'Score accuracy, completeness, traceability, tone, questions, and escalation.', sourceIds: ids },
    ],
    sections: [
      { heading: 'What the evidence can answer', paragraphs: paragraphs.slice(0, 3) },
      { heading: 'Define the work at record level', paragraphs: paragraphs.slice(3, 6) },
      { heading: 'Design a safe first test', paragraphs: paragraphs.slice(6, 9) },
      { heading: 'Set access and communication boundaries', paragraphs: paragraphs.slice(9, 11) },
      { heading: 'Interpret results without overclaiming', paragraphs: paragraphs.slice(11) },
    ],
    evidenceTable: t.signals.map((finding, i) => ({ signal: ['Scope', 'Observable record', 'Escalation'][i], finding, buyerUse: 'Put this requirement in the role brief and sample scorecard.', limit: 'It does not prove a candidate, provider, or future outcome.', sourceIds: ids })),
    implications: [
      { title: 'Define the lane', body: `List the recurring ${t.service} tasks, inputs, outputs, tools, reviewer, and stop conditions.` },
      { title: 'Protect the record', body: 'Use named accounts, minimum access, source links, and an exception note for every material uncertainty.' },
      { title: 'Test with safe data', body: 'Use invented or redacted records before opening live credentials or allowing an irreversible action.' },
      { title: 'Review the first work', body: 'Inspect a small first set for accuracy, completeness, traceability, communication, and escalation judgment.' },
    ],
    methodology: [`This report uses the authoritative sources listed below, accessed on August 13, 2026. Sources were selected for direct relevance to ${t.service}, privacy, security, accessibility, risk, or research method.`, 'The recommendations are practical guidance from Virtual Assistant Provider. The cited authorities support principles and boundaries, not a measured performance result or guarantee about any person, provider, customer, or business.', 'The article excludes individual hiring claims and does not substitute for qualified legal, clinical, accounting, privacy, employment, or property advice where those duties apply.'],
    faq: [
      { question: `Can support own the final ${t.service} decision?`, answer: 'Only when the responsible owner has explicitly assigned it and the role is qualified. Otherwise, support prepares the record and escalates.' },
      { question: 'What should a buyer test first?', answer: 'Use a short sample with safe data and score accuracy, completeness, traceability, communication, and escalation judgment.' },
      { question: 'Does a source prove a provider is suitable?', answer: 'No. It supplies relevant evidence and boundaries; suitability requires role-specific proof and review.' },
      { question: 'What belongs in the role brief?', answer: 'Tasks, inputs, outputs, access, owner-only decisions, exception paths, review timing, and offboarding.' },
    ],
    sources: t.sources,
    related: [
      { title: 'Research library', href: '/research', description: 'Read the other source-led reports for Philippines-based support decisions.' },
      { title: 'Services', href: '/services', description: 'Review the support areas covered by Virtual Assistant Provider.' },
      { title: 'Plan a Philippines-based role', href: '/contact', description: 'Bring the recurring work, tools, review rules, and owner decisions for a role plan.' },
    ],
  };
};
export const august13ResearchPosts: readonly ResearchPost[] = topics.map(makePost);
