import type { ResearchPost, ResearchSource } from './fleet-content';

type August14Topic = {
  slug: string;
  published: '2026-08-17';
  primaryKeyword: string;
  title: string;
  metaTitle: string;
  excerpt: string;
  image: string;
  question: string;
  finding: string;
  audience: string;
  sources: ResearchSource[];
  sections: { heading: string; paragraphs: string[] }[];
};

const nist: ResearchSource = { id: 1, name: 'NIST Privacy Framework', organization: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', accessed: '2026-08-14' };
const cisa: ResearchSource = { id: 2, name: 'Cybersecurity Performance Goals', organization: 'Cybersecurity and Infrastructure Security Agency', url: 'https://www.cisa.gov/cybersecurity-performance-goals', accessed: '2026-08-14' };
const wcag: ResearchSource = { id: 3, name: 'Web Content Accessibility Guidelines 2.2', organization: 'W3C Web Accessibility Initiative', url: 'https://www.w3.org/TR/WCAG22/', accessed: '2026-08-14' };
const sba: ResearchSource = { id: 4, name: 'Market research and competitive analysis', organization: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis', accessed: '2026-08-14' };
const bls: ResearchSource = { id: 5, name: 'Occupational Outlook Handbook: Office and Administrative Support', organization: 'U.S. Bureau of Labor Statistics', url: 'https://www.bls.gov/ooh/office-and-administrative-support/home.htm', accessed: '2026-08-14' };
const access: ResearchSource = { id: 6, name: 'Access Control', organization: 'National Institute of Standards and Technology', url: 'https://csrc.nist.gov/projects/access-control', accessed: '2026-08-14' };

const topics: August14Topic[] = [
  {
    slug: 'subscription-cancellation-research-philippines', published: '2026-08-17', primaryKeyword: 'subscription cancellation research virtual assistant Philippines',
    title: 'Subscription-cancellation research: separate customer signals from retention decisions', metaTitle: 'Subscription-cancellation research: evidence guide', image: '/featured/research-evidence-table-guide.png',
    excerpt: 'A bounded study of cancellation reasons, missing context, and handoff evidence for a Philippines-based support research role.', question: 'What can a cancellation sample reveal about friction, and what must remain a product or account-owner decision?', finding: 'Cancellation research is useful when the event, stated reason, cohort, and missing evidence remain separate from a claim about why customers leave.', audience: 'a customer-success or product owner', sources: [sba, nist],
    sections: [
      { heading: 'Define the event before counting it', paragraphs: ['A cancellation record can mean a customer clicked a button, allowed a renewal to lapse, asked support to stop billing, or left after a failed payment. Those events are operationally different. Before a Philippines-based researcher counts anything, write the event definition, observation window, channels included, and the system of record. If the study combines voluntary cancellations with involuntary payment failures, the result will describe a mixed queue rather than a single customer decision.', 'The useful unit is usually a subscription event linked to a cohort and date, not a dramatic message. Preserve the customer’s selected reason and a short redacted excerpt, but do not infer motive from tone. A request for a lower bill may indicate price sensitivity, a missing feature, a temporary cash constraint, or a policy misunderstanding. The record can show what was said and when; it cannot prove which explanation is true.'] },
      { heading: 'Build a defensible sample', paragraphs: ['Set a period such as four complete weeks and state whether the sample includes monthly, annual, trial, or reactivated accounts. Report the denominator: cancellations per eligible renewal or counts by plan cohort, rather than presenting a raw total as a rate. Keep a separate field for missing reason, multiple reasons, and reason selected from a menu. Missingness is a finding about the record, not permission to fill the gap with the most common category.', 'A second reviewer should code a small redacted sample using the written categories. Disagreements reveal where “billing,” “value,” “technical,” and “service” overlap. Record the rule that resolved each disagreement, then rerun the count. A small audit cannot establish perfect reliability, but it makes the interpretation reproducible and shows the owner where the categories are unstable.'] },
      { heading: 'Protect personal and billing context', paragraphs: ['Cancellation records may include names, account identifiers, payment references, health information, or messages written in distress. Use the minimum fields needed for the question and keep raw messages in the approved system. NIST’s Privacy Framework is a useful boundary: identify the data needed for the purpose, govern its handling, and communicate how privacy risk is managed.[1] A research extract should use a study ID instead of copying a full account history.', 'The researcher may note that a customer asked about a charge or could not find a setting, but should not decide whether a refund, exception, or retention offer is owed. CISA’s performance goals also support protecting accounts and data through appropriate access and authentication.[2] The owner retains authority over billing corrections, legal language, policy changes, and contact with a vulnerable customer.'] },
      { heading: 'Interpret patterns without overstating them', paragraphs: ['Compare reasons by defined cohort, tenure band, product area, and channel only when those fields are complete enough to support the comparison. A difference between new and long-standing accounts may reflect the mix of products, onboarding quality, or which customers answer the survey. It is not automatically evidence that tenure causes cancellation. Show counts alongside percentages and state the denominator for every comparison.', 'Look for negative evidence as well. If a large share has no selected reason, the next intervention may be better reason capture rather than a product change. If support transcripts mention a feature but the cancellation form does not, the two instruments are measuring different things. The conclusion should identify the strongest observable signal, the plausible alternatives, and the next question that would distinguish them.'] },
      { heading: 'Turn findings into an owner-ready brief', paragraphs: ['A useful brief starts with the question, population, field period, data exclusions, coding guide, and table of results. For each notable pattern, include an example record with identifying details removed, the source field, and the limit. This lets the customer-success owner inspect the reasoning without asking the researcher to reproduce the entire account history.', 'Recommendations should be staged. First repair a missing field or unclear cancellation reason. Then test a small change, such as clearer renewal language, and define the outcome and comparison period before acting. Keep offers, product commitments, and policy decisions with the named owner. A support research role supplies evidence; it does not turn a frequency table into an approved retention strategy.'] },
      { heading: 'Limitations and conclusion', paragraphs: ['This study cannot establish lifetime value, customer intent, causation, or the financial effect of a retention action unless those outcomes and methods are separately defined. Survey responders may differ from silent customers, selected reasons may be constrained by the form, and records may be duplicated across systems. Changes in billing policy or product packaging can also break comparisons across periods.', 'The defensible conclusion is narrow: a cancellation sample can locate observable friction and record gaps when its event definition, cohort, and coding rules are visible. A Philippines-based assistant can prepare the sample, redact it, document the counts, and route anomalies. The accountable owner must decide what to change, which customers to contact, and how the next measurement will test that decision.'] },
    ]
  },
  {
    slug: 'event-venue-accessibility-research-philippines', published: '2026-08-17', primaryKeyword: 'event venue accessibility research virtual assistant Philippines',
    title: 'Event-venue accessibility research: compare published information without certifying access', metaTitle: 'Event-venue accessibility research: evidence guide', image: '/featured/research-source-authority-check.png',
    excerpt: 'How to prepare a venue comparison from published evidence while leaving current confirmation and accessibility judgment with the organizer.', question: 'Which venue details can be compared remotely, and where does a desk review stop?', finding: 'A venue brief is credible when each observation names the route, date, source, and unanswered access question instead of implying a complete accessibility audit.', audience: 'an event organizer', sources: [wcag, sba],
    sections: [
      { heading: 'Define access needs as questions', paragraphs: ['“Accessible venue” is too broad to be a useful research field. Break it into the attendee journey: arrival, parking or drop-off, entrance, registration, seating, toilets, stage visibility, acoustics, captioning, emergency information, and departure. The organizer should identify which needs matter for the event and which details require confirmation from the venue. A researcher can then collect comparable observations without pretending that one label covers every person or route.', 'For each venue, record the exact page or contact response, observation date, jurisdiction, and whether the information describes the public building or one event room. A photo of a ramp does not establish its gradient, condition, or unobstructed route. A statement that a venue is accessible does not answer whether captioning, quiet space, service-animal policy, or accessible transport is available on the selected date.'] },
      { heading: 'Use a repeatable comparison method', paragraphs: ['Create a table with one row per venue and columns for the attendee need, published evidence, source date, confidence, question for confirmation, and owner. Do not collapse a missing detail into “no.” Use “not stated,” “requires confirmation,” or “observed on the public page” so absence of evidence is not confused with evidence of absence. The table should also show whether the source is official, a map listing, a review, or an attendee report.', 'A small second-reviewer exercise can test whether the fields are understandable. Give two reviewers the same three venue pages and ask them to record arrival, interior route, and communication details. Discuss disagreements rather than forcing a single score. The purpose is a clear handoff, not a universal ranking. If information changes quickly, repeat the check close to the event and preserve both observation dates.'] },
      { heading: 'Apply accessibility guidance carefully', paragraphs: ['WCAG 2.2 concerns web content and does not certify a physical building.[3] It can still help a researcher assess whether a venue page exposes useful information in a perceivable, operable, understandable way. That is a separate finding from whether an attendee can enter the building. Name the tested page and task, such as locating the accessible entrance or reading the contact method, and report the observed barrier without diagnosing its technical cause.', 'Do not ask a researcher to promise that a venue meets a legal standard or to interpret a person’s medical need. Route questions about building codes, reasonable accommodation, evacuation, service animals, and safety to the organizer and appropriate qualified advisers. A respectful brief asks the venue for current, specific confirmation and gives the attendee a way to state what they need without unnecessary health details.'] },
      { heading: 'Separate public evidence from confirmation', paragraphs: ['Public research is valuable for narrowing a long list, but a venue’s current capacity, room setup, lift status, and event staffing still require confirmation. The brief should distinguish “published,” “confirmed by venue,” and “pending.” Include the name or role of the confirming contact, the date, and the exact question answered. If an email is ambiguous, preserve the ambiguity and ask a focused follow-up rather than upgrading it to a yes.', 'The organizer can use the comparison to choose which venues deserve a site visit or call. Do not rank a location by a single accessibility score when the attendee journey contains multiple independent conditions. A venue with good web information may still need a physical check; a venue with sparse web information may be able to answer well by phone. The evidence informs the next step, not the final promise.'] },
      { heading: 'Write the brief for action', paragraphs: ['Begin with the event date, audience, required routes, and decision deadline. Then show the evidence table, open questions, contact trail, and a short “do not assume” note. Include source links beside the fields they support, not in a detached list that makes reconstruction difficult. Remove attendee names and unnecessary personal details from the working copy.', 'A Philippines-based support researcher can collect pages across time zones, normalize terminology, and flag missing information. The event owner must choose the venue, authorize contact, approve the attendee-facing wording, and decide whether an on-site or specialist review is needed. The handoff is complete when each important unknown has an owner and a next check date.'] },
      { heading: 'Limitations and conclusion', paragraphs: ['A desk comparison cannot test every route, observe a live event, verify a temporary obstruction, or understand an individual’s access experience. Venue pages may be stale, maps may simplify building layouts, and self-reported descriptions may omit detail. The study also cannot certify legal compliance or guarantee that a particular attendee will find the event usable.', 'The defensible conclusion is that structured public evidence can reduce avoidable questions and expose missing venue information. It becomes responsible research only when the source date, route, uncertainty, and confirmation owner remain visible. Use the brief to plan the next verification step, and keep safety, accommodation, and attendee commitments with the organizer.'] },
    ]
  },
];

const extraTopics: Array<Pick<August14Topic, 'slug'|'primaryKeyword'|'title'|'metaTitle'|'image'|'excerpt'|'question'|'finding'|'audience'|'sources'>> = [
  { slug: 'supplier-shipment-status-research-philippines', primaryKeyword: 'supplier shipment status research virtual assistant Philippines', title: 'Supplier-shipment status research: reconcile dates before an owner makes a promise', metaTitle: 'Supplier-shipment status research: evidence guide', image: '/featured/research-data-lineage.png', excerpt: 'A source-led method for comparing shipment updates, exceptions, and dates without turning an administrative note into a delivery guarantee.', question: 'What can a shipment-status sample establish about the record, and what remains a supplier or customer decision?', finding: 'Shipment research is strongest when event time, source time, carrier status, and promised date are recorded as separate fields.', audience: 'an operations or procurement owner', sources: [sba, nist] },
  { slug: 'grant-eligibility-research-philippines', primaryKeyword: 'grant eligibility research virtual assistant Philippines', title: 'Grant-eligibility research: map published requirements without promising an award', metaTitle: 'Grant-eligibility research: evidence guide', image: '/featured/research-claim-evidence-map.png', excerpt: 'How administrative research can organize grant requirements, deadlines, and open questions while leaving eligibility interpretation with the applicant.', question: 'How can a support researcher compare published grant requirements without offering legal or funding advice?', finding: 'A grant brief should link every requirement to the issuing authority, version date, applicant fact, and unresolved interpretation.', audience: 'a nonprofit or business owner', sources: [sba, nist] },
  { slug: 'local-regulation-change-research-philippines', primaryKeyword: 'local regulation change research virtual assistant Philippines', title: 'Local regulation-change research: build an alert brief with bounded claims', metaTitle: 'Local regulation-change research: evidence guide', image: '/featured/research-source-version-check.png', excerpt: 'A careful way to track public rule changes, effective dates, and questions for qualified review.', question: 'What does a public regulation update show, and where must a researcher stop before giving advice?', finding: 'Change monitoring is reliable when the issuing body, publication date, effective date, affected scope, and review question are all explicit.', audience: 'a business owner or compliance lead', sources: [nist, sba] },
  { slug: 'customer-knowledge-search-research-philippines', primaryKeyword: 'customer knowledge search research virtual assistant Philippines', title: 'Customer knowledge-search research: find documentation gaps without blaming the reader', metaTitle: 'Customer knowledge-search research: evidence guide', image: '/featured/research-evidence-gap-log.png', excerpt: 'Use search terms, failed results, and support questions to study findability while preserving sample limits and privacy.', question: 'What can search behavior reveal about documentation, and what can it not prove about customer understanding?', finding: 'Search-gap research should keep the original query, result state, channel, period, and coding rule before proposing a content change.', audience: 'a support or documentation owner', sources: [sba, wcag] },
  { slug: 'professional-event-speaker-research-philippines', primaryKeyword: 'professional event speaker research virtual assistant Philippines', title: 'Professional event-speaker research: verify public credentials without writing a biography as proof', metaTitle: 'Professional event-speaker research: evidence guide', image: '/featured/research-reviewer-independence.png', excerpt: 'A source-bound method for checking speaker identity, published work, and topic fit without inventing authority or private facts.', question: 'Which public facts belong in a speaker brief, and how should uncertainty be handled?', finding: 'A speaker brief is defensible when identity match, source authority, publication date, relevance, and confirmation needs are explicit.', audience: 'an event or marketing owner', sources: [sba, nist] },
  { slug: 'remote-workspace-connectivity-research-philippines', primaryKeyword: 'remote workspace connectivity research virtual assistant Philippines', title: 'Remote-workspace connectivity research: plan questions without ranking a worker by geography', metaTitle: 'Remote-workspace connectivity research: evidence guide', image: '/featured/research-source-reliability-review.png', excerpt: 'How to organize connectivity evidence for a remote support role while avoiding unsupported assumptions about a person or location.', question: 'What can a connectivity questionnaire establish about a work setup, and what remains an individual test?', finding: 'Connectivity planning is useful when the actual work window, primary path, backup path, recovery steps, and test date are recorded.', audience: 'an operations or staffing owner', sources: [bls, cisa] },
  { slug: 'customer-survey-question-research-philippines', primaryKeyword: 'customer survey question research virtual assistant Philippines', title: 'Customer-survey question research: test whether an answer can support a decision', metaTitle: 'Customer-survey question research: evidence guide', image: '/featured/research-question-design.png', excerpt: 'A research method for reviewing survey wording, response options, and missing context before a team interprets the results.', question: 'How can a support researcher identify ambiguity in survey questions without claiming that a small test validates the whole instrument?', finding: 'Question research should tie each item to a decision, define its response unit, and record where wording leaves multiple interpretations.', audience: 'a customer-insights owner', sources: [sba, wcag] },
  { slug: 'document-retention-research-philippines', primaryKeyword: 'document retention research virtual assistant Philippines', title: 'Document-retention research: map published rules before changing a file practice', metaTitle: 'Document-retention research: evidence guide', image: '/featured/research-data-definition-audit.png', excerpt: 'A bounded comparison of document categories, source authority, and review questions for administrative records.', question: 'What can a retention research brief organize, and why must legal or regulatory interpretation stay with a qualified owner?', finding: 'Retention mapping needs document category, business purpose, source authority, jurisdiction, date, and an explicit “needs review” state.', audience: 'an operations or records owner', sources: [nist, sba] },
];

function makePost(topic: August14Topic): ResearchPost {
  const sourceIds = topic.sources.map((source) => source.id);
  return {
    slug: topic.slug, featuredImage: topic.image, primaryKeyword: topic.primaryKeyword, title: topic.title, metaTitle: topic.metaTitle,
    excerpt: topic.excerpt, published: topic.published, updated: topic.published, readingMinutes: 12, revision: '2026-08-14-research-v1',
    takeaways: [topic.finding, `The question is bounded for ${topic.audience}; it is not a guarantee of an outcome.`, 'Use a named source, observation date, denominator, and owner for every material finding.', 'Protect personal information and stop when the record does not support the next claim.'],
    headlineStats: [
      { value: '1', label: 'Decision question', context: topic.question, sourceIds },
      { value: '2+', label: 'Authority checks', context: 'Use multiple claim-relevant sources and keep each source’s scope visible.', sourceIds },
      { value: '100%', label: 'Records dated', context: 'Each observation should carry its own period or access date.', sourceIds },
      { value: '0', label: 'Unsupported promises', context: 'A research brief does not certify a person, supplier, venue, or result.', sourceIds },
    ],
    sections: topic.sections,
    evidenceTable: [
      { signal: 'Research question', finding: topic.finding, buyerUse: 'Use it to define the fields and sample before collecting records.', limit: 'It does not answer an owner-only decision.', sourceIds },
      { signal: 'Source authority', finding: `${topic.sources[0].organization} is the named authority for part of this question.`, buyerUse: 'Read the linked definition and retain its date and scope.', limit: 'Authority for a rule is not proof about a specific case.', sourceIds: [topic.sources[0].id] },
      { signal: 'Observed record', finding: 'A dated, source-linked record gives the next reviewer something to reproduce.', buyerUse: 'Keep the original field, coding rule, and unresolved question.', limit: 'A record cannot prove an unobserved motive or outcome.', sourceIds },
      { signal: 'Owner handoff', finding: `The next decision belongs to ${topic.audience}.`, buyerUse: 'Route exceptions with the evidence and the exact question.', limit: 'The correct decision maker depends on the engagement and context.', sourceIds: [topic.sources[0].id] },
    ],
    implications: [
      { title: 'Set the scope', body: `Define ${topic.question.toLowerCase()} with a period, population, source list, and stop rule.` },
      { title: 'Keep the record safe', body: 'Use minimum necessary fields, approved storage, named access, and redaction before sharing a sample.' },
      { title: 'Separate finding from interpretation', body: 'State what was observed, what it may suggest, and what additional check would distinguish alternatives.' },
      { title: 'Escalate the decision', body: `Return policy, legal, financial, safety, and commercial decisions to ${topic.audience}.` },
    ],
    methodology: [
      `This report was prepared for the ${topic.audience} question and uses the linked authorities accessed on August 14, 2026.`,
      'The sources provide definitions, public evidence, or methodological boundaries. They do not evaluate a specific person, provider, customer, venue, supplier, or business outcome.',
      'Interpretations are bounded by the stated sample, source dates, and missing fields. A current owner should recheck volatile facts before acting.',
    ],
    faq: [
      { question: `Can a support researcher decide the ${topic.primaryKeyword.split(' research')[0]} outcome?`, answer: 'No. The researcher prepares a source-linked brief and routes exceptions; the named owner or qualified specialist decides.' },
      { question: 'What should each record contain?', answer: 'Keep the original observation, source, access or event date, scope, coding rule, uncertainty, and next owner.' },
      { question: 'Does a public source prove a specific case?', answer: 'No. It supplies context or a rule boundary; case-level facts still require direct confirmation.' },
    ],
    sources: topic.sources,
    related: [
      { title: 'Research library', href: '/research', description: 'Read other source-led reports for planning support roles.' },
      { title: 'Services', href: '/services', description: 'Review the support areas covered by Virtual Assistant Provider.' },
      { title: 'Role planning', href: '/contact', description: 'Bring the recurring work, tools, and review rules for a role plan.' },
    ],
  };
}

function expandTopic(base: August14Topic, extra: August14Topic['sections']): August14Topic {
  return { ...base, sections: extra };
}

const reusableSections = (topic: string, owner: string, evidence: string): August14Topic['sections'] => [
  { heading: 'Name the unit and the time window', paragraphs: [`For ${topic}, the first research choice is the unit being counted or compared. It might be one request, one document, one public page, one event, or one account event. Write that unit before opening records, then name the field period and the population included. Without those choices, a neat total can combine unlike cases and make a narrow queue look like a general market fact. The research owner should be able to explain what is included, excluded, and missing.`, `Record the source timestamp separately from the event date. A page accessed today may describe a policy for a future period; a message received yesterday may refer to an older decision. Preserve local dates and time zones where they affect meaning. When a date is unavailable, use an explicit unknown state rather than borrowing a neighboring record’s date. This is especially important for a Philippines-based support role working with owners or sources in several jurisdictions.`] },
  { heading: 'Collect evidence that another person can check', paragraphs: [`A useful ${topic} brief keeps the original observation beside the normalized field. ${evidence} Do not replace the source wording with a stronger summary unless the source supports that exact strength. Link the authority, quote only what is necessary, and add a short note explaining why the source is relevant to the question.`, `Test the extraction rule on ordinary, incomplete, and conflicting examples. A missing value, a contradiction, and a negative result should have different labels. Ask a second reviewer to reproduce a small sample and record disagreements. Agreement does not prove the conclusion, but it shows where the method needs clearer definitions before a larger set is interpreted.`] },
  { heading: 'Protect people and limit access', paragraphs: [`Research records often contain more personal detail than the decision requires. Start with the minimum fields, use a study identifier, redact names and account numbers from working copies, and store raw material only in the approved system. NIST privacy guidance supports identifying and managing privacy risk in relation to the purpose of processing.[1] A support researcher should not move sensitive material into an unapproved note merely because it is easier to compare there.`, `Use named accounts and least privilege for the source systems. CISA’s performance goals emphasize practical protection for accounts and data.[2] If access reveals health, financial, identity, employment, or confidential commercial information, stop and ask the owner to confirm the purpose and reviewer. The role can organize evidence without expanding its own authority to approve, disclose, diagnose, or promise.`] },
  { heading: 'Interpret the pattern with its denominator', paragraphs: [`A finding should state the numerator, denominator, period, and selection rule when those quantities apply. Counts help show volume; percentages help compare groups only when the groups are defined and large enough for the question. A difference may reflect channel mix, missing data, seasonality, or who chose to respond. Treat those as alternative explanations to examine, not nuisances to hide.`, `Keep observation, interpretation, and recommendation in separate sentences. “Nine records mentioned a delay” is an observation. “The sample may indicate a handoff gap” is an interpretation. “The owner should test a status field next month” is a recommendation. This separation lets ${owner} disagree with the interpretation while still using the underlying evidence.`] },
  { heading: 'Design the owner handoff', paragraphs: [`The final brief should open with the decision question and close with the next check. In between, show scope, sources, method, results, exceptions, and limitations in that order. Give each material finding a record link or identifier, a source date, and an owner. A reader should not have to reconstruct the sample from a long message thread or infer which table cells are assumptions.`, `A Philippines-based assistant can make the handoff concise by separating “checked,” “not stated,” “conflicting,” and “needs owner decision.” The owner receives a useful queue rather than a false sense of certainty. Route legal interpretation, financial authorization, medical or safety judgment, customer remedy, and commercial commitments to the appropriate qualified person.`] },
  { heading: 'Limitations and conclusion', paragraphs: [`This method cannot turn a small sample into a population estimate, a public page into a current guarantee, or an administrative observation into professional advice. Sources can change, records can be incomplete, and the people who appear in a dataset may not represent the people who do not respond. If the decision is material, repeat the check close to action and document what changed since the earlier observation.`, `The defensible conclusion for ${topic} is bounded: organize the evidence, expose the unknowns, and give ${owner} a clear next question. A careful research role improves the quality of a decision without claiming ownership of the decision itself. That boundary is part of the finding, not a disclaimer added after the work is done.`] },
];

const august14DateBindings = [
  { slug: 'supplier-shipment-status-research-philippines', published: '2026-08-17' },
  { slug: 'grant-eligibility-research-philippines', published: '2026-08-17' },
  { slug: 'local-regulation-change-research-philippines', published: '2026-08-17' },
  { slug: 'customer-knowledge-search-research-philippines', published: '2026-08-17' },
  { slug: 'professional-event-speaker-research-philippines', published: '2026-08-17' },
  { slug: 'remote-workspace-connectivity-research-philippines', published: '2026-08-17' },
  { slug: 'customer-survey-question-research-philippines', published: '2026-08-17' },
  { slug: 'document-retention-research-philippines', published: '2026-08-17' },
] as const;

const generatedTopics: August14Topic[] = extraTopics.map((extra, index) => expandTopic({ ...extra, published: august14DateBindings[index].published, sections: [] }, reusableSections(extra.title.toLowerCase(), extra.audience, extra.finding)));

export const august14ResearchPosts: readonly ResearchPost[] = [
  ...topics.map(makePost),
  ...generatedTopics.map(makePost),
];
