import type { ResearchPost, ResearchSource } from './fleet-content';

const source = (id: number, name: string, organization: string, url: string): ResearchSource => ({ id, name, organization, url, accessed: '2026-09-04' });
const sources = [
  source(1, 'The NIST Cybersecurity Framework (CSF) 2.0', 'National Institute of Standards and Technology', 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'),
  source(2, 'Security and Privacy Controls for Information Systems and Organizations', 'National Institute of Standards and Technology', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'),
  source(3, 'More than a Password', 'Cybersecurity and Infrastructure Security Agency', 'https://www.cisa.gov/mfa'),
  source(4, 'Web Content Accessibility Guidelines (WCAG) 2.2', 'World Wide Web Consortium', 'https://www.w3.org/TR/WCAG22/'),
  source(5, 'Federal Plain Language Guidelines', 'PlainLanguage.gov', 'https://www.plainlanguage.gov/guidelines/'),
  source(6, 'Monitoring Distributed Systems', 'Google Site Reliability Engineering', 'https://sre.google/sre-book/monitoring-distributed-systems/'),
  source(7, 'NIST Privacy Framework', 'National Institute of Standards and Technology', 'https://www.nist.gov/privacy-framework'),
  source(8, 'Creating helpful, reliable, people-first content', 'Google Search Central', 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'),
];

type Study = {slug:string;title:string;keyword:string;question:string;context:string;unit:string;method:string;caseStudy:string;interpretation:string;boundary:string;limitations:string;conclusion:string;sourceIds:number[]};
const studies: Study[] = [
  {slug:'virtual-assistant-approval-wait-time-study',title:'Approval wait time in virtual assistant workflows: what should teams measure?',keyword:'virtual assistant approval wait time research',question:'How can a distributed support team measure approval delay without blaming an assistant for time controlled by someone else?',context:'Inbox, finance preparation, ecommerce, and customer-support tasks often pause at a real decision boundary. A single cycle-time number combines active preparation, queue time, owner review, rework, and system delay, making the result hard to interpret.',unit:'one approval event linked to its task, evidence packet, submitted time, decision owner, acknowledgment, decision, returned questions, and permitted next action',method:'Define timestamps before collection. Separate preparation time, unacknowledged wait, acknowledged review, assistant rework, and post-decision execution. Stratify by decision type and risk. Review fast and slow cases, plus missing records, over a stated four-week window.',caseStudy:'A refund packet is ready at 10:05, acknowledged at 13:20, returned for a missing delivery scan at 13:42, resubmitted at 14:10, and approved at 14:35. Calling this 4.5 hours of assistant handling hides the owner queue and a correctable evidence gap.',interpretation:'The useful finding is not simply that waiting is high. Repeated unacknowledged waits may indicate backup-owner design; repeated returns may indicate a weak packet definition; long high-risk reviews may be justified. The data should lead to a narrower process question.',boundary:'The assistant timestamps the handoff, keeps the case visible, and supplies approved evidence. They do not approve their own exception, fabricate urgency, or treat silence as consent.',limitations:'No client workflow or provider dataset was reviewed. Task mix, time zones, owner availability, risk, tooling, and local policy can change each interval. A four-week sample cannot establish a universal benchmark or causation.',conclusion:'Measure approval as distinct accountable intervals, then inspect the cases behind the distribution. Pair time with completeness, decision type, and outcome rather than turning one elapsed figure into a performance score.',sourceIds:[1,2,6]},
  {slug:'virtual-assistant-handoff-completeness-observation-study',title:'Handoff completeness: can a checklist predict successful continuation?',keyword:'virtual assistant handoff completeness research',question:'Does a complete handoff record help the next virtual assistant continue work correctly, and how could a manager test that claim?',context:'Shift changes and backup coverage create a practical test of documentation. A record can contain every required field yet still be hard to use, while a shorter record may preserve the exact state and safe next action.',unit:'one paused task and its handoff, including source, last verified state, action already taken, next permitted action, exception, decision owner, and access context',method:'Select representative low-risk tasks and genuine exceptions. Have a second authorized worker continue from the record without private chat, then compare the resulting action with the source and approved rule. Record clarification, duplicate work, unsafe action avoided, correction, and completion—not merely restart time.',caseStudy:'A calendar request pauses because two executives have conflicting priorities. The handoff lists calendars checked, options offered, messages already sent, the unresolved choice, and the executive who decides. The next shift can follow up without sending a duplicate invitation.',interpretation:'If complete records still trigger questions, fields may be technically filled but vague. If sparse records succeed only because colleagues share unwritten context, the workflow is fragile. Near-boundary cases matter more than rehearsed examples.',boundary:'Assistants may preserve state and take the next action allowed by written rules. Schedule tradeoffs, customer commitments, financial choices, access expansion, and other exceptions remain with the named owner.',limitations:'Observation changes behavior, and repeated test cases teach the expected answer. Complexity and tool familiarity affect continuation. The design does not prove that a checklist causes better performance or that one checklist fits every work lane.',conclusion:'Test handoffs through correct continuation, not field completion alone. Include exceptions, measure clarification and duplicate action, and keep owner-only decisions visible.',sourceIds:[1,5,6]},
  {slug:'virtual-assistant-least-privilege-task-fit-study',title:'Least-privilege task fit: testing whether access matches a virtual assistant role',keyword:'virtual assistant least privilege access research',question:'How can a manager check whether a virtual assistant has enough access for assigned work without quietly accumulating unnecessary permissions?',context:'Permissions are often added one blocker at a time. Over months, the account can retain tools, folders, exports, and administrator functions that no longer match the role. A login that works is not evidence that its scope is appropriate.',unit:'one recurring task mapped to its business purpose, required system action, approved role, actual permission, prohibited action, access owner, last use, and review decision',method:'Start from current tasks rather than the account list. Independently map the smallest expected permissions, compare them with actual grants, safely test required actions, and record excess, missing, inherited, shared, or unverifiable access. Review temporary permissions and removal evidence separately.',caseStudy:'An ecommerce assistant needs to update approved descriptions but not change payouts, issue unrestricted refunds, or export customer data. A role test checks the editing path and confirms excluded functions without attempting a live financial or destructive action.',interpretation:'Missing access can create unsafe workarounds; excess access increases exposure. A role may be too broad because the platform lacks granular controls, not because a manager acted carelessly. That constraint should be recorded with a compensating review or different workflow.',boundary:'The assistant explains the task and tests only approved safe actions. The system owner authorizes and revokes access. Nobody should borrow credentials, approve their own entitlement, or probe sensitive data to prove a control.',limitations:'This is a role-design review, not a penetration test, legal opinion, or certification. Platform capabilities, contracts, regulation, threat models, and business impact differ. Documentary evidence may not match effective technical permissions.',conclusion:'Begin access review with the task and business purpose, then compare the expected role with the actual grant. Record platform constraints and verify both needed and excluded actions safely.',sourceIds:[1,2,3,7]},
  {slug:'virtual-assistant-knowledge-article-task-success-study',title:'Knowledge article task success: a usability test for operational guidance',keyword:'virtual assistant knowledge article usability research',question:'Can an assistant complete a recurring task from the approved knowledge article, and what does a failed attempt actually show?',context:'A policy page can be accurate yet unusable because readers cannot find it, terms are undefined, steps assume hidden access, or the finish line is missing. Conversely, a successful task may depend on prior knowledge rather than the article.',unit:'one defined user task paired with the search path, article version, user role, required inputs, observed completion, clarification, error, and reviewer result',method:'Choose common tasks and high-consequence exceptions. Ask representative authorized users to locate current guidance and think aloud while using non-sensitive examples. Score findability, comprehension, task completion, and safe stopping separately. Compare article claims with the authoritative owner-approved source.',caseStudy:'“Update the customer record” is tested with an example containing a conflicting address and an opt-out. A useful article tells the assistant which field is authoritative, what may be changed, how consent is protected, and when to stop for the data owner.',interpretation:'Failure to find the page points to navigation or search; misunderstanding a term points to language; completing the wrong action points to scope or source authority. These are different repairs. One successful user does not establish broad usability.',boundary:'Assistants can test paths, identify ambiguity, and draft revisions. Policy, legal, privacy, finance, or security owners approve authoritative rules and any consequential change.',limitations:'Small usability sessions are diagnostic, not representative performance studies. Prior experience, language, permissions, device, search personalization, and facilitator behavior affect results. WCAG and plain-language guidance inform design but do not guarantee task success.',conclusion:'Test operational guidance as a real task journey. Separate finding, understanding, acting, and stopping so each failure leads to the right repair.',sourceIds:[4,5,7,8]},
  {slug:'virtual-assistant-exception-queue-denominator-study',title:'Exception queues need denominators: reading escalation patterns responsibly',keyword:'virtual assistant exception queue research',question:'What denominator and case context are needed before managers interpret a virtual assistant team’s escalation count?',context:'A raw escalation count can rise because volume grew, policy changed, assistants became more careful, or inputs worsened. It can fall because the process improved—or because exceptions disappeared into chat and were never logged.',unit:'one eligible task with lane, period, risk class, written trigger, escalation state, reason, destination, acknowledgment, decision, outcome, and missing-data flag',method:'Define the eligible task population first. Report exception counts beside total eligible tasks and stratify by task and risk. Audit a sample of non-escalated cases for missed triggers, inspect unresolved cases, and compare periods only when definitions and coverage remain stable.',caseStudy:'A support lane records 24 escalations from 1,200 eligible requests this month versus 12 from 400 last month. Counts doubled, but the share fell. A new refund policy and improved logging still make a simple month-to-month verdict unsafe.',interpretation:'High rates may reflect complex case mix or a safe stop culture. Low rates may reflect clear rules or under-reporting. Pair the rate with missed-escalation review, reason codes, consequence, owner response, and the share of records whose status is unknown.',boundary:'The assistant applies written triggers and routes evidence. Managers own thresholds, exceptions, customer remedies, financial decisions, and changes to authority. Metrics should improve the system, not pressure workers to suppress necessary escalations.',limitations:'Rare severe cases create unstable rates, and audits cannot find events never recorded. Definitions, volumes, staffing, seasonality, policy changes, and owner availability limit comparisons. Observational patterns do not establish individual capability or causation.',conclusion:'Publish the eligible denominator, definitions, case mix, missing data, and owner response beside every escalation rate. Inspect contradictory cases before changing thresholds or judging people.',sourceIds:[1,5,6,7]},
];

const selected = (ids:number[]) => ids.map(id => sources.find(item => item.id === id)!);

function makeStudy(study: Study, index: number): ResearchPost {
  const refs = selected(study.sourceIds);
  const citations = study.sourceIds.map(id => `[${id}]`).join('');
  return {
    slug: study.slug,
    featuredImage: '/featured/publishing-contingency-routine.png',
    primaryKeyword: study.keyword,
    title: study.title,
    metaTitle: study.title,
    excerpt: `A source-led research brief asking: ${study.question}`,
    published: '2026-09-04', updated: '2026-09-04', readingMinutes: 12,
    revision: `2026-09-04-${index + 1}-${study.slug}-v1`,
    takeaways: [study.conclusion, study.limitations, 'Keep missing and contradictory cases visible.', 'Use the result to improve the workflow, not to make unsupported claims about a worker or provider.'],
    headlineStats: [
      {value:'1',label:'Defined unit',context:`The observation is ${study.unit}.`,sourceIds:[study.sourceIds[0]]},
      {value:String(refs.length),label:'Public sources',context:'Named sources frame the controls and evidence limits.',sourceIds:study.sourceIds},
      {value:'2+',label:'Views of the case',context:'Independent review helps expose unstable definitions.',sourceIds:[study.sourceIds[1]]},
      {value:'0',label:'Guaranteed outcomes',context:'The cited guidance does not guarantee a staffing result.',sourceIds:[study.sourceIds[0]]},
      {value:'Named',label:'Decision owner',context:'Consequential exceptions stay with an authorized owner.',sourceIds:[study.sourceIds[0]]},
      {value:'2026-09-04',label:'Evidence review',context:'The linked public guidance was reviewed September 4, 2026.',sourceIds:study.sourceIds},
    ],
    sections: [
      {heading:`Research question: ${study.question}`,paragraphs:[study.context,`This report examines ${study.keyword} for buyers and managers of Philippines-based virtual assistant services. It uses public guidance to frame a practical observation design. It does not assess a provider, worker, client, or country. No private records, credentials, live forms, or experimental interruptions were used.`, `The unit is ${study.unit}. Fixing the unit before collection keeps observations attached to work rather than personality.`]},
      {heading:'Method and evidence scope',paragraphs:[study.method,`Publish field definitions, the observation window, exclusions, and review rule before reading results. Retain missing records as missing. A second reviewer should classify a redacted subset independently, then resolve disagreement against the written rule rather than seniority.`,`The cited sources offer governance, security, usability, privacy, or monitoring principles; they do not provide a universal virtual-assistant benchmark.${citations} The proposed method is our analysis of how those principles could become reviewable operating evidence.`]},
      {heading:'Representative case',paragraphs:[study.caseStudy,`The case is deliberately bounded. It tests the record and decision path with approved or invented information; it does not authorize live financial, legal, hiring, security, privacy, or customer decisions.`]},
      {heading:'Interpretation and competing explanations',paragraphs:[study.interpretation,`Preserve other plausible explanations such as tool design, incomplete inputs, novelty, workload, time-zone overlap, owner availability, and changing instructions. A metric becomes useful when it directs attention to cases worth reviewing, not when it supplies a convenient verdict.`,`Compare normal work, exceptions, apparent successes, and failures. Review what happened after the observation, because speed and completion labels can conceal correction, duplicate action, or a decision made outside the record.`]},
      {heading:'Role and privacy boundary',paragraphs:[study.boundary,`Collect the minimum evidence needed and keep sensitive details in approved systems. Named accounts, bounded permissions, and traceable owner decisions support accountability without turning ordinary coordination into continuous surveillance.[${study.sourceIds[0]}]`]},
      {heading:'Limitations',paragraphs:[study.limitations,`This qualitative research brief applies adjacent public guidance to an operations question. It is not a controlled study, market survey, legal opinion, privacy assessment, security audit, or provider evaluation. Managers should validate the design with qualified owners and local requirements before using it.`]},
      {heading:'Evidence-led conclusion',paragraphs:[study.conclusion,`The conclusion is narrower than a claim of productivity or service quality. Buyers should ask for a redacted work sample, the written definition, a reviewer decision, and a correction trail. Managers should keep counterexamples and revise the process before drawing conclusions about people.`]},
    ],
    evidenceTable: [
      {signal:'Defined observation',finding:study.unit,buyerUse:'Ask for a redacted example and decision trail.',limit:study.limitations,sourceIds:[study.sourceIds[0]]},
      {signal:'Independent interpretation',finding:'A second review can reveal ambiguous definitions.',buyerUse:'Calibrate the rule before expanding authority.',limit:'Agreement does not prove that the underlying policy is correct.',sourceIds:[study.sourceIds[1]]},
      {signal:'Case context',finding:'Task type, risk, inputs, tools, and owner availability affect results.',buyerUse:'Publish strata and exclusions.',limit:'A selected sample does not represent every future case.',sourceIds:study.sourceIds},
      {signal:'Owner boundary',finding:'The record supports a decision without transferring authority.',buyerUse:'Name the exception owner in advance.',limit:'Documentation does not replace qualified advice.',sourceIds:[study.sourceIds[0]]},
    ],
    implications: [
      {title:'For buyers',body:'Ask how evidence is defined, reviewed, corrected, and connected to a business outcome.'},
      {title:'For managers',body:'Inspect cases that contradict the preferred explanation and keep missing data visible.'},
      {title:'For assistants',body:'Preserve source facts and uncertainty, then stop outside written authority.'},
      {title:'For providers',body:'Explain review, coaching, access, backup ownership, and exception handling.'},
    ],
    methodology: [`Research question: ${study.question}`,`Evidence scope: ${refs.length} named public sources reviewed September 4, 2026.`,`Method: ${study.method}`,`Limitations: ${study.limitations}`],
    faq: [
      {question:'Does this prove virtual assistant or provider quality?',answer:'No. Buyers still need direct work samples, references, and reviewed production evidence.'},
      {question:'Can one rate compare teams?',answer:'No. Definitions, task mix, risk, authority, volume, and missing data must accompany it.'},
      {question:'Who can change the operating rule?',answer:'An assistant may identify ambiguity and propose wording. The authorized owner approves the change.'},
      {question:'What evidence should remain?',answer:'Keep the minimum source, observation, decision, outcome, period, and correction needed for review.'},
      {question:'When should the study repeat?',answer:'Repeat after material changes and at a cadence based on risk, volume, and observed defects.'},
    ],
    sources: refs,
    related: [
      {title:'Research library',href:'/research',description:'Browse source-led virtual assistant operations reports.'},
      {title:'Services',href:'/services',description:'Review role areas and manager-owned decisions.'},
      {title:'Plan a role',href:'/contact',description:'Bring tasks, tools, examples, and decision limits.'},
    ],
  };
}

export const september4ResearchPosts: readonly ResearchPost[] = studies.map(makeStudy);
