import type { BlogPost } from './data';

const references = [
  { name: 'NIST Access Control Project', url: 'https://csrc.nist.gov/projects/access-control', note: 'Use access controls to limit actions to approved people and purposes.' },
  { name: 'CISA More than a Password', url: 'https://www.cisa.gov/more-password', note: 'Protect accounts that handle customer and business records.' },
  { name: 'Google Search Central: Creating helpful content', url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', note: 'Write for a real reader and keep the guidance specific.' },
];

type Draft = {
  slug: string; title: string; excerpt: string; topic: string; thesis: string; decision: string;
  boundary: string; bullets: string[]; owner: string; source: number;
  published: '2026-08-17'; updated: '2026-08-17'; displayDate: 'August 17, 2026';
};

function article(d: Draft): BlogPost {
  return {
    slug: d.slug, published: d.published, updated: d.updated, displayDate: d.displayDate,
    featuredImage: '/featured/virtual-assistant-appointment-setting-philippines.png', title: d.title,
    excerpt: d.excerpt, minutes: 10,
    takeaways: [d.thesis, d.decision, d.boundary],
    sections: [
      { heading: 'Set the operating question', body: `${d.thesis} For a Philippines-based virtual assistant, write the source record, expected output, and review point before the first task. ${d.owner} should provide a finished example and a case that must stop.`, bullets: d.bullets },
      { heading: 'Use evidence that survives a handoff', body: `A useful ${d.topic} record keeps the original request, the check performed, and the unresolved question together. This lets ${d.owner} review the result without reconstructing a chat or guessing which version was current.` },
      { heading: 'Keep judgment with the right owner', body: `${d.boundary} Give the assistant only the access needed for the first lane, and make the escalation request explicit: include the record, what was checked, and the decision required.` },
      { heading: 'Pilot, sample, then expand', body: `Start with a small representative sample of ${d.topic} work. Review accuracy, completeness, source use, and escalation quality. Correct the instruction at the source, then add a related duty only when the first lane is dependable.` },
    ],
    faq: [
      { question: `What should a VA do first with ${d.topic}?`, answer: 'Start with a small record set, clear examples, a named reviewer, and a stop rule for unusual cases.' },
      { question: 'Who decides an exception?', answer: `${d.owner} decides exceptions. The assistant should attach the record, explain what was checked, and identify the decision needed.` },
    ],
    sources: [references[d.source], references[2]], relatedServices: [],
    articleLinks: [{ label: 'onboarding checklist', href: '/blog/virtual-assistant-onboarding-checklist-philippines' }, { label: 'access control guide', href: '/blog/virtual-assistant-access-control-philippines' }, { label: 'NIST access control guidance', href: references[0].url, external: true }],
  };
}

export const august17BlogPosts: BlogPost[] = [
  article({ slug: 'virtual-assistant-refund-request-triage-philippines', title: 'Virtual assistant refund request triage Philippines: separate facts from approval', excerpt: 'Prepare refund cases with complete order evidence while the business owner keeps the decision and customer commitment.', topic: 'refund request triage', thesis: 'Refund triage works when the request, policy evidence, transaction record, and proposed next step are separate.', decision: 'A manager should decide exceptions, disputed facts, and any response outside the approved policy.', boundary: 'Do not approve a refund, promise a credit, or alter an order from an incomplete request.', bullets: ['Capture the original request and order reference.', 'Mark policy matches and missing evidence separately.', 'Route disputes with a concise decision question.'], owner: 'the support or finance owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-customer-complaint-log-philippines', title: 'Virtual assistant customer complaint logs Philippines: preserve the signal for managers', excerpt: 'Build complaint records that retain customer wording, response status, and escalation context for a Philippines-based assistant.', topic: 'customer complaint logs', thesis: 'A complaint log is useful only when it preserves the customer’s issue rather than reducing it to an uncheckable label.', decision: 'The service owner should decide remedies, safety concerns, and repeated-pattern responses.', boundary: 'Do not dismiss a complaint, diagnose a cause, or promise a remedy without the approved owner decision.', bullets: ['Quote only the necessary customer context.', 'Separate event, impact, response, and owner decision.', 'Link repeat complaints to the same issue definition.'], owner: 'the service owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-sales-call-prep-philippines', title: 'Virtual assistant sales call preparation Philippines: brief the seller without inventing fit', excerpt: 'Prepare a source-backed call brief from existing lead records while sales judgment stays with the responsible seller.', topic: 'sales call preparation', thesis: 'A sales brief should distinguish verified context, open questions, and the outcome the seller needs from the call.', decision: 'The seller should decide fit, scope, claims, and any commercial next step.', boundary: 'Do not infer budget, promise an outcome, or represent an unverified fact as a customer requirement.', bullets: ['Link every key fact to the lead record.', 'List questions instead of filling unknown fields.', 'Separate preparation from qualification and negotiation.'], owner: 'the sales owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-demo-follow-up-philippines', title: 'Virtual assistant demo follow-up Philippines: turn notes into owned next steps', excerpt: 'Convert demo notes into clear follow-up tasks without changing commitments or claiming customer approval.', topic: 'demo follow-up', thesis: 'Demo follow-up is reliable when each note is classified as a question, request, decision, or owner task.', decision: 'The account owner should approve commitments, scope changes, and the wording of sensitive replies.', boundary: 'Do not mark interest as approval, add a requirement from inference, or promise a delivery date.', bullets: ['Attach the meeting note and attendee context.', 'Give each action one owner and due point.', 'Flag unresolved requirements for the account owner.'], owner: 'the account owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-recruiting-interview-scheduling-philippines', title: 'Virtual assistant recruiting interview scheduling Philippines: coordinate without judging candidates', excerpt: 'Keep interview logistics accurate while a hiring manager retains candidate evaluation and selection decisions.', topic: 'recruiting interview scheduling', thesis: 'Interview scheduling needs a single current availability record, clear time zones, and a visible owner for changes.', decision: 'The hiring manager should evaluate candidates, change stages, and decide exceptions.', boundary: 'Do not rank a candidate, disclose interview feedback, or reject an applicant from a scheduling issue alone.', bullets: ['Confirm time zone and interviewer availability.', 'Keep candidate contact details in approved records.', 'Route accessibility, conflict, and reschedule questions quickly.'], owner: 'the hiring manager', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-candidate-record-hygiene-philippines', title: 'Virtual assistant candidate record hygiene Philippines: keep recruiting data reviewable', excerpt: 'Maintain candidate records with source notes and controlled changes while hiring decisions remain with the hiring team.', topic: 'candidate record hygiene', thesis: 'Candidate record hygiene means preserving source context, current stage, and the reason a field was changed.', decision: 'The hiring owner should decide retention, evaluation, and any sensitive candidate communication.', boundary: 'Do not infer qualifications, edit interview feedback, or expose candidate information outside the approved process.', bullets: ['Separate candidate statements from reviewer judgments.', 'Record the source and date of corrections.', 'Flag duplicate identities for review instead of merging guesses.'], owner: 'the hiring manager', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-subscription-renewal-tracking-philippines', title: 'Virtual assistant subscription renewal tracking Philippines: surface decisions before dates', excerpt: 'Track renewal dates, owners, and source terms so a Philippines-based assistant can surface choices without committing spend.', topic: 'subscription renewal tracking', thesis: 'Renewal tracking should show the contract source, renewal date, service owner, and decision status in one place.', decision: 'The budget owner should decide whether to renew, cancel, or negotiate a service.', boundary: 'Do not accept a renewal, cancel a service, or represent a commercial term that has not been approved.', bullets: ['Record notice windows from the source agreement.', 'Separate reminder status from renewal approval.', 'Escalate missing terms before the decision deadline.'], owner: 'the budget or procurement owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-website-content-inventory-philippines', title: 'Virtual assistant website content inventory Philippines: find stale pages without rewriting claims', excerpt: 'Create a reviewable inventory of pages, owners, dates, and open factual questions for a Philippines-based assistant.', topic: 'website content inventories', thesis: 'A content inventory is valuable when it maps each page to an owner, purpose, source, and review need.', decision: 'The content owner should approve factual edits, legal language, and publication timing.', boundary: 'Do not invent an update, change a claim, or publish a page because its review date has passed.', bullets: ['Record URL, page purpose, and current owner.', 'Mark factual, design, and access issues separately.', 'Attach the source needed for every proposed claim change.'], owner: 'the content owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-newsletter-draft-review-philippines', title: 'Virtual assistant newsletter draft review Philippines: make approval questions visible', excerpt: 'Prepare newsletter drafts with source links and open decisions while the owner retains audience, claims, and send approval.', topic: 'newsletter draft review', thesis: 'A newsletter draft is easier to approve when factual claims, links, audience, and uncertain wording are marked separately.', decision: 'The publisher should decide the final message, audience, timing, and any sensitive response.', boundary: 'Do not send a campaign, add an unsupported claim, or treat an unreviewed draft as approved copy.', bullets: ['Keep source links beside factual statements.', 'Mark links, dates, and names that need confirmation.', 'Separate editorial changes from audience and send decisions.'], owner: 'the publisher or marketing owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-webinar-registration-admin-philippines', title: 'Virtual assistant webinar registration admin Philippines: keep attendee records accurate', excerpt: 'Maintain registrations, reminders, and attendance states without exposing attendee data or changing event commitments.', topic: 'webinar registration administration', thesis: 'Registration administration needs one current attendee record, a defined status vocabulary, and a route for unusual requests.', decision: 'The event owner should decide access exceptions, cancellations, and attendee-facing commitments.', boundary: 'Do not share attendee lists, promise access, or change event details without approval.', bullets: ['Separate registered, confirmed, attended, and cancelled states.', 'Use approved channels for attendee questions.', 'Flag accessibility and privacy requests for the event owner.'], owner: 'the event owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-community-moderation-philippines', title: 'Virtual assistant community moderation Philippines: apply rules and escalate edge cases', excerpt: 'Support community moderation with consistent labels, evidence, and escalation while policy judgment stays with the owner.', topic: 'community moderation', thesis: 'Moderation is consistent when the assistant can point to the rule, the observed content, and the action available at that level.', decision: 'The community owner should decide bans, policy exceptions, and ambiguous safety concerns.', boundary: 'Do not invent a rule, reveal reporter identity, or make a permanent decision on an unclear case.', bullets: ['Record the relevant rule and minimum necessary evidence.', 'Use temporary review states for ambiguous cases.', 'Escalate threats, privacy concerns, and repeated edge cases.'], owner: 'the community owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-podcast-guest-coordination-philippines', title: 'Virtual assistant podcast guest coordination Philippines: protect details and commitments', excerpt: 'Coordinate guest availability, preparation notes, and follow-ups while the host keeps editorial and commercial decisions.', topic: 'podcast guest coordination', thesis: 'Guest coordination works when availability, agreed topics, preparation needs, and outstanding approvals are distinct.', decision: 'The host or producer should approve topics, promises, recording changes, and sensitive disclosures.', boundary: 'Do not publish guest details, promise placement, or change the agreed topic without approval.', bullets: ['Keep time zones and recording constraints current.', 'Separate guest-provided facts from editorial suggestions.', 'Route topic, consent, and cancellation questions to the producer.'], owner: 'the host or producer', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-course-enrollment-records-philippines', title: 'Virtual assistant course enrollment records Philippines: support learners without changing outcomes', excerpt: 'Keep enrollment and access records accurate while course owners retain grading, refund, and policy decisions.', topic: 'course enrollment records', thesis: 'Enrollment administration needs a current learner record, access state, source event, and clear route for exceptions.', decision: 'The course owner should decide access disputes, completion outcomes, refunds, and policy exceptions.', boundary: 'Do not alter a grade, promise completion, or change access for a disputed learner without approval.', bullets: ['Record enrollment source and current access state.', 'Separate technical access from learning outcome.', 'Escalate identity, payment, and accessibility questions.'], owner: 'the course owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-product-feedback-synthesis-philippines', title: 'Virtual assistant product feedback synthesis Philippines: group evidence without overstating demand', excerpt: 'Organize product feedback into traceable themes while product owners decide priorities and interpretation.', topic: 'product feedback synthesis', thesis: 'Feedback synthesis should preserve the original signal, show how themes were formed, and distinguish frequency from importance.', decision: 'The product owner should decide priority, scope, and whether a theme warrants action.', boundary: 'Do not claim customer consensus, merge different problems, or promise a roadmap change.', bullets: ['Keep representative source excerpts and dates.', 'Separate observed requests from interpretation.', 'Show missing evidence and conflicting feedback.'], owner: 'the product owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-competitor-research-table-philippines', title: 'Virtual assistant competitor research tables Philippines: compare evidence, not impressions', excerpt: 'Build a checkable competitor table for provider decisions without presenting unverified claims as market facts.', topic: 'competitor research tables', thesis: 'A competitor table is useful when each comparison field has a source, check date, definition, and confidence note.', decision: 'The business owner should decide positioning and claims after reviewing source quality and gaps.', boundary: 'Do not scrape restricted data, invent provider capabilities, or publish a competitor claim without verification.', bullets: ['Define each comparison field before collecting it.', 'Record source URL and check date for every material fact.', 'Mark unknowns instead of filling them with assumptions.'], owner: 'the strategy or business owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-market-survey-cleanup-philippines', title: 'Virtual assistant market survey cleanup Philippines: repair responses without changing meaning', excerpt: 'Prepare survey responses for analysis while preserving respondent meaning and leaving interpretation to the research owner.', topic: 'market survey cleanup', thesis: 'Survey cleanup should document each correction, preserve the raw response, and distinguish formatting from interpretation.', decision: 'The research owner should decide coding rules, exclusions, and conclusions.', boundary: 'Do not rewrite an answer, infer demographics, or remove an inconvenient response without the approved rule.', bullets: ['Keep raw and cleaned versions distinct.', 'Record the field, reason, and rule for each correction.', 'Flag ambiguous responses for the research owner.'], owner: 'the research owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-operations-calendar-philippines', title: 'Virtual assistant operations calendar Philippines: expose dependencies before deadlines', excerpt: 'Maintain an operations calendar that shows owners, dependencies, and decision points without silently changing priorities.', topic: 'operations calendars', thesis: 'An operations calendar becomes useful when each date has an owner, dependency, source, and definition of ready.', decision: 'The operations owner should resolve priority conflicts, missed dependencies, and deadline changes.', boundary: 'Do not move a critical date, promise completion, or hide a dependency because a calendar slot is empty.', bullets: ['Separate fixed dates from target dates.', 'Link each milestone to its source task or agreement.', 'Flag dependency risk before the due date.'], owner: 'the operations owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-process-mapping-philippines', title: 'Virtual assistant process mapping Philippines: show handoffs before assigning work', excerpt: 'Map a recurring process so a Philippines-based assistant can own a defined lane and escalate cleanly at boundaries.', topic: 'process mapping', thesis: 'A process map should show inputs, outputs, handoffs, decisions, and failure points rather than only a list of tasks.', decision: 'The process owner should decide policy, exception handling, and changes to the operating model.', boundary: 'Do not turn an observed habit into policy, remove a control, or assign approval to the assistant by implication.', bullets: ['Name the record that starts and ends each step.', 'Mark decisions and their owners explicitly.', 'Test the map against one normal and one exception case.'], owner: 'the process owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-workload-review-philippines', title: 'Virtual assistant workload review Philippines: adjust scope from evidence', excerpt: 'Review task volume, interruptions, and unresolved work so managers can adjust a VA role without guessing at performance.', topic: 'workload reviews', thesis: 'A workload review should separate volume, complexity, waiting time, rework, and owner decisions instead of treating all tasks as equal.', decision: 'The manager should decide scope, staffing, coaching, and priority changes from the evidence.', boundary: 'Do not turn a partial sample into a performance verdict or use hidden work as a capacity claim.', bullets: ['Define the period and task categories.', 'Record blocked time and rework separately.', 'Ask the owner to resolve competing priorities.'], owner: 'the manager or role owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-approval-matrix-philippines', title: 'Virtual assistant approval matrix Philippines: clarify who can prepare and decide', excerpt: 'Create an approval matrix that makes role boundaries visible across routine VA work and unusual cases.', topic: 'approval matrices', thesis: 'An approval matrix is practical when each action has a preparer, reviewer, decision owner, evidence requirement, and escalation route.', decision: 'The accountable business owner should approve changes to authority, risk, and access.', boundary: 'Do not infer authority from a job title, approve an exception by silence, or broaden access to compensate for an unclear rule.', bullets: ['List actions rather than vague departments.', 'State the evidence required before approval.', 'Review the matrix when tools, owners, or risk changes.'], owner: 'the accountable business owner', source: 0, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-business-continuity-notes-philippines', title: 'Virtual assistant business continuity notes Philippines: preserve the next safe action', excerpt: 'Document continuity steps for recurring VA work so coverage can begin without granting unnecessary access or inventing decisions.', topic: 'business continuity notes', thesis: 'Continuity notes should identify the current state, next safe action, critical source, and owner for unresolved decisions.', decision: 'The business owner should decide emergency priorities, access changes, and customer-impacting exceptions.', boundary: 'Do not share credentials, bypass an approval, or improvise a high-impact response from an incomplete note.', bullets: ['Record current status and last verified time.', 'Name the smallest safe task a backup can perform.', 'List decisions that must wait for the owner.'], owner: 'the business continuity owner', source: 1, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
  article({ slug: 'virtual-assistant-workflow-handover-philippines', title: 'Virtual assistant workflow handover Philippines: transfer context, not just task lists', excerpt: 'Prepare a workflow handover packet that explains recurring work, evidence, exceptions, and role boundaries for a Philippines-based assistant.', topic: 'workflow handovers', thesis: 'A workflow handover succeeds when the learner receives context, examples, source locations, and a way to test understanding.', decision: 'The role owner should confirm readiness and decide when the learner may take the next responsibility.', boundary: 'Do not transfer undocumented assumptions, sensitive access, or an unapproved exception as if it were a standard step.', bullets: ['Pair each task with a purpose and finished example.', 'Include an exception that requires a stop.', 'Use a small observed work sample before sign-off.'], owner: 'the role owner', source: 2, published: '2026-08-17', updated: '2026-08-17', displayDate: 'August 17, 2026' }),
];
