import type { ResearchPost } from './fleet-content';
const studies = [['virtual-assistant-routine-control-evidence-research', 'routine control', 'written inputs, outputs, owners, and exception rules'], ['virtual-assistant-handoff-record-evidence-research', 'handoff records', 'records that carry decisions and blockers across working hours'], ['virtual-assistant-access-review-evidence-research', 'access review', 'named accounts and periodic permission checks'], ['virtual-assistant-quality-sampling-evidence-research', 'quality sampling', 'reviewing useful samples without checking every task forever'], ['virtual-assistant-exception-log-evidence-research', 'exception logs', 'records that reveal unclear rules and recurring risk']] as const;
const sources = [{ id: 1, name: 'The NIST Cybersecurity Framework (CSF) 2.0', organization: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20', published: '2024-02-26', accessed: '2026-08-31' }, { id: 2, name: 'Cybersecurity Framework FAQs', organization: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/cyberframework/faqs', accessed: '2026-08-31' }, { id: 3, name: 'Creating helpful, reliable, people-first content', organization: 'Google Search Central', url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', accessed: '2026-08-31' }] as const;
export const august31ResearchPosts: ResearchPost[] = studies.map(([slug, keyword, question]) => ({
  slug, featuredImage: '/featured/publishing-contingency-routine.png', primaryKeyword: `virtual assistant ${keyword}`, title: `Research: ${keyword} for virtual assistant teams`, metaTitle: `Virtual assistant ${keyword} research`, excerpt: `A source-led review of ${question}, with practical limits for buyers and managers.`, published: '2026-08-31', updated: '2026-08-31', readingMinutes: 10, revision: `2026-08-31-${slug}-v1`,
  takeaways: [`Treat ${keyword} as a management record, not a guarantee.`, 'Assign an owner, source, finish line, and stop rule.', 'Use named accounts and minimum permissions.', 'Review exceptions because they show where controls need repair.'],
  headlineStats: [{ value: '6', label: 'CSF 2.0 functions', context: 'NIST organizes CSF 2.0 around Govern, Identify, Protect, Detect, Respond, and Recover.', sourceIds: [1, 2] }, { value: '1 owner', label: 'Decision accountability', context: 'Each lane needs a named person who decides exceptions.', sourceIds: [1] }, { value: 'Named', label: 'Account standard', context: 'Unique accounts preserve attribution and support access review.', sourceIds: [1] }, { value: 'Sample', label: 'Review unit', context: 'Sample size depends on task risk and error history.', sourceIds: [1] }, { value: '0', label: 'Guaranteed outcomes', context: 'The sources provide guidance, not a performance guarantee.', sourceIds: [1, 2] }, { value: '2026-08-31', label: 'Evidence accessed', context: 'Sources were checked on August 31, 2026.', sourceIds: [1, 2, 3] }],
  sections: [
    { heading: `The research question: ${question}`, paragraphs: [`This report examines ${keyword} as an operating control for a Philippines-based virtual assistant. The question is what record lets a manager see the input, action, exception, and owner decision without recreating the work.`, 'NIST CSF 2.0 separates governance, identification, protection, detection, response, and recovery outcomes.[1][2] The framework is voluntary and non-prescriptive, so this article applies those outcomes rather than presenting a required formula.'] },
    { heading: 'What the evidence supports', paragraphs: ['NIST describes outcomes organizations can use regardless of size, sector, or maturity.[1] Govern maps to ownership; Protect maps to permissions; Detect maps to review; Respond maps to escalation; Recover maps to correcting the record.', `That mapping supports a ${keyword} record with a source, expected output, worker, completion proof, exception, and owner decision. It does not prove that a provider follows the record or that the record catches every error.`] },
    { heading: 'A practical routine', paragraphs: [`Begin with one task and define its ${keyword} evidence. Review every completion during the first week. Move to sampling only after accurate work, then return to full review after a serious miss, process change, or access change.`, 'Keep the record close to the work. A task ID, source link, output link, exception note, and reviewer are usually enough.'] },
    { heading: 'People-first documentation', paragraphs: ['Google Search Central recommends explaining who, how, and why.[3] Those questions improve operating documentation: who owns the decision, how work is checked, and why the record exists.', `A ${keyword} document should help the next person act. If it only proves that someone filled out a form, it has failed.`] },
    { heading: 'Limits', paragraphs: ['This is a qualitative application of public guidance, not an audit, controlled study, legal opinion, or client measurement.', 'Review rates depend on task risk, volume, error history, and manager capacity. Qualified advice may be required.'] },
    { heading: 'Conclusion', paragraphs: [`The evidence supports treating ${keyword} as a compact control with a named owner and visible limits.[1][2] Start with the source and finish line, limit access, review early work, and keep exceptions.`] },
  ],
  evidenceTable: [{ signal: 'Govern', finding: 'CSF 2.0 adds governance.', buyerUse: 'Name the owner and decision limit.', limit: 'The framework does not assign roles.', sourceIds: [1, 2] }, { signal: 'Protect', finding: 'Protection includes safeguards.', buyerUse: 'Use named accounts and minimum access.', limit: 'Limited access does not remove all risk.', sourceIds: [1] }, { signal: 'Detect and respond', finding: 'Detection and response are separate.', buyerUse: 'Review samples and route exceptions.', limit: 'A sample can miss an error.', sourceIds: [1] }, { signal: 'Recover', finding: 'Recovery continues the cycle.', buyerUse: 'Correct records and instructions.', limit: 'Corrections cannot undo every impact.', sourceIds: [1] }],
  implications: [{ title: 'For buyers', body: `Ask for a redacted ${keyword} record.` }, { title: 'For managers', body: 'Choose review frequency from risk and error history.' }, { title: 'For assistants', body: 'Record sources, outputs, and exceptions while work is fresh.' }, { title: 'For providers', body: 'Explain coaching, access, replacement, and incident ownership.' }],
  methodology: ['We reviewed NIST CSF 2.0, its FAQ, and Google Search Central guidance on August 31, 2026.', `We mapped source outcomes to ${keyword} and separated claims from recommendations.`, 'No client, worker, or provider data was used.'],
  faq: [{ question: `What belongs in a ${keyword} record?`, answer: 'Include the source, output, worker, proof, exception, and owner decision.' }, { question: 'Review every task?', answer: 'Review every task at launch. Later sampling depends on risk and error history.' }, { question: 'Does this prove security?', answer: 'No. Provider controls require direct evidence and testing.' }, { question: 'What triggers review?', answer: 'A serious miss, repeated errors, or system and access changes.' }],
  sources, related: [{ title: 'Escalation rules', href: '/blog/virtual-assistant-escalation-rules-philippines', description: 'A related operating guide.' }, { title: 'Research library', href: '/research', description: 'Browse source-led reports.' }, { title: 'Plan a role', href: '/contact', description: 'Bring tasks, tools, and limits.' }],
}));
