import type { BlogPost } from './data';

const topics = [
  ['virtual-assistant-september-2-daily-request-intake-routine','daily request intake','Capture the requester, outcome, deadline, source material, and approval owner.','An intake record prevents an urgent message from becoming an untraceable assignment.'],
  ['virtual-assistant-september-2-priority-queue-review-routine','priority queue review','Sort work by business impact, due time, dependency, and blocker owner.','A queue review makes tradeoffs visible without letting the assistant invent business priorities.'],
  ['virtual-assistant-september-2-meeting-preparation-routine','meeting preparation','Confirm the purpose, attendees, agenda, prior decisions, links, and questions.','Preparation reduces search time while leaving meeting decisions with participants.'],
  ['virtual-assistant-september-2-action-item-tracking-routine','action item tracking','Record every commitment with one owner, due date, source meeting, and follow-up point.','A useful register distinguishes a promise from a suggestion or discussion note.'],
  ['virtual-assistant-september-2-invoice-document-prep-routine','invoice document preparation','Gather approved invoices, purchase references, receipts, discrepancies, and the finance owner.','The assistant organizes evidence but does not approve payment or choose accounting treatment.'],
  ['virtual-assistant-september-2-lead-response-routing-routine','lead response routing','Identify the inquiry source, requested service, consent status, urgency, and salesperson.','Routing protects response time without turning administration into unsupervised selling.'],
  ['virtual-assistant-september-2-customer-feedback-log-routine','customer feedback logging','Preserve the customer wording, channel, product area, severity, request, and team owner.','A feedback log retains themes without claiming every comment represents the customer base.'],
  ['virtual-assistant-september-2-knowledge-base-review-routine','knowledge base review','Check article ownership, verification date, broken links, product changes, and unanswered questions.','Review finds stale guidance; a qualified owner approves policy or product changes.'],
  ['virtual-assistant-september-2-shared-drive-cleanup-routine','shared drive cleanup','Inventory duplicates, unclear names, obsolete drafts, owners, permissions, and archive locations.','Cleanup starts with a reversible proposal so evidence is not moved or deleted without approval.'],
  ['virtual-assistant-september-2-recurring-task-audit-routine','recurring task audit','Compare scheduled work with actual use, misses, duplicate outputs, owners, and stop candidates.','An audit exposes routine clutter and gives the manager evidence for what to retire.'],
  ['virtual-assistant-september-2-approval-follow-up-routine','approval follow-up','List the decision, supporting record, approver, age, delay impact, and next reminder.','Follow-up makes waiting visible without asking the assistant to approve for someone else.'],
  ['virtual-assistant-september-2-daily-risk-flag-routine','daily risk flag review','Summarize security alerts, unusual requests, threats, access changes, and source conflicts.','A risk flag is an early warning record, not a diagnosis or specialist judgment.'],
] as const;
const sources=[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20',note:'Use governance, protection, detection, response, and recovery outcomes to define owners and escalation.'},{name:'Google Search Central people-first content guidance',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content',note:'Make records useful to the person who must understand the work and take the next action.'}];
export const september2BlogPosts: BlogPost[]=topics.map(([slug,routine,evidence,distinction],index)=>({
 slug,featuredImage:'/featured/publishing-contingency-routine.png',title:`Virtual assistant ${routine} content workflow: an accountable daily workflow`,excerpt:`A practical ${routine} workflow for a Philippines-based assistant, with a clear finish line, evidence record, and manager-owned exceptions.`,minutes:9,published:'2026-09-02',updated:'2026-09-02',displayDate:'September 2, 2026',
 takeaways:[`Define the finished ${routine} record before assigning the task.`,evidence,'Give exceptions to a named owner and preserve the source that prompted the question.','Review the routine after misses, business changes, or permission changes.'],
 sections:[
  {heading:`Set the finish line for ${routine}`,body:`${evidence} ${distinction} Write the destination, cutoff time, and reader next to the task. A Philippines-based virtual assistant can then prepare a consistent output across working hours without guessing why it matters.`},
  {heading:'Separate preparation from decisions',body:`Write three lanes for this ${routine}: actions the assistant may complete, drafts that need approval, and conditions that stop work. Keep spending, legal conclusions, sensitive personnel choices, permission expansion, and customer promises with the responsible owner.`,bullets:[`Name the manager who owns ${routine} exceptions.`,'Use only approved tools and named accounts.','State how quickly a blocker must be raised.','Record the owner decision after escalation.']},
  {heading:'Use a five-day calibration',body:`Demonstrate one complete ${routine} record on day one. Review the next two records in full. On days four and five, compare output with its source, correct ambiguous instructions, and agree which errors trigger renewed full review.`},
  {heading:'Keep evidence close to the work',body:`The ${routine} record should identify its source, output location, completion time, exceptions, and reviewer. A stable task or document link is usually more useful than an isolated screenshot. Named accounts preserve attribution.`},
  {heading:'Review causes, not just symptoms',body:`When ${routine} misses its finish line, check whether the input was incomplete, instruction unclear, access missing, or review late. Repair that cause. Every retained field should support a decision, handoff, or audit trail.`},
  {heading:'Run a monthly usefulness test',body:`Ask the next reader whether the ${routine} output saved time or supported a decision. ${distinction} Retire duplicate outputs, clarify recurring exceptions, and keep the smallest record that reliably moves work forward.`}],
 faq:[{question:`Who owns the ${routine}?`,answer:'The assistant can own preparation and repeatable execution. A named manager owns exceptions, approvals, access changes, and business judgment.'},{question:'What should the completion record contain?',answer:`Keep the source, finished output, completion time, exception status, and reviewer decision. This workflow also documents: ${evidence.toLowerCase()}`},{question:'When can review move to sampling?',answer:'Move from full review only after consistently accurate output and timely escalation. Return after a serious miss or process change.'}],
 sources,relatedServices:[],articleLinks:[{label:'daily planning guide',href:'/blog/virtual-assistant-daily-planning-philippines'},{label:index%2===0?'handoff guide':'escalation rules guide',href:index%2===0?'/blog/virtual-assistant-handoff-philippines':'/blog/virtual-assistant-escalation-rules-philippines'},{label:'NIST Cybersecurity Framework 2.0',href:sources[0].url,external:true}],
}));
