import type { BlogPost } from './data';

const sources = [
  { name: 'NIST Access Control Project', url: 'https://csrc.nist.gov/projects/access-control', note: 'Limit each role to the actions and records it needs.' },
  { name: 'CISA More than a Password', url: 'https://www.cisa.gov/more-password', note: 'Protect accounts that handle customer and business records.' },
  { name: 'Google Search Central: Creating helpful content', url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', note: 'Write for a real reader and keep the guidance specific.' },
];

type Draft = { slug: string; title: string; topic: string; excerpt: string; point: string; boundary: string; bullets: string[]; owner: string; source: number };

function article(draft: Draft): BlogPost {
  return {
    slug: draft.slug, published: '2026-08-14', updated: '2026-08-14', displayDate: 'August 14, 2026',
    featuredImage: '/featured/virtual-assistant-appointment-setting-philippines.png', title: draft.title, excerpt: draft.excerpt, minutes: 9,
    takeaways: [draft.point, draft.bullets[0], draft.boundary],
    sections: [
      { heading: 'Define the record before the task', body: `${draft.point} For a Philippines-based virtual assistant, start with the source record, the expected result, and the point where the work must pause. ${draft.owner} should provide one finished example and one incomplete example.`, bullets: draft.bullets },
      { heading: 'Make the handoff easy to check', body: `A useful ${draft.topic} handoff names what was checked, when it was checked, and what remains open. Keep the source beside the summary so ${draft.owner} can review the work without reconstructing the conversation.` },
      { heading: 'Keep decisions with the owner', body: `${draft.boundary} Give the role only the access needed for its first lane. Record corrections where the next person will see them.` },
      { heading: 'Review a small sample first', body: `Sample early ${draft.topic} work for accuracy, completeness, and clear escalation. Add another responsibility only after the first set is dependable. When a source conflicts, preserve the conflict and ask ${draft.owner} to decide.` },
    ],
    faq: [
      { question: `What should a VA do first with ${draft.topic}?`, answer: 'Begin with a small record set, clear examples, a named reviewer, and a stop rule for unusual cases.' },
      { question: 'Who decides an exception?', answer: `${draft.owner} decides exceptions. The assistant should attach the record, explain what was checked, and identify the decision needed.` },
    ],
    sources: [sources[draft.source], sources[2]], relatedServices: [],
    articleLinks: [
      { label: 'onboarding checklist', href: '/blog/virtual-assistant-onboarding-checklist-philippines' },
      { label: 'access control guide', href: '/blog/virtual-assistant-access-control-philippines' },
      { label: 'NIST access control guidance', href: sources[0].url, external: true },
    ],
  };
}

export const august14BlogPosts: BlogPost[] = [
  article({ slug: 'virtual-assistant-inbox-cleanup-philippines', title: 'Virtual assistant inbox cleanup Philippines: sort messages by decision owner', topic: 'inbox cleanup', excerpt: 'A practical inbox-cleanup guide for a Philippines-based virtual assistant who separates routine replies from decisions that need the owner.', point: 'Inbox cleanup works when every message has a next owner, a due point, and a reason for its label.', boundary: 'Do not delete messages, send a sensitive reply, or make a commitment from an inbox label alone.', bullets: ['Use labels tied to action and owner.', 'Keep drafts separate from sent replies.', 'Flag unclear, legal, financial, and customer-risk messages.'], owner: 'the inbox owner', source: 0 }),
  article({ slug: 'virtual-assistant-travel-research-philippines', title: 'Virtual assistant travel research Philippines: compare options without booking', topic: 'travel research', excerpt: 'How to prepare travel options, constraints, and open questions while the responsible person keeps the final booking decision.', point: 'Travel research is easier to review when each option shows dates, constraints, source, and what still needs confirmation.', boundary: 'Do not book, cancel, disclose passport details, or assume a preference that the traveler has not confirmed.', bullets: ['Record the traveler, dates, and hard constraints.', 'Link each option to its source and check time.', 'Separate a researched option from an approved itinerary.'], owner: 'the traveler or travel owner', source: 2 }),
  article({ slug: 'virtual-assistant-meeting-agenda-philippines', title: 'Virtual assistant meeting agendas Philippines: give busy teams a useful starting point', topic: 'meeting agendas', excerpt: 'Build concise agendas from prior notes, open decisions, and attendee input with a Philippines-based virtual assistant.', point: 'An agenda should show why the meeting exists, what decision is needed, and which background record supports it.', boundary: 'Do not invent a decision, attribute an opinion to an attendee, or circulate sensitive notes to the wrong group.', bullets: ['Collect proposed items with an owner.', 'Link prior notes and unresolved questions.', 'Mark information items separately from decisions.'], owner: 'the meeting owner', source: 2 }),
  article({ slug: 'virtual-assistant-meeting-notes-philippines', title: 'Virtual assistant meeting notes Philippines: separate decisions from discussion', topic: 'meeting notes', excerpt: 'A clear approach to recording decisions, owners, and open questions after meetings supported by a Philippines-based assistant.', point: 'Good notes distinguish a decision, an action, a question, and a comment so readers do not mistake discussion for approval.', boundary: 'Do not rewrite uncertainty as agreement or publish notes that include private comments without approval.', bullets: ['Record the decision wording and decision owner.', 'Give each action one owner and due point.', 'Mark unresolved items for follow-up.'], owner: 'the meeting owner', source: 2 }),
  article({ slug: 'virtual-assistant-calendar-conflict-philippines', title: 'Virtual assistant calendar conflicts Philippines: resolve overlaps with clear rules', topic: 'calendar conflict review', excerpt: 'Use a simple conflict-review process for a Philippines-based virtual assistant who protects the owner’s time without guessing priorities.', point: 'A calendar conflict needs the meetings involved, the constraints, and the person who can choose what moves.', boundary: 'Do not cancel a customer or hiring meeting, disclose private calendar details, or infer priority from meeting length.', bullets: ['Show time zone and attendee owner.', 'List the conflict and each known constraint.', 'Route the choice with a proposed next step.'], owner: 'the calendar owner', source: 0 }),
  article({ slug: 'virtual-assistant-appointment-reminders-philippines', title: 'Virtual assistant appointment reminders Philippines: keep confirmations accurate', topic: 'appointment reminders', excerpt: 'A bounded guide to preparing appointment reminders, tracking replies, and routing changes for a Philippines-based assistant.', point: 'Reminder work needs one current appointment record, an approved message, and a visible status for confirmation or change.', boundary: 'Do not change a service, promise availability, or reveal private appointment details outside the approved channel.', bullets: ['Confirm time zone, location, and contact record.', 'Use separate confirmed, declined, and unanswered states.', 'Route reschedules and unusual requests to the owner.'], owner: 'the appointment owner', source: 0 }),
  article({ slug: 'virtual-assistant-email-draft-review-philippines', title: 'Virtual assistant email draft review Philippines: make approval quick and precise', topic: 'email draft review', excerpt: 'Prepare email drafts with source links, open questions, and a clear approval line for a Philippines-based virtual assistant.', point: 'A draft is easier to approve when the requested outcome, supporting record, and uncertain wording are visible together.', boundary: 'Do not send a sensitive message, change a commitment, or sign for the owner without explicit approval.', bullets: ['State the intended recipient and outcome.', 'Mark claims that need confirmation.', 'Keep the approval request separate from the draft body.'], owner: 'the email owner', source: 2 }),
  article({ slug: 'virtual-assistant-contact-list-cleanup-philippines', title: 'Virtual assistant contact list cleanup Philippines: fix records without losing context', topic: 'contact list cleanup', excerpt: 'A careful method for identifying duplicate and stale contacts while a Philippines-based assistant preserves the source record.', point: 'Contact cleanup should show which records were compared and why a merge, archive, or review is suggested.', boundary: 'Do not merge uncertain identities, remove a contact, or change consent status without the responsible owner.', bullets: ['Compare names, organizations, and source details.', 'Keep possible duplicates in a review queue.', 'Record the reason for every approved change.'], owner: 'the contact-data owner', source: 0 }),
  article({ slug: 'virtual-assistant-lead-response-routing-philippines', title: 'Virtual assistant lead response routing Philippines: send replies to the right owner', topic: 'lead response routing', excerpt: 'Organize inbound lead details and owner handoffs without making claims or promises on behalf of the business.', point: 'Lead routing needs a complete source message, a clear fit question, and the owner who can respond next.', boundary: 'Do not qualify beyond approved rules, promise a result, or submit a lead form on someone’s behalf.', bullets: ['Preserve the original inquiry and received time.', 'Use approved categories for routing.', 'Escalate requests that need a specialist answer.'], owner: 'the sales or service owner', source: 2 }),
  article({ slug: 'virtual-assistant-proposal-formatting-philippines', title: 'Virtual assistant proposal formatting Philippines: prepare a clean review copy', topic: 'proposal formatting', excerpt: 'Help a Philippines-based virtual assistant format proposal material while the business owner keeps scope and commitment decisions.', point: 'Formatting support should make scope, assumptions, open fields, and approval points easier to inspect.', boundary: 'Do not invent deliverables, edit a commitment, or send a proposal without owner approval.', bullets: ['Keep source wording beside proposed edits.', 'Mark missing scope, dates, and assumptions.', 'Separate formatting changes from commercial decisions.'], owner: 'the proposal owner', source: 2 }),
  article({ slug: 'virtual-assistant-client-onboarding-philippines', title: 'Virtual assistant client onboarding Philippines: collect the right starting details', topic: 'client onboarding', excerpt: 'A practical intake guide for collecting client context, contacts, and first tasks without overpromising or widening access.', point: 'Client onboarding is clearer when goals, first tasks, source documents, and unanswered questions have separate fields.', boundary: 'Do not promise outcomes, accept a policy exception, or request sensitive access before the owner confirms the need.', bullets: ['Record the client’s goal in their own terms.', 'List the first task lane and source location.', 'Route access, legal, and service questions to the owner.'], owner: 'the account owner', source: 0 }),
  article({ slug: 'virtual-assistant-client-update-philippines', title: 'Virtual assistant client updates Philippines: report progress without hiding gaps', topic: 'client updates', excerpt: 'Write useful client updates that distinguish completed work, open questions, and decisions still needed.', point: 'A progress update should show what changed since the last note and what the client or owner must decide next.', boundary: 'Do not report an unverified task as complete or hide a delay behind a vague status phrase.', bullets: ['Use source-backed status labels.', 'List blockers with an owner and next check.', 'Keep private internal notes out of the client copy.'], owner: 'the account owner', source: 2 }),
  article({ slug: 'virtual-assistant-service-request-intake-philippines', title: 'Virtual assistant service request intake Philippines: turn vague asks into clear next steps', topic: 'service request intake', excerpt: 'Capture the details needed to route a client or customer request without forcing the assistant to guess the intended outcome.', point: 'A useful request record states who asked, what outcome they want, what evidence exists, and who can approve the next action.', boundary: 'Do not promise a deadline, change a service rule, or close a request because the description is incomplete.', bullets: ['Record the original request and received time.', 'Ask for the smallest missing fact.', 'Use a visible status for owner review.'], owner: 'the service owner', source: 2 }),
  article({ slug: 'virtual-assistant-faq-maintenance-philippines', title: 'Virtual assistant FAQ maintenance Philippines: keep answers tied to approved facts', topic: 'FAQ maintenance', excerpt: 'Keep customer-facing answers current by tracking source ownership, review dates, and questions that still need an answer.', point: 'An FAQ entry should have a source, an owner, a review point, and wording that matches the actual service rule.', boundary: 'Do not publish an answer from memory, add an exception as a general rule, or claim a feature that has not been confirmed.', bullets: ['Link each answer to an owner or source.', 'Mark stale and disputed entries for review.', 'Keep internal notes out of public answers.'], owner: 'the service or support owner', source: 2 }),
  article({ slug: 'virtual-assistant-customer-record-update-philippines', title: 'Virtual assistant customer record updates Philippines: change only what the source supports', topic: 'customer record updates', excerpt: 'A safe record-update lane for a Philippines-based assistant who keeps customer details accurate and changes traceable.', point: 'A customer-record update should identify the source, the field changed, and the person who can approve an uncertain correction.', boundary: 'Do not change identity, consent, payment, or account ownership fields without the required approval.', bullets: ['Record the source and received date.', 'Separate confirmed corrections from suggestions.', 'Keep a review trail for sensitive fields.'], owner: 'the customer-record owner', source: 0 }),
  article({ slug: 'virtual-assistant-shared-drive-organization-philippines', title: 'Virtual assistant shared drive organization Philippines: make files findable and current', topic: 'shared-drive organization', excerpt: 'Organize shared files with a Philippines-based virtual assistant while protecting ownership, access, and approved versions.', point: 'A useful file structure tells people where current work lives, who owns it, and what status each document has.', boundary: 'Do not delete a file, broaden access, or move an approved source without the owner’s rule.', bullets: ['Use folders and names that match the team’s vocabulary.', 'Keep current, draft, and archived states distinct.', 'Record owner and access questions beside the file index.'], owner: 'the document owner', source: 0 }),
  article({ slug: 'virtual-assistant-receipt-organization-philippines', title: 'Virtual assistant receipt organization Philippines: prepare records for review', topic: 'receipt organization', excerpt: 'A bounded way to collect and label receipts while leaving accounting treatment and approval with the responsible owner.', point: 'Receipt organization works when each file has a date, source, transaction reference, and a clear missing-field note.', boundary: 'Do not classify a disputed expense, alter a receipt, or approve reimbursement from file presence alone.', bullets: ['Match each receipt to the available transaction record.', 'Flag unreadable or conflicting details.', 'Keep submitted and approved states separate.'], owner: 'the finance owner', source: 0 }),
  article({ slug: 'virtual-assistant-invoice-follow-up-philippines', title: 'Virtual assistant invoice follow-up Philippines: track questions before payment review', topic: 'invoice follow-up', excerpt: 'Track invoice status and missing details with a Philippines-based assistant without authorizing payment or changing terms.', point: 'An invoice follow-up record should show the supplier, invoice reference, question asked, and person who can resolve it.', boundary: 'Do not approve payment, change bank details, or confirm a disputed balance from an email alone.', bullets: ['Match the invoice to the approved supplier record.', 'Use a separate status for missing information.', 'Verify sensitive changes through the approved channel.'], owner: 'the finance or procurement owner', source: 0 }),
  article({ slug: 'virtual-assistant-vendor-contact-philippines', title: 'Virtual assistant vendor contact Philippines: keep supplier conversations usable', topic: 'vendor contact records', excerpt: 'Keep supplier conversations, commitments, and follow-up questions organized without allowing a Philippines-based assistant to negotiate.', point: 'Vendor contact notes should separate what the supplier said, what the contract says, and what the owner still needs to decide.', boundary: 'Do not accept changed terms, promise payment, or disclose another supplier’s information.', bullets: ['Link the message to the supplier and contract record.', 'Record due dates and open questions.', 'Route changes and disputes to the owner.'], owner: 'the procurement owner', source: 2 }),
  article({ slug: 'virtual-assistant-training-materials-philippines', title: 'Virtual assistant training materials Philippines: turn examples into a usable starter set', topic: 'training materials', excerpt: 'Prepare role examples and reference notes that help a Philippines-based assistant learn the work without turning guesses into policy.', point: 'Useful training material pairs a normal example with an exception, the source rule, and the question to ask when the case differs.', boundary: 'Do not present an unapproved draft as policy or let training notes override the current owner instruction.', bullets: ['Label examples by task and outcome.', 'Include at least one stop-and-ask case.', 'Name the owner who confirms changes.'], owner: 'the role owner', source: 2 }),
  article({ slug: 'virtual-assistant-feedback-request-philippines', title: 'Virtual assistant feedback requests Philippines: ask for corrections people can use', topic: 'feedback requests', excerpt: 'Make feedback on assistant work specific enough to correct the source task and the next handoff.', point: 'A useful feedback request names the record, the expected result, the observed gap, and the question for the reviewer.', boundary: 'Do not use feedback to assign blame, expose private information, or change a rule without the owner.', bullets: ['Point to the exact sentence, field, or step.', 'Separate preference from an actual requirement.', 'Record the agreed correction where the role can find it.'], owner: 'the reviewer or role owner', source: 2 }),
  article({ slug: 'virtual-assistant-weekly-business-review-philippines', title: 'Virtual assistant weekly business review Philippines: bring owners the facts they need', topic: 'weekly business reviews', excerpt: 'Prepare a compact review packet from current records, open decisions, and recurring questions for a Philippines-based assistant.', point: 'A review packet should show completed work, unresolved items, evidence, and the few decisions that need owner attention.', boundary: 'Do not turn a small sample into a broad performance claim or hide missing evidence in a score.', bullets: ['Use the same definitions each week.', 'Link exceptions to the source record.', 'Separate observation from interpretation and decision.'], owner: 'the business owner', source: 2 }),
];
