import type { ResearchPost, ResearchSource } from './fleet-content';

const source = (id:number,name:string,organization:string,url:string):ResearchSource => ({id,name,organization,url,accessed:'2026-09-11'});
const sources = [
  source(1,'The NIST Cybersecurity Framework (CSF) 2.0','National Institute of Standards and Technology','https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'),
  source(2,'Security and Privacy Controls for Information Systems and Organizations','National Institute of Standards and Technology','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'),
  source(3,'Web Content Accessibility Guidelines (WCAG) 2.2','World Wide Web Consortium','https://www.w3.org/TR/WCAG22/'),
  source(4,'Federal Plain Language Guidelines','PlainLanguage.gov','https://www.plainlanguage.gov/guidelines/'),
  source(5,'Monitoring Distributed Systems','Google Site Reliability Engineering','https://sre.google/sre-book/monitoring-distributed-systems/'),
  source(6,'NIST Privacy Framework','National Institute of Standards and Technology','https://www.nist.gov/privacy-framework'),
];

type Study={slug:string;title:string;keyword:string;question:string;context:string;unit:string;method:string;caseStudy:string;interpretation:string;boundary:string;limitations:string;conclusion:string;sourceIds:number[]};
const studies:Study[] = [
  {slug:'virtual-assistant-review-sample-coverage-research-september-11-study',title:'September 11 study: Review sample coverage: finding the work a spot check misses',keyword:'virtual assistant review sample coverage research',question:'How can a manager tell whether a quality sample covers the work most likely to fail?',context:'A convenient sample can overrepresent ordinary completed work while excluding corrections, late items, exceptions, and records with missing evidence.',unit:'one eligible work item with its lane, risk class, completion state, exception state, reviewer selection probability, and review result',method:'Define the eligible population first, group items by lane and risk, select ordinary and exception cases with a recorded random seed, and compare sampled with unsampled distributions over four weeks.',caseStudy:'A weekly review selects five recently closed tickets. All pass, but the selection excludes reopened tickets and two cases that stopped for owner approval. The result describes clean closures, not the whole queue.',interpretation:'Coverage evidence can show that a sample omits meaningful classes of work. It cannot prove that unsampled work contains defects or that one sampling design fits every risk level.',boundary:'Assistants can preserve the sampling frame and evidence. Managers set risk groups, review consequential cases, and decide corrective action.',limitations:'No client or provider records were analyzed. Small groups, changing volume, hidden work, reviewer behavior, and disputed classifications limit comparison and prevent causal claims.',conclusion:'Publish the eligible population, selection rule, exclusions, and results by risk class before treating a spot check as evidence of queue quality.',sourceIds:[1,2,5]},
  {slug:'virtual-assistant-handoff-field-completeness-research-september-11-study',title:'September 11 study: Handoff field completeness: testing whether the next shift can act',keyword:'virtual assistant handoff field completeness research',question:'Which handoff fields let an authorized colleague continue recurring work without private context?',context:'A handoff may look complete because every box contains text, yet still omit the source, current state, decision owner, deadline, or permitted next action.',unit:'one handoff record paired with the source item, required-field definition, receiving role, attempted next action, clarification request, and outcome',method:'Predefine required fields by work lane, choose routine and exception records, ask an authorized backup to continue from the record alone, and log clarification without filling gaps from memory.',caseStudy:'A vendor note says “waiting for reply” but omits who was contacted, when, and what answer is needed. The next shift repeats the request and creates conflicting correspondence.',interpretation:'A successful continuation supports the usability of that record under the tested role and conditions. It does not prove the source was accurate or that every recipient has suitable access.',boundary:'Assistants maintain factual handoffs and flag missing fields. Process owners approve the required fields, authority limits, retention, and access.',limitations:'Backup familiarity, task complexity, permissions, urgency, and undocumented messages affect the test. A simulated continuation may not predict live performance.',conclusion:'Test handoffs by asking the intended receiver to take the next permitted action, then repair the specific fields that caused clarification or duplication.',sourceIds:[1,3,4]},
  {slug:'virtual-assistant-access-request-aging-research-september-11-study',title:'September 11 study: Access request aging: separating safe delay from forgotten ownership',keyword:'virtual assistant access request aging research',question:'How should a team examine access-request delay without treating faster approval as automatically safer?',context:'Access queues mix valid denials, incomplete requests, manager delay, security review, and forgotten ownership. A single average hides those different states.',unit:'one access request with business purpose, requested permission, requester, system owner, submitted time, evidence-ready time, decision time, decision, and expiry or review date',method:'Define request states before measurement, retain denied and withdrawn items, separate preparation time from owner-decision time, and review the oldest cases by system and permission risk.',caseStudy:'An assistant requests export access without a stated purpose. The request waits three days until the owner returns it. Calling the full interval approval delay hides the incomplete packet.',interpretation:'Age by state can expose routing or ownership gaps. A long review may also be a reasonable response to broad access, and a fast approval may indicate weak scrutiny.',boundary:'Assistants explain the task and request the least permission needed. System and security owners approve, deny, time-limit, and revoke access.',limitations:'The design does not evaluate the correctness of a permission decision. System risk, owner availability, emergencies, tooling, and missing timestamps prevent universal targets.',conclusion:'Measure access requests by state and risk, and inspect the underlying decision before setting a speed target.',sourceIds:[1,2,6]},
  {slug:'virtual-assistant-duplicate-action-prevention-research-september-11-study',title:'September 11 study: Duplicate action prevention in shared virtual assistant queues',keyword:'virtual assistant duplicate action prevention research',question:'What records help a shared queue prevent two people from taking the same external action?',context:'Parallel coverage can improve responsiveness, but weak claiming and stale status can produce duplicate emails, bookings, refunds, or updates.',unit:'one externally visible action with source item, claimed owner, claim time, action state, idempotency evidence, completion time, and any duplicate or near miss',method:'Map the action states, observe normal and handoff periods, compare system events with queue status, retain near misses, and independently review cases where two people opened the same item.',caseStudy:'Two assistants open an unclaimed scheduling request. One books the meeting while the other drafts a different time. A timely claim would have made the active owner visible.',interpretation:'A claim record and action identifier can reduce ambiguity, but the observation cannot isolate the effect of tooling from staffing, instruction, workload, or communication.',boundary:'Assistants follow claim and confirmation rules. Managers decide refunds, commitments, policy exceptions, and recovery after a duplicate action.',limitations:'Undetected duplicates remain invisible, and platform logs may not reflect drafts or off-channel work. Low counts and changing queues limit rate comparisons.',conclusion:'Use a visible claim, current state, and action identifier for externally visible work, then audit near misses as well as completed duplicates.',sourceIds:[1,2,5]},
  {slug:'virtual-assistant-backup-readiness-research-september-11-study',title:'September 11 study: Backup readiness: testing whether recurring work survives an absence',keyword:'virtual assistant backup readiness research',question:'How can a team test backup coverage without exposing live accounts or disrupting customers?',context:'A named backup is not evidence of readiness. The person may lack current instructions, source access, examples, or a clear boundary for exceptions.',unit:'one recurring task attempted by the designated backup with a safe record, current instruction, approved access role, completion evidence, clarification, and owner review',method:'Select representative routine and exception tasks, use redacted or test records, provide only documented context, observe the attempt, and classify each stop as instruction, access, source, skill, or authority related.',caseStudy:'A backup can open the queue but cannot find the current approved reply library. The test stops safely before any customer message and exposes a documentation gap.',interpretation:'Completion provides evidence for the tested task and conditions only. A safe stop can demonstrate good boundary behavior rather than poor readiness.',boundary:'Assistants document steps and stop rules. Managers approve backup access, customer-facing actions, consequential exceptions, and live activation.',limitations:'A test changes participant behavior and cannot reproduce every live condition. Familiarity, task selection, access timing, and reviewer judgment constrain generalization.',conclusion:'Test backups on safe representative work, score correct stopping as well as completion, and repair the named dependency before an actual absence.',sourceIds:[1,3,4,5]},
];

const pick=(ids:number[])=>ids.map(id=>sources.find(s=>s.id===id)!);
export const september11ResearchPosts:readonly ResearchPost[]=studies.map((s,index)=>{
  const refs=pick(s.sourceIds); const citations=s.sourceIds.map(id=>`[${id}]`).join('');
  return {slug:s.slug,featuredImage:'/featured/daily-research-brief-routine.png',primaryKeyword:s.keyword,title:s.title,metaTitle:s.title,excerpt:`A source-led research brief asking: ${s.question}`,published:'2026-09-11',updated:'2026-09-11',readingMinutes:12,revision:`2026-09-11-${index+1}-${s.slug}-v1`,
    takeaways:[s.conclusion,s.limitations,'Keep contradictory and missing cases visible.','Use findings to improve the workflow, not to make unsupported claims about a worker or provider.'],
    headlineStats:[{value:'1',label:'Defined unit',context:`The observation is ${s.unit}.`,sourceIds:[s.sourceIds[0]]},{value:String(refs.length),label:'Public sources',context:'Named guidance frames the controls and limits.',sourceIds:s.sourceIds},{value:'2+',label:'Case views',context:'Independent review can expose unstable definitions.',sourceIds:[s.sourceIds[1]]},{value:'0',label:'Guaranteed outcomes',context:'The sources do not guarantee staffing results.',sourceIds:[s.sourceIds[0]]},{value:'Named',label:'Decision owner',context:'Consequential exceptions stay with an authorized owner.',sourceIds:[s.sourceIds[0]]},{value:'2026-09-11',label:'Evidence review',context:'Linked guidance was reviewed September 11, 2026.',sourceIds:s.sourceIds}],
    sections:[{heading:`Research question: ${s.question}`,paragraphs:[s.context,`This report examines ${s.keyword} for managers of Philippines-based virtual assistant services. It applies public guidance to an operational observation design; it does not evaluate a provider, worker, client, or country.`,`The defined unit is ${s.unit}. Fixing the unit before collection keeps evidence attached to work rather than personality.`]},{heading:'Method and evidence scope',paragraphs:[s.method,`Publish definitions, scope, observation window, exclusions, and review rules before interpreting results. Retain missing records as missing.`,`The sources provide governance, privacy, usability, or monitoring principles; they do not provide a universal virtual-assistant benchmark.${citations} The operating design is our inference from those principles.`]},{heading:'Representative case',paragraphs:[s.caseStudy,'The case uses bounded or invented information and does not authorize live financial, legal, hiring, security, clinical, or customer decisions.']},{heading:'Interpretation and competing explanations',paragraphs:[s.interpretation,'Consider tool design, incomplete inputs, novelty, workload, time-zone overlap, owner availability, and changed instructions before choosing a cause.','Compare ordinary work, exceptions, apparent successes, and failures; a convenient aggregate can conceal correction or off-record decisions.']},{heading:'Role and privacy boundary',paragraphs:[s.boundary,`Collect only the evidence needed and keep sensitive detail in approved systems.[${s.sourceIds[0]}]`]},{heading:'Limitations',paragraphs:[s.limitations,'This qualitative brief is not a controlled study, market survey, legal opinion, privacy assessment, security audit, or provider evaluation.']},{heading:'Evidence-led conclusion',paragraphs:[s.conclusion,'Buyers should request a redacted work sample, written definition, reviewer decision, and correction trail before drawing conclusions.']}],
    evidenceTable:[{signal:'Defined observation',finding:s.unit,buyerUse:'Ask for a redacted example and decision trail.',limit:s.limitations,sourceIds:[s.sourceIds[0]]},{signal:'Independent review',finding:'A second reading can reveal ambiguous definitions.',buyerUse:'Calibrate the rule before expanding authority.',limit:'Agreement does not prove the underlying rule is correct.',sourceIds:[s.sourceIds[1]]},{signal:'Case context',finding:'Task, risk, inputs, tools, and owner availability affect results.',buyerUse:'Publish strata and exclusions.',limit:'A selected sample does not represent every future case.',sourceIds:s.sourceIds},{signal:'Owner boundary',finding:'Evidence supports a decision without transferring authority.',buyerUse:'Name the exception owner in advance.',limit:'Documentation does not replace qualified advice.',sourceIds:[s.sourceIds[0]]}],
    implications:[{title:'September 11 study: For buyers',body:'Ask how evidence is defined, reviewed, corrected, and linked to a business outcome.'},{title:'September 11 study: For managers',body:'Inspect cases that contradict the preferred explanation and keep missing data visible.'},{title:'September 11 study: For assistants',body:'Preserve source facts and uncertainty, then stop outside written authority.'},{title:'September 11 study: For providers',body:'Explain review, coaching, access, backup ownership, and exception handling.'}],
    methodology:[`Research question: ${s.question}`,`Evidence scope: ${refs.length} named public sources reviewed September 11, 2026.`,`Method: ${s.method}`,`Inference limits: public control guidance was translated into a proposed operating review; no causal or provider-performance conclusion is supported.`,`Limitations: ${s.limitations}`],
    faq:[{question:'Does this prove virtual assistant or provider quality?',answer:'No. Buyers still need direct work samples, references, and reviewed production evidence.'},{question:'Can one rate compare teams?',answer:'No. Definitions, work mix, risk, authority, volume, and missing data must accompany it.'},{question:'Who can change the operating rule?',answer:'An assistant may identify ambiguity; the authorized owner approves the change.'},{question:'What evidence should remain?',answer:'Keep the minimum source, observation, decision, outcome, period, and correction needed for review.'},{question:'When should this review repeat?',answer:'Repeat after material changes and at a cadence based on risk, volume, and observed defects.'}],sources:refs,related:[{title:'September 11 study: Research library',href:'/research',description:'Browse source-led virtual assistant operations reports.'},{title:'September 11 study: Services',href:'/services',description:'Review role areas and manager-owned decisions.'},{title:'September 11 study: Plan a role',href:'/contact',description:'Bring tasks, tools, examples, and decision limits.'}]};
});
