import type { ResearchPost, ResearchSource } from './fleet-content';
const src=(id:number,name:string,organization:string,url:string):ResearchSource=>({id,name,organization,url,accessed:'2026-08-23'});
const refs=[
src(1,'The NIST Cybersecurity Framework (CSF) 2.0','National Institute of Standards and Technology','https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'),
src(2,'Security and Privacy Controls for Information Systems and Organizations','National Institute of Standards and Technology','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'),
src(3,'Best Practices for Event Logging and Threat Detection','Cybersecurity and Infrastructure Security Agency','https://www.cisa.gov/resources-tools/resources/best-practices-event-logging-and-threat-detection'),
src(4,'More than a Password','Cybersecurity and Infrastructure Security Agency','https://www.cisa.gov/mfa'),
src(5,'Creating helpful, reliable, people-first content','Google Search Central','https://developers.google.com/search/docs/fundamentals/creating-helpful-content'),
src(6,'Federal plain language guidelines','PlainLanguage.gov','https://www.plainlanguage.gov/guidelines/'),
src(7,'Web Content Accessibility Guidelines (WCAG) 2.2','World Wide Web Consortium','https://www.w3.org/TR/WCAG22/'),
src(8,'Monitoring Distributed Systems','Google Site Reliability Engineering','https://sre.google/sre-book/monitoring-distributed-systems/'),
src(9,'NIST Privacy Framework','National Institute of Standards and Technology','https://www.nist.gov/privacy-framework')];
type D={slug:string;title:string;keyword:string;question:string;scope:string;unit:string;method:string;caseText:string;analysis:string;boundary:string;limits:string;conclusion:string;ids:number[]};
const ds:D[]=[
{slug:'virtual-assistant-work-resumption-state-study',title:'Interruption recovery in virtual assistant work: what handoff evidence reduces reconstruction?',keyword:'virtual assistant interruption recovery evidence',question:'Which observable records help a Philippines-based virtual assistant resume interrupted work, and what can those records prove about recovery quality?',scope:'Inbox, calendar, CRM, ecommerce, and support tasks cross shifts, connection failures, owner delays, and absences. Reopening an application is not recovery. The task must return to a verified business state.',unit:'one interrupted task, including its source, last verified state, next permitted action, exception, decision owner, and latest check',method:'Separate detection, reconstruction, and completion time. Compare interrupted tasks with similar uninterrupted tasks from the same lane for four weeks. Stratify by task type, risk, shift boundary, and need for an owner decision. Record correction and duplicate-action counts beside time.',caseText:'A calendar change pauses while an owner decides which attendee to move. The handoff records calendars checked, conflicts found, messages already sent, and the unanswered question. Recovery occurs after the decision, approved change, and a final check against the request.',analysis:'A two-minute restart that sends a duplicate reply is not success. A forty-minute restart can be correct when the assistant waits for an authorized exception. Repeated reconstruction questions may justify a shared queue or clearer status field. Approval delays may need a backup decision maker.',boundary:'The assistant maintains state and follows approved recovery steps. Money, legal, hiring, policy, and sensitive customer decisions stay with the manager. Suspected credential loss or disclosure enters the security response path.',limits:'No provider telemetry, client records, worker monitoring, or experimental interruptions were studied. Complexity, connectivity, tool design, manager availability, and sensitivity affect elapsed time.',conclusion:'Recovery is more reviewable when the record preserves last verified state, next safe action, exceptions, and decision ownership. Measure distinct intervals and pair time with correctness.',ids:[1,3,8]},
{slug:'virtual-assistant-brief-interpretation-divergence-study',title:'Instruction ambiguity in virtual assistant tasks: can clarification patterns expose weak briefs?',keyword:'virtual assistant instruction ambiguity research',question:'Can clarification patterns reveal ambiguity in virtual assistant instructions without treating every question as a worker defect?',scope:'Inbox triage, lead updates, publishing, booking, and ticket tagging depend on instructions another person can interpret. Questions may reflect a weak brief, unfamiliar tool, novel case, conflicting documents, or careful escalation.',unit:'one instruction-and-task pair, including exact wording, examples, clarification reason, interpretations, correction severity, and resulting edit',method:'Give the same safe task and brief to two reviewers independently. Each states the expected output, stop conditions, and owner-only decisions. Code missing input, undefined term, conflicting rule, missing example, unclear deadline, unknown owner, novel exception, or unresolved.',caseText:'The phrase handle urgent messages hides what urgent means, which action is allowed, who receives escalation, and when acknowledgment is due. A decision table with examples and counterexamples exposes the boundary better than vague prose.',analysis:'Agreement on a label can conceal different timing or authority assumptions, so compare reasons. A formatting change and an unauthorized refund are not equal. A question that stops risky action is positive control evidence. Falling question count matters only when accuracy remains stable.',boundary:'The assistant flags ambiguity and proposes wording. The owner decides policy, money, legal questions, hiring, customer remedies, and any expansion of authority. Silence is not automatic proof of mastery.',limits:'Workers differ in experience, communication style, and tool familiarity. Parallel tests simplify live pressure. WCAG concerns accessibility, not employee performance, and is used only as a design reference.',conclusion:'Clarification patterns expose weak briefs only when tied to exact wording and case context. Count reason, consequence, and edit, preserve unresolved cases, and reward safe questions.',ids:[5,6,7]},
{slug:'virtual-assistant-permission-provisioning-stage-study',title:'Access-request decision latency: when does waiting protect virtual assistant work?',keyword:'virtual assistant access request decision latency',question:'What does access-request latency show about a virtual assistant workflow, and when is waiting a legitimate control rather than a process defect?',scope:'A request for a named account, folder, queue, or role can wait because information is missing, a reviewer is unavailable, sensitive review takes time, or provisioning has stalled. One elapsed number hides those causes.',unit:'one complete access request with purpose, requested and granted role, data category, duration, owner, review, decision, provisioning, and verification times',method:'Group new accounts, changed roles, temporary elevation, emergency access, and removals. Within risk classes, report median and slow-tail time, returned requests, exact grants, corrections, and abandoned requests. Inspect fast and slow cases rather than rewarding speed.',caseText:'A read-only project-board seat is unlike billing administration or a customer export. A fast preapproved role can be sound, while another fast grant bypasses review. A slow sensitive request can be justified, while a low-risk request without an owner exposes weak governance.',analysis:'Provisioning is not readiness. Verify a named login, multi-factor authentication, intended access, and excluded access where a safe test exists. Temporary access needs expiry or review. Private-message approvals weaken timestamp evidence and count as missing data.',boundary:'The assistant explains the task and tests assigned permission. The system owner authorizes access. The worker cannot approve their own entitlement, borrow an account, or broaden a role because an approver is absent.',limits:'This is not a security audit or legal opinion. Tool capabilities, regulatory duties, staffing models, and volumes differ. Onboarding can dominate a short period, and missing requests bias reported speed.',conclusion:'Measure access latency as accountable stages, not a race. Identify least necessary access, owner, actual grant, and verification. Speed without authorization and caution without ownership are both weak states.',ids:[1,2,4,9]},
{slug:'virtual-assistant-support-guidance-validity-study',title:'Knowledge-base staleness sampling for virtual assistant support: what should owners verify?',keyword:'virtual assistant knowledge base staleness sampling',question:'How can a manager sample knowledge-base staleness in a virtual assistant support lane without assuming that document age equals inaccuracy?',scope:'Support, ecommerce, onboarding, and operations assistants reach guidance through search, bookmarks, saved replies, and links. An old page can be correct. A new page can contain an obsolete condition or unusable step.',unit:'one claim or user task compared with current owner-approved policy, interface, source version, intended audience, access path, and test date',method:'Draw a random coverage sample and a separate risk sample for payments, privacy, recovery, cancellation, regulated topics, and interface changes. Test factual claims and task usability separately. Include reasonable searches returning no approved result.',caseText:'Break a page into required fields, eligibility conditions, steps, contact routes, interface labels, and owner decisions. Mark each supported, contradicted, unverifiable, or outside scope. One obsolete condition may change an outcome even when the page mostly passes.',analysis:'Classify product drift, policy drift, broken evidence, terminology drift, audience mismatch, and missing ownership. Each needs a different repair. A changed timestamp is weak proof. The owner approves the corrected claim and the task is retested.',boundary:'The assistant inventories pages, finds conflicts, tests searches, and drafts changes. The policy owner selects the authoritative rule and approves customer language or legal and financial implications. During conflict, the assistant pauses or uses an approved holding response.',limits:'A sample cannot prove the whole library accurate. Search personalization, permissions, devices, language needs, and undocumented decisions affect what appears. The method tests alignment with approved policy, not the fairness or legality of that policy.',conclusion:'Claim-level task sampling is stronger than deletion by age. Combine random and labeled risk samples, test truth and usability separately, classify decay, approve corrections, and retest.',ids:[1,5,6,7]},
{slug:'virtual-assistant-exception-routing-agreement-study',title:'Escalation-threshold calibration: can virtual assistant case reviews reduce silent risk?',keyword:'virtual assistant escalation threshold calibration',question:'Can case-based calibration improve virtual assistant escalation decisions without encouraging unnecessary escalation or silent guessing?',scope:'Support, CRM, bookkeeping preparation, calendar, and ecommerce work contain exceptions. An escalation is a documented transfer to a decision owner, not merely a notification. Review asks if a case met the threshold and if the handoff supported a decision.',unit:'one representative case with written trigger, severity, uncertainty, safe action, destination, evidence, owner response, and disposition',method:'Build invented obvious escalations, clear non-escalations, and near-boundary cases. The assistant, manager, and another reviewer classify each independently and cite the rule. Revise the smallest unclear passage, then rerun with a new transfer case.',caseText:'Escalate difficult tickets is untestable. A bounded rule routes requests outside approved refund policy to the support owner, attaches an order identifier and summary, and prohibits promising an outcome. Boundary examples show where assistant authority ends.',analysis:'Disagreement reveals which condition reviewers prioritize. Live samples classify correct escalation, correct in-lane action, missed escalation, and unnecessary escalation, with consequence separate from count. Track acknowledgment, decision, and resolution because routing fails if nobody responds.',boundary:'The assistant identifies triggers, collects minimum facts, and uses the handoff. The owner retains exceptions, legal interpretation, financial commitments, hiring, sensitive remedies, and threshold changes. Personal data stays in approved systems.',limits:'Case sets simplify work and teach answers when reused. Reviewers may defer to senior colleagues. Rare severe events make percentages unstable, and audits miss cases never logged. Scope, tools, language, policy, and owner availability limit comparison.',conclusion:'Case calibration tests thresholds before authority expands. Compare independent reasons, retest edits, and attach consequence, case mix, and owner response time. A sound rule supports in-lane action and a clear stop.',ids:[1,6,8,9]}];
const get=(ids:number[])=>ids.map(id=>refs.find(s=>s.id===id)!);
function make(d:D,i:number):ResearchPost{const ss=get(d.ids);const cite=d.ids.map(x=>`[${x}]`).join('');const common=`This report examines ${d.keyword} for buyers and managers of Philippines-based virtual assistant services. Public guidance frames controls and evidence boundaries. It does not prove that a country, candidate, assistant, or provider has a particular quality. Facts attributed to sources carry citations. Proposed measures and management responses are analysis. No client, candidate, worker, or provider data was reviewed.`;return{
slug:d.slug,featuredImage:'/featured/publishing-contingency-routine.png',primaryKeyword:d.keyword,title:d.title,metaTitle:d.title,excerpt:`A source-led report asking: ${d.question}`,published:'2026-08-23',updated:'2026-08-23',readingMinutes:12,revision:`2026-08-23-${i+1}-${d.slug}-v1`,
takeaways:[d.conclusion,d.limits,'Use case-level evidence with a defined denominator and period.','Keep consequential decisions with a named manager.'],
headlineStats:[
{value:'1',label:'Defined unit',context:`The unit is ${d.unit}.`,sourceIds:[d.ids[0]]},
{value:String(ss.length),label:'Direct public sources',context:'Named authorities frame the evidence and limits.',sourceIds:d.ids},
{value:'2+',label:'Independent reviews',context:'Independent interpretation can expose unstable definitions.',sourceIds:[d.ids[1]]},
{value:'0',label:'Guaranteed outcomes',context:'The sources do not guarantee an assistant or provider result.',sourceIds:[d.ids[0]]},
{value:'Named',label:'Decision owner',context:'Exceptions require an authorized decision maker.',sourceIds:[d.ids[0]]},
{value:'2026-08-23',label:'Evidence reviewed',context:'The linked evidence was reviewed on August 23, 2026.',sourceIds:d.ids}],
sections:[
{heading:`Research question: ${d.question}`,paragraphs:[d.scope,common,`The unit is ${d.unit}. This keeps review attached to observable work rather than personality. Missing information remains missing or unresolved. Reviewers should never fill a gap with an assumption about a worker, provider, client, or country.`]},
{heading:'Method and comparison design',paragraphs:[d.method,`Publish definitions and the observation period before sampling. Keep the denominator beside each count or rate. Review failures and apparent successes because a fast output can conceal a wrong decision. A second reviewer should classify a redacted subset without seeing the first result. Resolve disagreement against the written rule, not seniority.`,`The public sources offer principles, not a staffing benchmark.${cite} Managers choose sample size and frequency from volume, consequence, recent change, and error history. A small sample identifies questions worth testing but cannot estimate every future case.`]},
{heading:'A representative operating case',paragraphs:[d.caseText,`The case tests whether the record supports the next permitted action and whether the assistant recognizes a stopping point. It does not test live credentials, contact a customer, submit a form, or authorize a consequential decision. Buyers can request a comparable exercise with invented or redacted data before expanding a role.`]},
{heading:'Interpretation and competing explanations',paragraphs:[d.analysis,`Preserve plausible alternatives. Process design, novelty, incomplete inputs, tool changes, workload, and owner availability can affect the observation. Evidence narrows explanations only when timestamps, source versions, task types, and decisions remain available. Clicks, messages, and hours are not substitutes for reviewed business outcomes.`,`Use results to decide what to inspect next. A pattern may justify clearer instructions, a safer role template, a better queue field, additional calibration, or a backup owner. It does not prove negligence, competence, causation, or provider quality. Direct work samples and reviewed production evidence remain necessary.`]},
{heading:'Role boundary and privacy',paragraphs:[d.boundary,`Collect the minimum evidence needed. Use task identifiers and keep sensitive detail inside approved systems. Named accounts, limited permissions, and an auditable owner decision support attribution without continuous surveillance.[${d.ids[0]}] Route legal, employment, financial, security, or regulated judgment to the authorized manager and a qualified adviser where appropriate.`]},
{heading:'Limitations',paragraphs:[d.limits,`This qualitative analysis applies guidance from adjacent fields to virtual assistant operations. It is not a controlled study, provider assessment, legal opinion, privacy determination, or security audit. Do not generalize one lane to another without new definitions and representative cases. Missing records are findings and must not be silently excluded.`]},
{heading:'Evidence-led conclusion',paragraphs:[d.conclusion,`The sources support governance, traceable information, usable instructions, and bounded action.${cite} This conclusion is narrower than a performance claim. Buyers should ask for a redacted example, written rule, reviewer decision, and correction path. Managers should preserve contradictory cases and repair the work system before judging the person.`]}],
evidenceTable:[
{signal:'Defined observation',finding:d.unit,buyerUse:'Ask for a redacted example and decision trail.',limit:d.limits,sourceIds:[d.ids[0]]},
{signal:'Independent review',finding:'A second interpretation can expose divergence.',buyerUse:'Test the rule before expanding work.',limit:'Agreement does not prove the policy correct.',sourceIds:[d.ids[1]]},
{signal:'Case context',finding:'Risk, task type, owner availability, and change affect results.',buyerUse:'Publish strata and denominators.',limit:'A selected sample is not universal.',sourceIds:d.ids.slice(0,3)},
{signal:'Owner boundary',finding:'Evidence supports a decision without transferring authority.',buyerUse:'Name the exception owner in advance.',limit:'Records do not replace qualified advice.',sourceIds:[d.ids[0]]}],
implications:[
{title:'For buyers',body:'Ask how evidence is captured, reviewed, corrected, and handed to an owner.'},
{title:'For managers',body:'Publish definitions and inspect cases that contradict the preferred explanation.'},
{title:'For assistants',body:'Preserve sources and uncertainty, then stop outside written authority.'},
{title:'For providers',body:'Explain review, coaching, access, backup ownership, and exceptions.'}],
methodology:[`Research question: ${d.question}`,`Evidence scope: ${ss.length} named public sources reviewed August 23, 2026.`,`Method: ${d.method}`,`Limitations: ${d.limits}`],
faq:[
{question:'Does this prove provider quality?',answer:'No. Buyers still need direct work samples, references, and reviewed records.'},
{question:'Can one rate compare assistants?',answer:'No. Task mix, risk, authority, change, and sample size must accompany it.'},
{question:'Can an assistant change the rule?',answer:'The assistant may propose an edit. The authorized owner approves it.'},
{question:'What data should remain?',answer:'Keep the minimum source, classification, decision, outcome, and timing.'},
{question:'When should review repeat?',answer:'After material changes and at a cadence based on risk and observed defects.'}],
sources:ss,related:[
{title:'Research library',href:'/research',description:'Browse source-led virtual assistant operations reports.'},
{title:'Services',href:'/services',description:'Review role areas and owner decisions.'},
{title:'Plan a role',href:'/contact',description:'Bring tasks, tools, examples, and decision limits.'}]};}
export const august23ResearchPosts:readonly ResearchPost[]=ds.map(make);
