import type { ResearchPost } from './fleet-content';
const studies=[
 ['virtual-assistant-request-intake-control-research','request intake controls','which intake fields preserve task intent and reveal missing authority','A request register connects an instruction to its requester and approval path.'],
 ['virtual-assistant-work-queue-risk-research','work queue risk','how ownership, aging, and priority evidence expose stalled assistant work','Queue age prompts review; it does not prove a worker caused the delay.'],
 ['virtual-assistant-document-retention-control-research','document retention controls','how assistants can organize records without unauthorized deletion decisions','A reversible archive proposal separates organization from records-policy judgment.'],
 ['virtual-assistant-approval-delay-evidence-research','approval delay evidence','what an approval log shows about waiting work and decision bottlenecks','Elapsed time does not establish that deliberation was unreasonable.'],
 ['virtual-assistant-operating-exception-trends-research','operating exception trends','how repeated exceptions reveal weak instructions, permissions, or task design','Exception counts need context because risk and workload differ by task lane.'],
] as const;
const sources=[{id:1,name:'The NIST Cybersecurity Framework (CSF) 2.0',organization:'National Institute of Standards and Technology',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20',published:'2024-02-26',accessed:'2026-09-01'},{id:2,name:'Cybersecurity Framework FAQs',organization:'National Institute of Standards and Technology',url:'https://www.nist.gov/cyberframework/faqs',accessed:'2026-09-01'},{id:3,name:'Creating helpful, reliable, people-first content',organization:'Google Search Central',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content',accessed:'2026-09-01'}] as const;
export const september1ResearchPosts: ResearchPost[]=studies.map(([slug,keyword,question,distinction])=>({
 slug,featuredImage:'/featured/publishing-contingency-routine.png',primaryKeyword:`virtual assistant ${keyword}`,title:`Research: ${keyword} in virtual assistant operations`,metaTitle:`Virtual assistant ${keyword} research`,excerpt:`A source-led examination of ${question}, including practical uses, evidence boundaries, and management limits.`,published:'2026-09-01',updated:'2026-09-01',readingMinutes:10,revision:`2026-09-01-${slug}-v1`,
 takeaways:[`Treat ${keyword} as management evidence, not a performance guarantee.`,distinction,'Connect every exception to a source and named decision owner.','Use minimum access and review after material process changes.'],
 headlineStats:[{value:'6',label:'CSF 2.0 functions',context:`Govern, Identify, Protect, Detect, Respond, and Recover provide a lifecycle for examining ${keyword}.`,sourceIds:[1,2]},{value:'1 owner',label:'Decision accountability',context:`A ${keyword} lane needs one named owner for approvals and exceptions.`,sourceIds:[1]},{value:'Named',label:'Account standard',context:'Individual accounts support attribution and permission review.',sourceIds:[1]},{value:'Risk-led',label:'Review frequency',context:`Review frequency for ${keyword} depends on impact, change, and error history.`,sourceIds:[1]},{value:'0',label:'Guaranteed outcomes',context:'Public frameworks provide guidance rather than a guarantee about any provider.',sourceIds:[1,2]},{value:'2026-09-01',label:'Evidence accessed',context:'The cited sources were checked on September 1, 2026.',sourceIds:[1,2,3]}],
 sections:[
  {heading:`Research question: ${question}`,paragraphs:[`This report examines ${keyword} for work assigned to a Philippines-based virtual assistant. It asks which compact record lets a manager reconstruct the source, action, exception, and owner decision.`,`NIST CSF 2.0 organizes outcomes around Govern, Identify, Protect, Detect, Respond, and Recover.[1][2] This analysis maps those voluntary outcomes to ${keyword}; it does not claim that the framework prescribes a virtual assistant workflow.`]},
  {heading:'What public guidance supports',paragraphs:[`Govern supports ownership, Protect supports limited permissions, Detect supports review, Respond supports escalation, and Recover supports correction.[1] Applied to ${keyword}, those outcomes favor visible sources, named workers, decision limits, and retained exceptions.`,`${distinction} Direct testing is still required to learn whether a provider follows the control consistently.`]},
  {heading:'A practical review routine',paragraphs:[`Begin with one ${keyword} lane, define expected evidence, and review every completion during calibration. Move to sampling only after accurate work and timely escalation.`,'Return to full review after a serious miss, system change, permission change, or material task change. Preserve the source and owner decision so corrections remain understandable.']},
  {heading:'People-first operating evidence',paragraphs:[`Google Search Central recommends considering who created material, how it was produced, and why.[3] Those questions improve ${keyword}: identify the worker and owner, explain review, and state the supported decision.`,'A form nobody uses is not a useful control. Keep evidence compact enough for the next person to act without reconstructing the task in a meeting.']},
  {heading:'Limitations',paragraphs:[`This is a qualitative application of public guidance to ${keyword}, not an audit, controlled study, legal opinion, security assessment, or provider measurement.`,'Fields, review rates, retention, and escalation timing depend on obligations, sensitivity, workload, impact, and observed error history.']},
  {heading:'Conclusion',paragraphs:[`The evidence supports a compact ${keyword} record with a source, named owner, limited access, completion proof, exception, and decision trail.[1][2] ${distinction}`]}],
 evidenceTable:[{signal:'Govern',finding:`CSF 2.0 elevates governance relevant to ${keyword}.`,buyerUse:'Name the owner and approval boundary.',limit:'The framework does not assign a staffing role.',sourceIds:[1,2]},{signal:'Protect',finding:'Protection includes safeguards for assets.',buyerUse:'Use named accounts and minimum access.',limit:'Restricted access cannot remove every error.',sourceIds:[1]},{signal:'Detect and respond',finding:'Detection and response are distinct.',buyerUse:'Review work and route exceptions.',limit:'Sampling can miss an error.',sourceIds:[1]},{signal:'Recover',finding:'Recovery continues the risk cycle.',buyerUse:'Correct records, instructions, and access.',limit:'Correction cannot reverse every consequence.',sourceIds:[1]}],
 implications:[{title:'For buyers',body:`Ask for a redacted ${keyword} record and resolved exception trail.`},{title:'For managers',body:'Choose review frequency from impact, change, and error history.'},{title:'For assistants',body:'Preserve sources, outputs, and questions while work is fresh.'},{title:'For providers',body:'Explain access, coaching, review, incident, and replacement ownership.'}],
 methodology:['We reviewed NIST CSF 2.0, its FAQ, and Google Search Central guidance on September 1, 2026.',`We mapped cited outcomes to ${keyword} and separated source statements from recommendations.`,'No client, candidate, worker, or provider data was analyzed.'],
 faq:[{question:`What belongs in a ${keyword} record?`,answer:'Include the source, expected output, worker, evidence, exception, and owner decision.'},{question:'Review every task?',answer:'Review every completion at launch. Later sampling reflects impact, change, and error history.'},{question:'Does this prove quality or security?',answer:'No. Direct evidence, observation, and testing remain necessary.'},{question:'What triggers full review?',answer:'A serious miss, repeated errors, workflow changes, or access changes.'},{question:'Can an assistant resolve exceptions?',answer:'Only exceptions within written authority; other decisions stay with the owner.'}],
 sources,related:[{title:'Daily risk flag routine',href:'/blog/virtual-assistant-daily-risk-flag-routine',description:'Build a daily record for issues needing an owner.'},{title:'Research library',href:'/research',description:'Browse other source-led reports.'},{title:'Plan a role',href:'/contact',description:'Bring tasks, tools, hours, and limits.'}],
}));
