import type { ResearchPost, ResearchSource } from './fleet-content';

const source = (id:number,name:string,organization:string,url:string):ResearchSource => ({id,name,organization,url,accessed:'2026-09-09'});
const sources = [
  source(1,'The NIST Cybersecurity Framework (CSF) 2.0','National Institute of Standards and Technology','https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'),
  source(2,'Security and Privacy Controls for Information Systems and Organizations','National Institute of Standards and Technology','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'),
  source(3,'Web Content Accessibility Guidelines (WCAG) 2.2','World Wide Web Consortium','https://www.w3.org/TR/WCAG22/'),
  source(4,'Federal Plain Language Guidelines','PlainLanguage.gov','https://www.plainlanguage.gov/guidelines/'),
  source(5,'Monitoring Distributed Systems','Google Site Reliability Engineering','https://sre.google/sre-book/monitoring-distributed-systems/'),
  source(6,'NIST Privacy Framework','National Institute of Standards and Technology','https://www.nist.gov/privacy-framework'),
];

type Study={slug:string;title:string;keyword:string;question:string;context:string;unit:string;method:string;caseStudy:string;interpretation:string;boundary:string;limitations:string;conclusion:string;sourceIds:number[]};
const studies:Study[] = [
  {slug:'virtual-assistant-queue-age-by-owner-research',title:'Queue age by owner: separating preparation delay from decision delay',keyword:'virtual assistant queue age by owner research',question:'How should a manager measure queue age when assistants and decision owners control different intervals?',context:'A single oldest-item number can hide whether work is waiting for source material, assistant preparation, customer response, or an authorized decision.',unit:'one queue item with entered, first-reviewed, evidence-ready, acknowledged, decided, and closed timestamps plus the owner at each state',method:'Define states before sampling, retain missing timestamps, stratify by lane and risk, and inspect the oldest and newest cases during a four-week observation window.',caseStudy:'A vendor record is prepared in 18 minutes, waits two days for procurement review, then closes in six minutes. Reporting a two-day assistant handling time assigns delay to the wrong control point.',interpretation:'Age by state can reveal an unclear owner, inadequate packet, or justified high-risk review. It does not by itself establish poor performance.',boundary:'Assistants record state and evidence; managers set priorities and decide commercial, legal, safety, and financial exceptions.',limitations:'No provider or client records were studied. Work mix, time zones, urgency, tooling, definitions, and missing events limit comparison and prevent causal claims.',conclusion:'Publish age by state and accountable owner, then review the underlying cases before changing staffing or targets.',sourceIds:[1,2,5]},
  {slug:'virtual-assistant-source-link-survival-research',title:'Source-link survival in recurring virtual assistant handoffs',keyword:'virtual assistant source link survival research',question:'Do handoff links still lead an authorized reviewer to the exact supporting record?',context:'A handoff can look complete while pointing to a moved file, a broad folder, an expired share, or a version that no longer supports the stated action.',unit:'one handoff claim paired with its link, access context, record identifier, version, observed destination, and reviewer result',method:'Select normal and exception cases, test links with an authorized reviewer account, compare the destination with the claim, and classify precise, stale, over-broad, inaccessible, or missing results.',caseStudy:'A month-end note links to a finance folder rather than the invoice used. The reviewer can open the folder but cannot reproduce the reconciliation without searching private context.',interpretation:'A reachable URL is weaker than a precise, authorized, version-correct source. Inaccessibility may also indicate a correct least-privilege boundary.',boundary:'Assistants repair labels and approved links; data owners decide sharing, retention, access expansion, and authoritative versions.',limitations:'Link checks do not prove source accuracy. Permission design, retention, account role, versioning, and platform behavior affect results; a small sample is diagnostic only.',conclusion:'Test whether each link reproduces the claim for the intended reviewer, while treating access boundaries and source accuracy as separate questions.',sourceIds:[1,2,6]},
  {slug:'virtual-assistant-instruction-drift-detection-research',title:'Instruction drift: detecting when the checklist and real workflow diverge',keyword:'virtual assistant instruction drift research',question:'How can a team identify recurring work that succeeds only through unwritten knowledge?',context:'Checklists age quietly when tools, fields, owners, or exception rules change. Experienced assistants may compensate, masking failure until backup coverage begins.',unit:'one representative task performed from the current approved instruction with inputs, user role, clarification, deviation, outcome, and owner review',method:'Choose common tasks and consequential exceptions, have an authorized backup follow the current instruction using safe examples, and compare each deviation with the owner-approved source.',caseStudy:'A booking checklist says to confirm by email, but the team now treats the scheduling platform as authoritative. A veteran knows this; a backup sends a duplicate confirmation.',interpretation:'Deviation may reflect obsolete guidance, unclear language, missing access, or unsafe habit. Successful completion alone cannot distinguish them.',boundary:'Assistants may expose drift and draft corrections. Process, legal, privacy, finance, and security owners approve authoritative changes.',limitations:'Observation and prior knowledge affect behavior. A task test does not represent all workers or prove that documentation caused an outcome.',conclusion:'Use backup task tests to expose unwritten dependencies, then resolve each deviation against a named authoritative owner.',sourceIds:[1,3,4,5]},
  {slug:'virtual-assistant-correction-recurrence-research',title:'Correction recurrence: when repeated fixes point to a system problem',keyword:'virtual assistant correction recurrence research',question:'What evidence distinguishes an isolated correction from a recurring process defect?',context:'Raw correction counts mix harmless formatting fixes with source conflicts, access failures, unclear instructions, and consequential misses.',unit:'one correction linked to the original task, expected rule, source, defect class, consequence, reviewer, repair, and later recurrence',method:'Define defect classes and eligibility first, independently review a redacted sample, retain disputed classifications, and examine recurrence by cause and workflow rather than person alone.',caseStudy:'Three assistants omit a new CRM consent field after the template changed but the instruction did not. Coaching individuals treats the symptom while the source mismatch remains.',interpretation:'Recurrence across people or shifts can point to instruction or tool design; recurrence within one context still has competing explanations that require case review.',boundary:'Assistants document corrections and propose clarity. Managers own performance decisions, policy, authority, and consequential remedies.',limitations:'Small counts are unstable, classifications can drift, and unrecorded corrections remain invisible. Observational recurrence cannot establish causation.',conclusion:'Attach corrections to their rules and causes, inspect counterexamples, and repair shared conditions before attributing the pattern to an individual.',sourceIds:[1,4,5,6]},
  {slug:'virtual-assistant-exception-acknowledgment-research',title:'Exception acknowledgment: measuring whether a safe stop reaches an owner',keyword:'virtual assistant exception acknowledgment research',question:'How can teams test whether a correctly raised exception reaches someone able to decide it?',context:'An escalation is not complete when a message is sent. It must reach an authorized owner with enough evidence, a visible deadline, and a safe waiting state.',unit:'one exception with trigger, evidence packet, sent time, destination, acknowledgment, decision authority, response, and permitted interim action',method:'Define acknowledgment separately from decision, sample varied risk levels, verify the recipient’s authority, audit missed triggers, and preserve unresolved and out-of-channel cases.',caseStudy:'An assistant flags a disputed refund in chat. A colleague reacts with an emoji, but no authorized owner accepts the case and the customer deadline expires.',interpretation:'Slow acknowledgment can indicate ownership gaps, routing failure, incomplete evidence, or deliberate review. A fast reaction does not prove an authorized decision path.',boundary:'Assistants follow written triggers and preserve a safe state. Authorized owners decide exceptions and define backup coverage.',limitations:'Messaging telemetry does not prove comprehension or authority. Risk, staffing, channel behavior, urgency, and policy changes limit comparisons.',conclusion:'Measure receipt by an authorized owner, not message delivery alone, and audit whether the exception remains safe until a decision.',sourceIds:[1,2,5]},
];

const pick=(ids:number[])=>ids.map(id=>sources.find(s=>s.id===id)!);
export const september9ResearchPosts:readonly ResearchPost[]=studies.map((s,index)=>{
  const refs=pick(s.sourceIds); const citations=s.sourceIds.map(id=>`[${id}]`).join('');
  return {slug:s.slug,featuredImage:'/featured/publishing-contingency-routine.png',primaryKeyword:s.keyword,title:s.title,metaTitle:s.title,excerpt:`A source-led research brief asking: ${s.question}`,published:'2026-09-09',updated:'2026-09-09',readingMinutes:12,revision:`2026-09-09-${index+1}-${s.slug}-v1`,
    takeaways:[s.conclusion,s.limitations,'Keep contradictory and missing cases visible.','Use findings to improve the workflow, not to make unsupported claims about a worker or provider.'],
    headlineStats:[{value:'1',label:'Defined unit',context:`The observation is ${s.unit}.`,sourceIds:[s.sourceIds[0]]},{value:String(refs.length),label:'Public sources',context:'Named guidance frames the controls and limits.',sourceIds:s.sourceIds},{value:'2+',label:'Case views',context:'Independent review can expose unstable definitions.',sourceIds:[s.sourceIds[1]]},{value:'0',label:'Guaranteed outcomes',context:'The sources do not guarantee staffing results.',sourceIds:[s.sourceIds[0]]},{value:'Named',label:'Decision owner',context:'Consequential exceptions stay with an authorized owner.',sourceIds:[s.sourceIds[0]]},{value:'2026-09-09',label:'Evidence review',context:'Linked guidance was reviewed September 9, 2026.',sourceIds:s.sourceIds}],
    sections:[{heading:`Research question: ${s.question}`,paragraphs:[s.context,`This report examines ${s.keyword} for managers of Philippines-based virtual assistant services. It applies public guidance to an operational observation design; it does not evaluate a provider, worker, client, or country.`,`The defined unit is ${s.unit}. Fixing the unit before collection keeps evidence attached to work rather than personality.`]},{heading:'Method and evidence scope',paragraphs:[s.method,`Publish definitions, scope, observation window, exclusions, and review rules before interpreting results. Retain missing records as missing.`,`The sources provide governance, privacy, usability, or monitoring principles; they do not provide a universal virtual-assistant benchmark.${citations} The operating design is our inference from those principles.`]},{heading:'Representative case',paragraphs:[s.caseStudy,'The case uses bounded or invented information and does not authorize live financial, legal, hiring, security, clinical, or customer decisions.']},{heading:'Interpretation and competing explanations',paragraphs:[s.interpretation,'Consider tool design, incomplete inputs, novelty, workload, time-zone overlap, owner availability, and changed instructions before choosing a cause.','Compare ordinary work, exceptions, apparent successes, and failures; a convenient aggregate can conceal correction or off-record decisions.']},{heading:'Role and privacy boundary',paragraphs:[s.boundary,`Collect only the evidence needed and keep sensitive detail in approved systems.[${s.sourceIds[0]}]`]},{heading:'Limitations',paragraphs:[s.limitations,'This qualitative brief is not a controlled study, market survey, legal opinion, privacy assessment, security audit, or provider evaluation.']},{heading:'Evidence-led conclusion',paragraphs:[s.conclusion,'Buyers should request a redacted work sample, written definition, reviewer decision, and correction trail before drawing conclusions.']}],
    evidenceTable:[{signal:'Defined observation',finding:s.unit,buyerUse:'Ask for a redacted example and decision trail.',limit:s.limitations,sourceIds:[s.sourceIds[0]]},{signal:'Independent review',finding:'A second reading can reveal ambiguous definitions.',buyerUse:'Calibrate the rule before expanding authority.',limit:'Agreement does not prove the underlying rule is correct.',sourceIds:[s.sourceIds[1]]},{signal:'Case context',finding:'Task, risk, inputs, tools, and owner availability affect results.',buyerUse:'Publish strata and exclusions.',limit:'A selected sample does not represent every future case.',sourceIds:s.sourceIds},{signal:'Owner boundary',finding:'Evidence supports a decision without transferring authority.',buyerUse:'Name the exception owner in advance.',limit:'Documentation does not replace qualified advice.',sourceIds:[s.sourceIds[0]]}],
    implications:[{title:'For buyers',body:'Ask how evidence is defined, reviewed, corrected, and linked to a business outcome.'},{title:'For managers',body:'Inspect cases that contradict the preferred explanation and keep missing data visible.'},{title:'For assistants',body:'Preserve source facts and uncertainty, then stop outside written authority.'},{title:'For providers',body:'Explain review, coaching, access, backup ownership, and exception handling.'}],
    methodology:[`Research question: ${s.question}`,`Evidence scope: ${refs.length} named public sources reviewed September 9, 2026.`,`Method: ${s.method}`,`Inference limits: public control guidance was translated into a proposed operating review; no causal or provider-performance conclusion is supported.`,`Limitations: ${s.limitations}`],
    faq:[{question:'Does this prove virtual assistant or provider quality?',answer:'No. Buyers still need direct work samples, references, and reviewed production evidence.'},{question:'Can one rate compare teams?',answer:'No. Definitions, work mix, risk, authority, volume, and missing data must accompany it.'},{question:'Who can change the operating rule?',answer:'An assistant may identify ambiguity; the authorized owner approves the change.'},{question:'What evidence should remain?',answer:'Keep the minimum source, observation, decision, outcome, period, and correction needed for review.'},{question:'When should this review repeat?',answer:'Repeat after material changes and at a cadence based on risk, volume, and observed defects.'}],sources:refs,related:[{title:'Research library',href:'/research',description:'Browse source-led virtual assistant operations reports.'},{title:'Services',href:'/services',description:'Review role areas and manager-owned decisions.'},{title:'Plan a role',href:'/contact',description:'Bring tasks, tools, examples, and decision limits.'}]};
});
