import type { BlogPost } from './data';

const topics = [
  ['virtual-assistant-morning-brief-routine', 'morning brief', 'calendar changes, urgent messages, and decisions due today'], ['virtual-assistant-end-of-day-handoff-routine', 'end-of-day handoff', 'finished work, open questions, and the next owner action'], ['virtual-assistant-inbox-sweep-routine', 'inbox sweep', 'priority messages, safe drafts, and owner-only messages'], ['virtual-assistant-calendar-check-routine', 'calendar check', 'conflicts, missing links, preparation notes, and travel time'], ['virtual-assistant-research-brief-routine', 'research brief', 'the question, source trail, findings, limits, and next decision'], ['virtual-assistant-content-publishing-routine', 'content publishing', 'approved copy, metadata, links, visual checks, and release evidence'], ['virtual-assistant-crm-follow-up-routine', 'CRM follow-up', 'stale records, approved messages, replies, and next actions'], ['virtual-assistant-customer-ticket-routine', 'customer ticket review', 'queue age, approved replies, risk flags, and escalations'], ['virtual-assistant-document-control-routine', 'document control', 'file names, versions, permissions, and review status'], ['virtual-assistant-data-quality-routine', 'data quality review', 'duplicates, missing fields, source conflicts, and correction evidence'], ['virtual-assistant-weekly-priority-reset', 'weekly priority reset', 'workload, deadlines, blocked items, and work to stop'], ['virtual-assistant-month-end-close-support-routine', 'month-end support', 'document collection, exception logs, reconciler notes, and owner sign-off'],
] as const;
const sources = [{ name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20', note: 'Use governance, access, detection, response, and recovery outcomes when routine work touches business systems.' }, { name: 'Google Search Central people-first content guidance', url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content', note: 'Publish material that answers a real reader need and explains who created it, how it was produced, and why.' }];
export const august31BlogPosts: BlogPost[] = topics.map(([slug, routine, evidence], index) => ({
  slug, featuredImage: '/featured/publishing-contingency-routine.png', title: `Virtual assistant ${routine} routine: a daily operating guide`, excerpt: `A practical way to run a ${routine} with clear evidence, decision limits, and a review path for a Philippines-based assistant.`, minutes: 9, published: '2026-08-31', updated: '2026-08-31', displayDate: 'August 31, 2026',
  takeaways: [`Define the ${routine} output before assigning the work.`, 'Keep decisions with the named owner and give the assistant written stop rules.', 'Record the source, completion evidence, exceptions, and reviewer in one place.', 'Change the routine when repeated misses show that the instructions are weak.'],
  sections: [
    { heading: `What the ${routine} should produce`, body: `A useful ${routine} ends with a small, checkable record: ${evidence}. The assistant should know where each input comes from, when the record is due, and who reads it. That is more useful than a vague instruction to keep things organized. Start with one example from real work, remove sensitive details if needed, and label the parts that make it complete.` },
    { heading: 'Write the decision boundary', body: 'List what the assistant may complete, what needs approval, and what must stop immediately. Routine does not mean risk-free. A strange payment request, customer threat, security warning, or source conflict belongs with the named owner. The assistant records the facts and routes the question instead of guessing.', bullets: ['Name the owner for exceptions.', 'Set the approved tools and accounts.', 'State the deadline for raising a blocker.', 'Keep money, legal judgment, and access expansion outside the routine.'] },
    { heading: 'Run the first five days', body: `On day one, the manager demonstrates the ${routine} with a completed example. The assistant performs it with review on days two and three. On day four, the assistant works independently but the manager checks every item. On day five, both people revise the instructions. This loop exposes missing inputs and unclear language before the work becomes habitual.` },
    { heading: 'Make proof part of the work', body: 'The completion note should point to the source and finished output. It should name skipped items and reasons. Screenshots help with visual checks, but a link or record ID is easier to search. Use named accounts so the activity trail belongs to the person who did the work. NIST Cybersecurity Framework 2.0 treats governance and access as ongoing outcomes, which fits this routine control.' },
    { heading: 'Review misses without adding clutter', body: 'When something goes wrong, ask whether the input, instruction, permission, or review timing caused the miss. Fix that part. Do not add a field unless someone will use it. A compact record that the manager reads is better than a long form that everyone ignores.' },
    { heading: 'Keep the routine useful to a person', body: `Google Search Central recommends material made for people rather than a process built only to fill pages. The same test works here. The ${routine} should help a manager decide or help the next worker continue without a meeting. If it does neither, shorten it or stop producing it.` },
  ],
  faq: [{ question: `Who should own the ${routine}?`, answer: 'The assistant can own preparation and routine execution. A named manager owns exceptions, access changes, and business decisions.' }, { question: 'How often should the manager review it?', answer: 'Review every item during the first week. Move to sampling only after the output is accurate and exceptions arrive on time.' }, { question: 'What evidence should be saved?', answer: 'Save the input source, output link or record ID, completion time, exceptions, and reviewer decision.' }],
  sources, relatedServices: [], articleLinks: [{ label: 'daily planning guide', href: '/blog/virtual-assistant-daily-planning-philippines' }, { label: index % 2 === 0 ? 'escalation rules guide' : 'reporting template guide', href: index % 2 === 0 ? '/blog/virtual-assistant-escalation-rules-philippines' : '/blog/virtual-assistant-reporting-template-philippines' }, { label: 'NIST Cybersecurity Framework 2.0', href: sources[0].url, external: true }],
}));
