import type { ResearchPost, ResearchSource } from './fleet-content';

type Topic = { slug: string; published: '2026-08-13'; keyword: string; title: string; excerpt: string; service: string; audience: string; question: string; finding: string; image: string; sources: ResearchSource[]; signals: string[] };
const S = {
  privacy: { id: 1, name: 'NIST Privacy Framework', organization: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', accessed: '2026-08-13' },
  access: { id: 2, name: 'Cybersecurity Performance Goals', organization: 'Cybersecurity and Infrastructure Security Agency', url: 'https://www.cisa.gov/cybersecurity-performance-goals', accessed: '2026-08-13' },
  wcag: { id: 3, name: 'Web Content Accessibility Guidelines', organization: 'W3C Web Accessibility Initiative', url: 'https://www.w3.org/TR/WCAG22/', accessed: '2026-08-13' },
  market: { id: 4, name: 'Market research and competitive analysis', organization: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis', accessed: '2026-08-13' },
  risk: { id: 5, name: 'Risk Management Framework', organization: 'National Institute of Standards and Technology', url: 'https://csrc.nist.gov/projects/risk-management', accessed: '2026-08-13' },
};
const topics: readonly Topic[] = [
  { slug: 'remote-team-onboarding-virtual-assistant-philippines', published: '2026-08-13', keyword: 'remote team onboarding virtual assistant Philippines', title: 'Remote-team onboarding with a Philippines-based virtual assistant: evidence for a bounded support role', excerpt: 'What privacy, accessibility, and security guidance can—and cannot—establish about delegating onboarding records and communications.', service: 'remote-team onboarding record preparation', audience: 'an operations owner', question: 'Which onboarding records can be prepared remotely while employment, access, and people decisions remain with accountable owners?', finding: 'Onboarding support is safer when required records, source documents, access requests, and unresolved exceptions remain visibly separate.', image: '/featured/virtual-assistant-reporting-template-philippines.png', sources: [S.privacy, S.wcag, S.access], signals: ['A complete checklist is not proof that a person is ready.', 'A response window is not a promise of instant availability.', 'An escalation rule gives ambiguity a safe destination.'] },
  { slug: 'event-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'event research virtual assistant Philippines', title: 'Event research in a Philippines-based support role: evidence and limits', excerpt: 'How to separate venue and agenda research from contracting authority, personal-data handling, and final event decisions.', service: 'event research and brief preparation', audience: 'an executive support buyer', question: 'What evidence supports delegating event research while the organizer keeps control of commitments and purchases?', finding: 'Event research is safer when sources, dates, capacities, accessibility details, and owner-only decisions are explicit.', image: '/featured/virtual-assistant-appointment-setting-philippines.png', sources: [S.privacy, S.access, S.wcag], signals: ['An event record contains personal and business context.', 'Date and location labels prevent avoidable coordination errors.', 'The owner remains accountable for sensitive commitments.'] },
  { slug: 'support-survey-analysis-virtual-assistant-philippines', published: '2026-08-13', keyword: 'support survey analysis virtual assistant Philippines', title: 'Support-survey analysis: evidence for a bounded Philippines-based support role', excerpt: 'How a support role can organize survey responses without treating a response rate or coded theme as a causal claim.', service: 'support-survey coding and analysis', audience: 'a customer-support owner', question: 'How can survey responses be organized for a decision owner without overstating what a selected sample proves?', finding: 'Survey analysis is more useful when the field period, response count, question wording, missing responses, and distinction between observation and interpretation are visible.', image: '/featured/customer-support-qa-workflow.png', sources: [S.privacy, S.wcag, S.access], signals: ['A theme needs a coding rule and review owner.', 'Customer data should not be copied into general notes.', 'Unusual requests need a human decision path.'] },
  { slug: 'sales-call-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'sales call research virtual assistant Philippines', title: 'Sales-call research in a Philippines-based support role: what the evidence permits', excerpt: 'How to prepare a source-based call brief while separating public observations from forecasting judgment and customer claims.', service: 'sales-call research and brief preparation', audience: 'a sales-operations owner', question: 'Which call-preparation tasks can be delegated while pipeline meaning and customer commitments remain accountable?', finding: 'Call research is defensible when the research question, observation date, source records, unknowns, and exception paths are visible to the reviewer.', image: '/featured/sales-support-crm-hygiene.png', sources: [S.privacy, S.market, S.access], signals: ['A public fact is not proof of buyer intent.', 'Duplicate findings need an accountable reviewer.', 'Customer-facing claims require source records and approval.'] },
  { slug: 'marketplace-taxonomy-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'marketplace taxonomy research virtual assistant Philippines', title: 'Marketplace taxonomy research: evidence for a Philippines-based catalog role', excerpt: 'A research-backed boundary between studying category structures and making unsupported claims about product fit, safety, availability, or commercial terms.', service: 'marketplace taxonomy research', audience: 'an ecommerce operator', question: 'What evidence supports delegating category research without delegating product claims or commercial decisions?', finding: 'Taxonomy research is strongest when each proposed category has a source, a definition, a reviewer, and a visible distinction between observation and recommendation.', image: '/featured/ecommerce-virtual-assistant-philippines.png', sources: [S.privacy, S.wcag, S.access], signals: ['Category labels need a source of truth.', 'Descriptions should explain a category rather than invent benefits.', 'Commercial changes need owner-approved rules.'] },
  { slug: 'expense-receipt-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'expense receipt research virtual assistant Philippines', title: 'Expense-receipt research: evidence for a bounded Philippines-based role', excerpt: 'How to organize receipt evidence while keeping accounting judgment, approvals, tax decisions, and money movement with qualified owners.', service: 'expense-receipt research and document preparation', audience: 'a small-business owner', question: 'Which receipt-preparation tasks can be supported without confusing organized evidence with accounting judgment?', finding: 'Receipt preparation is safer when original sources, transaction dates, coding questions, approval status, and unresolved exceptions remain separate.', image: '/featured/bookkeeping-virtual-assistant-philippines.png', sources: [S.risk, S.privacy, S.access], signals: ['A complete packet is not a reconciled account.', 'Uncertain coding belongs in an exception queue.', 'Bank and payment permissions should be narrowly assigned.'] },
  { slug: 'property-market-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'property market research virtual assistant Philippines', title: 'Property-market research: evidence for a careful Philippines-based support role', excerpt: 'A bounded research view of market-source checks, record accuracy, privacy, and decisions that should stay with a licensed or accountable professional.', service: 'property-market research and comparison', audience: 'a real-estate team owner', question: 'How can support organize market research while leaving property, legal, and client commitments with the responsible professional?', finding: 'Market research should preserve each source, define the comparison period, distinguish observed details from interpretation, and route legal or property questions instead of guessing.', image: '/featured/real-estate-assistant-lead-follow-up.png', sources: [S.privacy, S.access, S.market], signals: ['A source log preserves the market question.', 'Observed data is narrower than professional judgment.', 'Privacy and fair-treatment duties need local review.'] },
  { slug: 'medical-record-request-coordination-virtual-assistant-philippines', published: '2026-08-13', keyword: 'medical record request coordination virtual assistant Philippines', title: 'Medical-record request coordination: evidence for a bounded Philippines-based role', excerpt: 'What privacy and risk principles imply for administrative records requests, minimum necessary access, patient communication, and escalation of clinical questions.', service: 'medical-record request coordination', audience: 'a healthcare practice owner', question: 'Which records-request tasks can be delegated without allowing administrative support to become clinical advice?', finding: 'Records-request support should handle approved logistics with minimum necessary access and route symptoms, treatment, identity, and urgent concerns to qualified staff.', image: '/featured/virtual-assistant-patient-scheduling-philippines.png', sources: [S.privacy, S.access, S.risk], signals: ['A records request still deserves privacy controls.', 'An administrative script cannot answer a clinical question.', 'Identity or urgent language needs a named escalation path.'] },
  { slug: 'board-packet-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'board packet research virtual assistant Philippines', title: 'Board-packet research: evidence for a safer Philippines-based support role', excerpt: 'A practical evidence boundary for source gathering, version tracking, access, and escalation when an assistant supports executive or board materials.', service: 'board-packet research and document preparation', audience: 'an executive or founder', question: 'How can board-material research reduce administrative load while preserving confidentiality and decision ownership?', finding: 'Board-packet research is safer when source citations, version labels, confidential handling, and owner-only decisions are defined before circulation.', image: '/featured/executive-assistant-calendar-delegation.png', sources: [S.privacy, S.access, S.wcag], signals: ['Triage is different from making a commitment.', 'Delegated access is safer than a shared password.', 'Confidential documents need an explicit route.'] },
  { slug: 'industry-regulation-research-virtual-assistant-philippines', published: '2026-08-13', keyword: 'industry regulation research virtual assistant Philippines', title: 'Industry-regulation research: evidence for a decision-ready Philippines-based support role', excerpt: 'How a research-support role can make public regulatory findings easier to check while leaving interpretation, compliance, and business decisions with the client.', service: 'industry-regulation research and brief preparation', audience: 'a founder or strategy owner', question: 'What separates useful regulation research from a collection of untested links?', finding: 'A decision-ready regulatory record states the jurisdiction, effective date, source authority, question, and exact inference the evidence permits.', image: '/featured/virtual-assistant-market-research-brief-philippines.png', sources: [S.market, S.privacy, S.wcag], signals: ['A source must match the jurisdiction and question.', 'A finding needs an effective date and definition.', 'Interpretation is distinct from observed text.'] },
];

const makePost = (t: Topic): ResearchPost => {
  const ids = t.sources.map((s) => s.id);
  const paragraphs = [
    `This report examines ${t.service} for ${t.audience}. The question is narrow: ${t.question} The answer cannot come from a national statistic or a provider description. It requires a defined task, a safe sample, a named owner, and a record of what happened when the task became ambiguous.`,
    `${t.finding} That conclusion is a boundary, not a promise. The cited authorities describe privacy, security, accessibility, risk, or research principles; they do not measure a particular Philippines-based assistant, customer, practice, property, inbox, catalog, or account.`,
    'The useful unit of review is one work item. Identify its input, expected output, source of truth, permitted action, stop condition, and reviewer. Then ask whether another person could inspect the record later and understand what changed, why it changed, and what remained unresolved.',
    `${t.signals[0]} Put that requirement in the task brief and test it in a small sample using invented or redacted information. A fluent answer is not enough if the work cannot be traced back to its source.`,
    `${t.signals[1]} Separate a response target from an outcome guarantee. A calendar response can be timely without creating a good meeting; a CRM update can be complete without proving sales fit; a prepared document can be orderly without being an approved record.`,
    `${t.signals[2]} Escalation is not failure when the rule does not cover the case. It keeps a support role from silently making a legal, clinical, financial, commercial, or confidential decision.`,
    'A practical role brief lists recurring work, permitted fields or messages, systems, exception owner, review frequency, and offboarding action. Write an acceptable output and a stop-worthy output. This reduces disagreement during the first week because quality is described before it is scored.',
    'Access should follow the task rather than the title. Use named accounts, multi-factor authentication, minimum necessary permissions, and a documented recovery owner. Do not provide a shared administrator login for convenience. Remove unused access when the work changes, and confirm that exported files and notes have an owner when the assignment ends.',
    'The first test should resemble the real work but contain no live customer secrets, payment credentials, medical details, confidential negotiations, or irreversible actions. Score completeness, accuracy, source traceability, tone, question quality, and escalation. One exercise cannot prove long-term performance; use it to decide what to supervise next.',
    'For a Philippines-based arrangement, clarify hours, overlap, outage communication, equipment, holidays, data handling, and the person responsible for review. Country context can help plan the conversation, but it cannot establish an individual’s connection quality, schedule, education, language judgment, or fit. Ask for evidence at the role level.',
    'Review the first live set at a cadence matching the risk. A formatting queue may need sampling; a customer, healthcare, finance, or executive workflow may require approval before release. Ask: was the source right, was the field complete, was the boundary respected, and did the record make the next decision easier?',
    'The main limitation is transfer. Guidance about privacy or risk does not predict worker accuracy, and a clean sample does not establish future reliability. Results depend on source data, software, instructions, workload, and review capacity. Treat this as role-design guidance that must be tested in the actual setting.',
  ];
  return {
    slug: t.slug, featuredImage: t.image, primaryKeyword: t.keyword, title: t.title, metaTitle: t.title, excerpt: t.excerpt,
    published: t.published, updated: t.published, readingMinutes: 10, revision: `${t.published}-${t.slug}-v1`,
    takeaways: [t.finding, ...t.signals, 'Use role-level evidence and bounded access; do not turn general guidance into a guarantee.'],
    headlineStats: [
      { value: '1', label: 'Decision question', context: t.question, sourceIds: ids },
      { value: '3', label: 'Evidence boundaries', context: 'Source scope, task proof, and owner accountability must stay distinct.', sourceIds: ids },
      { value: '1', label: 'Named owner', context: 'Every exception needs an accountable person who can resolve it.', sourceIds: ids },
      { value: '0', label: 'Unsupported promises', context: 'The sources support boundaries and questions, not guaranteed results.', sourceIds: ids },
      { value: '1', label: 'Safe first lane', context: `Begin with a bounded ${t.service} assignment and review the evidence before widening scope.`, sourceIds: ids },
      { value: '6', label: 'Review dimensions', context: 'Score accuracy, completeness, traceability, tone, questions, and escalation.', sourceIds: ids },
    ],
    sections: [
      { heading: 'What the evidence can answer', paragraphs: paragraphs.slice(0, 3) },
      { heading: 'Define the work at record level', paragraphs: paragraphs.slice(3, 6) },
      { heading: 'Design a safe first test', paragraphs: paragraphs.slice(6, 9) },
      { heading: 'Set access and communication boundaries', paragraphs: paragraphs.slice(9, 11) },
      { heading: 'Interpret results without overclaiming', paragraphs: paragraphs.slice(11) },
    ],
    evidenceTable: t.signals.map((finding, i) => ({ signal: ['Scope', 'Observable record', 'Escalation'][i], finding, buyerUse: 'Put this requirement in the role brief and sample scorecard.', limit: 'It does not prove a candidate, provider, or future outcome.', sourceIds: ids })),
    implications: [
      { title: 'Define the lane', body: `List the recurring ${t.service} tasks, inputs, outputs, tools, reviewer, and stop conditions.` },
      { title: 'Protect the record', body: 'Use named accounts, minimum access, source links, and an exception note for every material uncertainty.' },
      { title: 'Test with safe data', body: 'Use invented or redacted records before opening live credentials or allowing an irreversible action.' },
      { title: 'Review the first work', body: 'Inspect a small first set for accuracy, completeness, traceability, communication, and escalation judgment.' },
    ],
    methodology: [`This report uses the authoritative sources listed below, accessed on August 13, 2026. Sources were selected for direct relevance to ${t.service}, privacy, security, accessibility, risk, or research method.`, 'The recommendations are practical guidance from Virtual Assistant Provider. The cited authorities support principles and boundaries, not a measured performance result or guarantee about any person, provider, customer, or business.', 'The article excludes individual hiring claims and does not substitute for qualified legal, clinical, accounting, privacy, employment, or property advice where those duties apply.'],
    faq: [
      { question: `Can support own the final ${t.service} decision?`, answer: 'Only when the responsible owner has explicitly assigned it and the role is qualified. Otherwise, support prepares the record and escalates.' },
      { question: 'What should a buyer test first?', answer: 'Use a short sample with safe data and score accuracy, completeness, traceability, communication, and escalation judgment.' },
      { question: 'Does a source prove a provider is suitable?', answer: 'No. It supplies relevant evidence and boundaries; suitability requires role-specific proof and review.' },
      { question: 'What belongs in the role brief?', answer: 'Tasks, inputs, outputs, access, owner-only decisions, exception paths, review timing, and offboarding.' },
    ],
    sources: t.sources,
    related: [
      { title: 'Research library', href: '/research', description: 'Read the other source-led reports for Philippines-based support decisions.' },
      { title: 'Services', href: '/services', description: 'Review the support areas covered by Virtual Assistant Provider.' },
      { title: 'Plan a Philippines-based role', href: '/contact', description: 'Bring the recurring work, tools, review rules, and owner decisions for a role plan.' },
    ],
  };
};
export const august13ResearchPosts: readonly ResearchPost[] = topics.map(makePost);
