import type { ResearchPost, ResearchSource } from './fleet-content';

type Topic = { slug: string; keyword: string; title: string; excerpt: string; service: string; audience: string; question: string; finding: string; image: string; sources: ResearchSource[]; signals: string[] };
const S = {
  privacy: { id: 1, name: 'NIST Privacy Framework', organization: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', accessed: '2026-08-13' },
  access: { id: 2, name: 'Cybersecurity Performance Goals', organization: 'Cybersecurity and Infrastructure Security Agency', url: 'https://www.cisa.gov/cybersecurity-performance-goals', accessed: '2026-08-13' },
  wcag: { id: 3, name: 'Web Content Accessibility Guidelines', organization: 'W3C Web Accessibility Initiative', url: 'https://www.w3.org/TR/WCAG22/', accessed: '2026-08-13' },
  market: { id: 4, name: 'Market research and competitive analysis', organization: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis', accessed: '2026-08-13' },
  risk: { id: 5, name: 'Risk Management Framework', organization: 'National Institute of Standards and Technology', url: 'https://csrc.nist.gov/projects/risk-management', accessed: '2026-08-13' },
};
const topics: readonly Topic[] = [
  { slug: 'async-communication-virtual-assistant-philippines', keyword: 'async communication virtual assistant Philippines', title: 'Async communication with a Philippines-based virtual assistant: evidence for a dependable handoff', excerpt: 'What research on privacy, accessibility, and operational risk suggests about written handoffs, response windows, and owner decisions across time zones.', service: 'async communication', audience: 'an operations owner', question: 'Which communication practices make remote support dependable without requiring constant meetings?', finding: 'Written context, explicit response windows, and a named escalation owner make remote coordination easier to inspect and improve.', image: '/featured/virtual-assistant-reporting-template-philippines.png', sources: [S.privacy, S.wcag, S.access], signals: ['A written handoff preserves context.', 'A response window is not a promise of instant availability.', 'An escalation rule gives ambiguity a safe destination.'] },
  { slug: 'calendar-coordination-virtual-assistant-philippines', keyword: 'calendar coordination virtual assistant Philippines', title: 'Calendar coordination in a Philippines-based support role: evidence and limits', excerpt: 'How to define calendar assistance around time zones, meeting purpose, privacy, and owner approval instead of treating scheduling as simple data entry.', service: 'calendar coordination', audience: 'an executive support buyer', question: 'What evidence supports delegating calendar administration while the owner keeps control of commitments?', finding: 'Calendar support is safest when meeting purpose, attendees, time zones, buffers, and owner-only decisions are explicit.', image: '/featured/virtual-assistant-appointment-setting-philippines.png', sources: [S.privacy, S.access, S.wcag], signals: ['A calendar record contains personal and business context.', 'Time-zone labels prevent avoidable scheduling errors.', 'The owner remains accountable for sensitive commitments.'] },
  { slug: 'customer-support-knowledge-base-virtual-assistant-philippines', keyword: 'customer support knowledge base virtual assistant Philippines', title: 'Customer-support knowledge bases: evidence for a safer Philippines-based support role', excerpt: 'How a support assistant can keep answers consistent while managers retain responsibility for exceptions, privacy, and customer promises.', service: 'customer-support knowledge-base maintenance', audience: 'a customer-support owner', question: 'How can a support role use shared answers without turning old guidance into an automatic promise?', finding: 'Knowledge-base support works when each answer has an owner, scope, review signal, and route for questions outside the rule.', image: '/featured/customer-support-qa-workflow.png', sources: [S.privacy, S.wcag, S.access], signals: ['An answer needs scope and a review owner.', 'Customer data should not be copied into general notes.', 'Unusual requests need a human decision path.'] },
  { slug: 'crm-data-quality-virtual-assistant-philippines', keyword: 'CRM data quality virtual assistant Philippines', title: 'CRM data quality in a Philippines-based support role: what the evidence permits', excerpt: 'How to separate record cleanup from sales judgment, define fields precisely, and test a CRM assistant with safe data and observable checks.', service: 'CRM data quality', audience: 'a sales-operations owner', question: 'Which CRM tasks can be delegated while pipeline meaning and customer commitments remain accountable?', finding: 'CRM support is defensible when field definitions, source records, duplicate rules, and escalation paths are visible to the reviewer.', image: '/featured/sales-support-crm-hygiene.png', sources: [S.privacy, S.market, S.access], signals: ['A clean field is not proof of a qualified lead.', 'Duplicate rules need an accountable owner.', 'Customer-facing claims require source records and approval.'] },
  { slug: 'ecommerce-catalog-accuracy-virtual-assistant-philippines', keyword: 'ecommerce catalog accuracy virtual assistant Philippines', title: 'Ecommerce catalog accuracy: evidence for a Philippines-based product-record role', excerpt: 'A research-backed boundary between maintaining product records and making claims about products, availability, safety, or commercial terms.', service: 'ecommerce catalog maintenance', audience: 'an ecommerce operator', question: 'What evidence supports delegating product-record maintenance without delegating product claims or commercial decisions?', finding: 'Catalog support is strongest when every changed field has a source, a reviewer, and a visible distinction between product fact and marketing claim.', image: '/featured/ecommerce-virtual-assistant-philippines.png', sources: [S.privacy, S.wcag, S.access], signals: ['Variant fields need a source of truth.', 'Accessibility descriptions should describe the product rather than invent benefits.', 'Price and availability changes need owner-approved rules.'] },
  { slug: 'bookkeeping-document-preparation-virtual-assistant-philippines', keyword: 'bookkeeping document preparation virtual assistant Philippines', title: 'Bookkeeping document preparation: evidence for a bounded Philippines-based role', excerpt: 'How to delegate document collection and preparation while keeping accounting judgment, approvals, tax decisions, and money movement with qualified owners.', service: 'bookkeeping document preparation', audience: 'a small-business owner', question: 'Which bookkeeping preparation tasks can be supported without confusing organized records with accounting judgment?', finding: 'Preparation is safer when source documents, coding questions, approval status, and unresolved exceptions remain separate.', image: '/featured/bookkeeping-virtual-assistant-philippines.png', sources: [S.risk, S.privacy, S.access], signals: ['A complete packet is not a reconciled account.', 'Uncertain coding belongs in an exception queue.', 'Bank and payment permissions should be narrowly assigned.'] },
  { slug: 'real-estate-lead-response-virtual-assistant-philippines', keyword: 'real estate lead response virtual assistant Philippines', title: 'Real-estate lead response: evidence for a careful Philippines-based support role', excerpt: 'A bounded research view of response preparation, record accuracy, privacy, and decisions that should stay with a licensed or accountable professional.', service: 'real-estate lead response', audience: 'a real-estate team owner', question: 'How can support improve lead follow-up while leaving property, legal, and client commitments with the responsible professional?', finding: 'Lead-response support should preserve the inquiry, use approved language, and route property-specific or legal questions instead of guessing.', image: '/featured/real-estate-assistant-lead-follow-up.png', sources: [S.privacy, S.access, S.market], signals: ['A response log preserves the customer question.', 'Approved language is narrower than sales judgment.', 'Privacy and fair-treatment duties need local review.'] },
  { slug: 'healthcare-appointment-scheduling-virtual-assistant-philippines', keyword: 'healthcare appointment scheduling virtual assistant Philippines', title: 'Healthcare appointment scheduling: evidence for a bounded Philippines-based role', excerpt: 'What privacy and risk principles imply for scheduling support, minimum necessary access, patient communication, and escalation of clinical questions.', service: 'healthcare appointment scheduling', audience: 'a healthcare practice owner', question: 'Which scheduling tasks can be delegated without allowing administrative support to become clinical advice?', finding: 'Scheduling support should handle approved logistics with minimum necessary access and route symptoms, treatment, and urgent concerns to qualified staff.', image: '/featured/virtual-assistant-patient-scheduling-philippines.png', sources: [S.privacy, S.access, S.risk], signals: ['Appointment data still deserves privacy controls.', 'A scheduling script cannot answer a clinical question.', 'Urgent language needs a named escalation path.'] },
  { slug: 'executive-inbox-delegation-virtual-assistant-philippines', keyword: 'executive inbox delegation virtual assistant Philippines', title: 'Executive inbox delegation: evidence for a safer Philippines-based support role', excerpt: 'A practical evidence boundary for triage, drafting, access, and escalation when an assistant supports a busy executive inbox.', service: 'executive inbox delegation', audience: 'an executive or founder', question: 'How can inbox support reduce administrative load while preserving confidentiality and decision ownership?', finding: 'Inbox delegation is safer when categories, delegated access, draft approval, confidential labels, and owner-only decisions are defined before launch.', image: '/featured/executive-assistant-calendar-delegation.png', sources: [S.privacy, S.access, S.wcag], signals: ['Triage is different from making a commitment.', 'Delegated access is safer than a shared password.', 'Confidential messages need an explicit route.'] },
  { slug: 'market-research-brief-virtual-assistant-philippines', keyword: 'market research brief virtual assistant Philippines', title: 'Market-research briefs: evidence for a decision-ready Philippines-based support role', excerpt: 'How a research-support assistant can make findings easier to check while leaving interpretation, strategy, and business decisions with the client.', service: 'market-research brief preparation', audience: 'a founder or strategy owner', question: 'What separates a useful market-research brief from a collection of untested links?', finding: 'A decision-ready brief states the question, population, method, date, source limits, and exact inference the evidence permits.', image: '/featured/virtual-assistant-market-research-brief-philippines.png', sources: [S.market, S.privacy, S.wcag], signals: ['A source must match the claim and population.', 'A finding needs a date and definition.', 'Recommendation is distinct from observed evidence.'] },
];

const makePost = (t: Topic): ResearchPost => {
  const ids = t.sources.map((s) => s.id);
  const paragraphs = [
    `This report examines ${t.service} for ${t.audience}. The question is narrow: ${t.question} The answer cannot come from a national statistic or a provider description. It requires a defined task, a safe sample, a named owner, and a record of what happened when the task became ambiguous.`,
    `${t.finding} That conclusion is a boundary, not a promise. The cited authorities describe privacy, security, accessibility, risk, or research principles; they do not measure a particular Philippines-based assistant, customer, practice, property, inbox, catalog, or account.`,
    'The useful unit of review is one work item. Identify its input, expected output, source of truth, permitted action, stop condition, and reviewer. Then ask whether another person could inspect the record later and understand what changed, why it changed, and what remained unresolved.',
    `${t.signals[0]} Put that requirement in the task brief and test it in a small sample using invented or redacted information. A fluent answer is not enough if the work cannot be traced back to its source.`,
    `${t.signals[1]} Separate a response target from an outcome guarantee. A calendar response can be timely without creating a good meeting; a CRM update can be complete without proving sales fit; a prepared document can be orderly without being an approved record.`,
    `${t.signals[2]} Escalation is not failure when the rule does not cover the case. It keeps a support role from silently making a legal, clinical, financial, commercial, or confidential decision.`,
    'A practical role brief lists recurring work, permitted fields or messages, systems, exception owner, review frequency, and offboarding action. Write an acceptable output and a stop-worthy output. This reduces disagreement during the first week because quality is described before it is scored.',
    'Access should follow the task rather than the title. Use named accounts, multi-factor authentication, minimum necessary permissions, and a documented recovery owner. Do not provide a shared administrator login for convenience. Remove unused access when the work changes, and confirm that exported files and notes have an owner when the assignment ends.',
    'The first test should resemble the real work but contain no live customer secrets, payment credentials, medical details, confidential negotiations, or irreversible actions. Score completeness, accuracy, source traceability, tone, question quality, and escalation. One exercise cannot prove long-term performance; use it to decide what to supervise next.',
    'For a Philippines-based arrangement, clarify hours, overlap, outage communication, equipment, holidays, data handling, and the person responsible for review. Country context can help plan the conversation, but it cannot establish an individual’s connection quality, schedule, education, language judgment, or fit. Ask for evidence at the role level.',
    'Review the first live set at a cadence matching the risk. A formatting queue may need sampling; a customer, healthcare, finance, or executive workflow may require approval before release. Ask: was the source right, was the field complete, was the boundary respected, and did the record make the next decision easier?',
    'The main limitation is transfer. Guidance about privacy or risk does not predict worker accuracy, and a clean sample does not establish future reliability. Results depend on source data, software, instructions, workload, and review capacity. Treat this as role-design guidance that must be tested in the actual setting.',
  ];
  return {
    slug: t.slug, featuredImage: t.image, primaryKeyword: t.keyword, title: t.title, metaTitle: t.title, excerpt: t.excerpt,
    published: '2026-08-13', updated: '2026-08-13', readingMinutes: 10, revision: `2026-08-13-${t.slug}-v1`,
    takeaways: [t.finding, ...t.signals, 'Use role-level evidence and bounded access; do not turn general guidance into a guarantee.'],
    headlineStats: [
      { value: '1', label: 'Decision question', context: t.question, sourceIds: ids },
      { value: '3', label: 'Evidence boundaries', context: 'Source scope, task proof, and owner accountability must stay distinct.', sourceIds: ids },
      { value: '1', label: 'Named owner', context: 'Every exception needs an accountable person who can resolve it.', sourceIds: ids },
      { value: '0', label: 'Unsupported promises', context: 'The sources support boundaries and questions, not guaranteed results.', sourceIds: ids },
      { value: '1', label: 'Safe first lane', context: `Begin with a bounded ${t.service} assignment and review the evidence before widening scope.`, sourceIds: ids },
      { value: '6', label: 'Review dimensions', context: 'Score accuracy, completeness, traceability, tone, questions, and escalation.', sourceIds: ids },
    ],
    sections: [
      { heading: 'What the evidence can answer', paragraphs: paragraphs.slice(0, 3) },
      { heading: 'Define the work at record level', paragraphs: paragraphs.slice(3, 6) },
      { heading: 'Design a safe first test', paragraphs: paragraphs.slice(6, 9) },
      { heading: 'Set access and communication boundaries', paragraphs: paragraphs.slice(9, 11) },
      { heading: 'Interpret results without overclaiming', paragraphs: paragraphs.slice(11) },
    ],
    evidenceTable: t.signals.map((finding, i) => ({ signal: ['Scope', 'Observable record', 'Escalation'][i], finding, buyerUse: 'Put this requirement in the role brief and sample scorecard.', limit: 'It does not prove a candidate, provider, or future outcome.', sourceIds: ids })),
    implications: [
      { title: 'Define the lane', body: `List the recurring ${t.service} tasks, inputs, outputs, tools, reviewer, and stop conditions.` },
      { title: 'Protect the record', body: 'Use named accounts, minimum access, source links, and an exception note for every material uncertainty.' },
      { title: 'Test with safe data', body: 'Use invented or redacted records before opening live credentials or allowing an irreversible action.' },
      { title: 'Review the first work', body: 'Inspect a small first set for accuracy, completeness, traceability, communication, and escalation judgment.' },
    ],
    methodology: [`This report uses the authoritative sources listed below, accessed on August 13, 2026. Sources were selected for direct relevance to ${t.service}, privacy, security, accessibility, risk, or research method.`, 'The recommendations are practical guidance from Virtual Assistant Provider. The cited authorities support principles and boundaries, not a measured performance result or guarantee about any person, provider, customer, or business.', 'The article excludes individual hiring claims and does not substitute for qualified legal, clinical, accounting, privacy, employment, or property advice where those duties apply.'],
    faq: [
      { question: `Can support own the final ${t.service} decision?`, answer: 'Only when the responsible owner has explicitly assigned it and the role is qualified. Otherwise, support prepares the record and escalates.' },
      { question: 'What should a buyer test first?', answer: 'Use a short sample with safe data and score accuracy, completeness, traceability, communication, and escalation judgment.' },
      { question: 'Does a source prove a provider is suitable?', answer: 'No. It supplies relevant evidence and boundaries; suitability requires role-specific proof and review.' },
      { question: 'What belongs in the role brief?', answer: 'Tasks, inputs, outputs, access, owner-only decisions, exception paths, review timing, and offboarding.' },
    ],
    sources: t.sources,
    related: [
      { title: 'Research library', href: '/research', description: 'Read the other source-led reports for Philippines-based support decisions.' },
      { title: 'Services', href: '/services', description: 'Review the support areas covered by Virtual Assistant Provider.' },
      { title: 'Plan a Philippines-based role', href: '/contact', description: 'Bring the recurring work, tools, review rules, and owner decisions for a role plan.' },
    ],
  };
};
export const august13ResearchPosts: readonly ResearchPost[] = topics.map(makePost);
