import type { BlogPost } from './data';

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20', note: 'Use named governance, protection, response, and recovery ownership.' },
  { name: 'CISA More than a Password', url: 'https://www.cisa.gov/mfa', note: 'Protect work accounts with multi-factor authentication.' },
  { name: 'Federal Plain Language Guidelines', url: 'https://www.plainlanguage.gov/guidelines/', note: 'Write operational records so the next reader can act without decoding them.' },
];

const topics = [
  ['virtual-assistant-dental-lab-case-status-board-september-11-review', 'September 11 review: A dental lab case-status board that keeps patient promises with clinicians','dental lab case-status board', 'September 11 review: address, inspection date, room or area, original photo link, visible condition, missing view, and reviewer','label what the image visibly shows without diagnosing a defect or estimating repair cost','Route safety concerns, tenant disputes, repair decisions, and legal notices to the property manager.'],
  ['virtual-assistant-construction-submittal-receipt-log-september-11-review', 'September 11 review: Log construction submittal receipts without approving technical content','construction submittal receipt log', 'September 11 review: document owner, controlled identifier, approved repository link, effective date, expiry date, renewal state, and study contact','copy dates from the controlled record and flag conflicts instead of choosing one','Clinical, regulatory, ethics, and participant-safety judgments remain with qualified study staff.'],
  ['virtual-assistant-veterinary-referral-record-chase-september-11-review', 'September 11 review: Chase veterinary referral records without giving care advice','veterinary referral record chase', 'September 11 review: event, guest wording, menu item, kitchen response status, approved reply, deadline, and escalation owner','preserve the guest’s exact question and distinguish an inquiry from a confirmed accommodation','The chef or authorized safety owner confirms ingredients, cross-contact controls, and any promise to a guest.'],
  ['virtual-assistant-museum-loan-document-checklist-september-11-review', 'September 11 review: Run a museum loan document checklist without accepting custody terms','museum loan document checklist', 'September 11 review: vehicle, service event, requested record, source workshop, received date, discrepancy, and fleet reviewer','match invoices and inspection records to the correct vehicle and service date','Only the fleet or safety owner can determine roadworthiness, approve repairs, or return a vehicle to service.'],
  ['virtual-assistant-home-care-visit-note-routing-september-11-review', 'September 11 review: Route home-care visit notes without interpreting clinical information','home-care visit note routing', 'September 11 review: RFI number, drawing reference, question, sender, design owner, due date, response state, and issued version','record the issued response verbatim and retain superseded status without deleting history','Architects and designated consultants own design interpretation, instruction, and professional sign-off.'],
  ['virtual-assistant-freight-claim-evidence-folder-september-11-review', 'September 11 review: Assemble a freight claim evidence folder without admitting liability','freight claim evidence folder', 'September 11 review: product identifier, supplier notice, order quantity, expected date, affected request, and pharmacist owner','separate supplier statements from local inventory records and mark uncertain dates','A pharmacist or authorized clinical owner decides substitution, patient communication, and dispensing action.'],
  ['virtual-assistant-franchise-renewal-obligation-calendar-september-11-review', 'September 11 review: Maintain a franchise renewal calendar without interpreting the agreement','franchise renewal obligation calendar', 'September 11 review: campaign, approved copy, placement, episode URL, publication time, screenshot, correction, and account owner','capture delivery evidence against the signed brief, not memory or a draft','The commercial owner handles claims, make-goods, pricing, contract interpretation, and performance representations.'],
  ['virtual-assistant-film-release-form-register-september-11-review', 'September 11 review: Build a film release form register without deciding rights clearance','film release form register', 'September 11 review: grant requirement, reporting period, source record, program owner, verification state, gap, and approval','keep reported figures tied to their source period and definition','Program and finance owners approve outcomes, allocations, certifications, and explanations to the funder.'],
  ['virtual-assistant-laboratory-sample-intake-audit-september-11-review', 'September 11 review: Audit laboratory sample intake fields without validating results','laboratory sample intake audit', 'September 11 review: reservation reference, guest-supplied name, stay dates, room request, confirmation state, and exception owner','compare the latest approved list with hotel confirmations one field at a time','The event owner decides upgrades, concessions, cancellations, payment changes, and disputed commitments.'],
  ['virtual-assistant-community-association-mail-log-september-11-review', 'September 11 review: Track association notices without making enforcement decisions','calibration certificate index', 'September 11 review: asset identifier, certificate number, laboratory, calibration date, due date, scope, exception, and quality owner','link the original certificate and flag missing identifiers or inconsistent dates','Quality or engineering owners determine fitness for use, tolerances, quarantine, and release.'],
  ['virtual-assistant-wholesale-food-specification-register-september-11-review', 'September 11 review: Maintain a wholesale food specification register without approving safety claims','wholesale food specification register', 'September 11 review: work, territory, recipient, approved material, sent date, response, follow-up rule, and agent owner','record interest and requested materials in the recipient’s own terms','The author or rights agent chooses submissions and decides representation, licensing, exclusivity, and commercial terms.'],
  ['virtual-assistant-university-participant-schedule-september-11-review', 'September 11 review: Coordinate a university research participant schedule without influencing consent','university research participant schedule', 'September 11 review: project, jurisdiction, application identifier, portal status, last official notice, requested item, deadline, and permit owner','quote official status text and link the notice rather than translating it into a guarantee','Licensed, legal, engineering, and permitting owners interpret requirements and authorize responses.'],
] as const;

export const september11BlogPosts: BlogPost[] = topics.map(([slug,title,lane,finish,check,boundary], index) => ({
  slug, title, featuredImage: '/featured/operations-assistant-daily-workflow.png', minutes: 9,
  excerpt: `A practical ${lane} routine for a Philippines-based virtual assistant, with source checks and a clear owner boundary.`,
  published: '2026-09-11', updated: '2026-09-11', displayDate: 'September 11, 2026',
  takeaways: [`Define the finished record as ${finish}.`, check, boundary, 'Leave the next shift a linked source, current state, exception, and named owner.'],
  sections: [
    { heading: 'Name the record before opening the queue', body: `A reliable ${lane} starts with one source of truth and a narrow finish line. For Virtual Assistant Provider, the completed record contains ${finish}. That definition keeps daily work reviewable instead of turning “updated” into an uncheckable status.` },
    { heading: 'Work from evidence, not memory', body: `Open the approved source, confirm the identifier, record the current state, and preserve the link another authorized person can inspect. ${check}.`, bullets: ['Distinguish requested, received, checked, and approved.', 'September 11 review: Keep conflicting facts visible.', 'Do not move sensitive details into an informal digest.'] },
    { heading: 'Keep authority where it belongs', body: boundary },
    { heading: 'Check the first five records', body: `Review five varied ${lane} examples against their sources. Classify corrections as a missing input, unclear rule, access gap, execution error, or owner delay. Revise the instruction when the same ambiguity returns.` },
    { heading: 'Protect access and recovery', body: 'Use named accounts, multi-factor authentication, and the smallest permission set that supports the task. NIST and CISA guidance provide a useful control frame, but the client’s system owner still approves access and recovery.' },
    { heading: 'Close with an actionable handoff', body: `List completed records, unresolved conflicts, deadlines, and the next permitted action. ${boundary} A good handoff lets the next person continue without private context or duplicated action.` },
  ],
  faq: [
    { question: `What can an assistant own in a ${lane}?`, answer: `They can maintain the factual record, run documented checks, and route exceptions. ${boundary}` },
    { question: 'What proof should remain?', answer: 'Keep the source link, identifier, previous state, action, check result, timestamp, exception, and reviewer decision.' },
    { question: 'When should the manager review every item?', answer: 'Review every item during launch, after a serious miss, and whenever the source, instruction, or permissions change.' },
  ],
  sources, relatedServices: [],
  articleLinks: [{label:'daily planning guide',href:'/blog/virtual-assistant-daily-planning-philippines'},{label:index % 2 ? 'handoff guide':'escalation rules guide',href:index % 2 ? '/blog/virtual-assistant-handoff-philippines':'/blog/virtual-assistant-escalation-rules-philippines'},{label:'NIST Cybersecurity Framework 2.0',href:sources[0].url,external:true}],
}));
