import type { ResearchPost, ResearchSource } from './fleet-content';

type ReplacementTopic = {
  slug: string;
  published: '2026-08-13';
  keyword: string;
  title: string;
  excerpt: string;
  service: string;
  question: string;
  finding: string;
  angle: string;
  details: readonly string[];
  source: ResearchSource;
  image: string;
};

const sources = {
  privacy: { id: 1, name: 'NIST Privacy Framework', organization: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', accessed: '2026-08-13' },
  cisa: { id: 2, name: 'Cybersecurity Performance Goals', organization: 'Cybersecurity and Infrastructure Security Agency', url: 'https://www.cisa.gov/cybersecurity-performance-goals', accessed: '2026-08-13' },
  access: { id: 3, name: 'Web Content Accessibility Guidelines', organization: 'W3C Web Accessibility Initiative', url: 'https://www.w3.org/TR/WCAG22/', accessed: '2026-08-13' },
  sba: { id: 4, name: 'Market research and competitive analysis', organization: 'U.S. Small Business Administration', url: 'https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis', accessed: '2026-08-13' },
  risk: { id: 5, name: 'Risk Management Framework', organization: 'National Institute of Standards and Technology', url: 'https://csrc.nist.gov/projects/risk-management', accessed: '2026-08-13' },
} as const;

const topics: readonly ReplacementTopic[] = [
  { slug: 'executive-calendar-conflict-research-philippines', published: '2026-08-13', keyword: 'executive calendar conflict research virtual assistant Philippines', title: 'Executive-calendar conflict research: evidence for a bounded Philippines-based support role', excerpt: 'How to study incoming customer messages without confusing urgency signals with a promise, diagnosis, or final response.', service: 'executive calendar conflict research', question: 'Which observable message features can support triage while the customer owner keeps responsibility for sensitive decisions?', finding: 'A defensible triage record preserves the original message, evidence for its category, time context, and the owner who resolves exceptions.', angle: 'message triage', details: ['Urgency is not a property that can be inferred from punctuation alone; it depends on the customer’s stated impact, the promised service, and the current record.', 'A useful sample labels the message channel, received timestamp, stated need, affected account or order, and any safety or privacy language before assigning a queue.', 'A category should be reproducible: two reviewers should be able to explain which phrase or linked record led to it and where the category stops applying.', 'The first test should use redacted conversations that include normal requests, duplicates, missing identifiers, angry language, and requests for exceptions.', 'Response speed is a process measure, not evidence that the answer was correct. Review answer accuracy and escalation alongside elapsed time.', 'Keep private details in the approved system. A research note should contain only the fields needed to support the queue decision.', 'Customer sentiment can inform review priority but cannot establish motive, fraud, legal entitlement, or a service remedy.', 'For a Philippines-based support role, agree on overlap hours, handoff format, language questions, and the owner for urgent or ambiguous messages.'], source: sources.privacy, image: '/featured/customer-service-virtual-assistant-philippines.png' },
  { slug: 'customer-onboarding-evidence-research-philippines', published: '2026-08-13', keyword: 'customer onboarding evidence research virtual assistant Philippines', title: 'customer onboarding evidence research: what a Philippines-based support role can establish', excerpt: 'A source-led examination of duplicate records, field definitions, and observable evidence in sales administration.', service: 'customer onboarding evidence research', question: 'How can support improve CRM reliability without turning an observed field into a forecast or customer claim?', finding: 'CRM research is strongest when each material field has a source, an observation date, a confidence boundary, and an accountable owner.', angle: 'CRM provenance', details: ['A contact name, company relationship, stage, and next action are different claims and should not inherit one another’s evidence.', 'Duplicate detection needs matching rules that are visible to the reviewer: email, domain, account identifier, spelling variants, and collision exceptions.', 'A blank field and an unknown field have different meanings. Preserve unknowns rather than filling them with a plausible guess.', 'Record the source channel and access date for every material update; a later reviewer must be able to tell whether the fact came from a customer message, public page, or internal note.', 'Pipeline stage is an organizational label, not proof of buyer intent. Forecasts and commitments remain owner decisions.', 'Use a safe sample that includes merges, shared domains, changed job titles, and conflicting records. Measure false matches as well as missed matches.', 'Access should be limited to the fields required for the assignment, with named accounts and a removal check when the role changes.', 'A useful handoff lists changed records, unresolved collisions, source links, and questions that require sales judgment.'], source: sources.cisa, image: '/featured/sales-support-crm-hygiene.png' },
  { slug: 'ecommerce-product-catalog-research-philippines', published: '2026-08-13', keyword: 'ecommerce product catalog research virtual assistant Philippines', title: 'Ecommerce product-catalog research: measure what the knowledge base does not answer', excerpt: 'How to analyze recurring questions and documentation coverage without overstating a small support sample.', service: 'support-documentation gap research', question: 'What can a support-question sample show about missing documentation, and what can it not prove?', finding: 'A gap study should define its field period, question sample, coding rule, and missingness before proposing an update.', angle: 'documentation gaps', details: ['Start with a bounded period and channel set. A week of email cannot describe every question received through chat, phone, or a self-service page.', 'Preserve the wording of the question before coding it into a topic. Rewritten summaries can erase the ambiguity the document needs to address.', 'Distinguish no article, hard-to-find article, outdated article, and article that requires an owner-only decision.', 'A frequency count describes the selected sample. It does not prove that the most common question creates the greatest customer harm.', 'Test the coding rule on a second reviewer and record disagreements. Agreement is useful evidence that the categories are understandable, not proof that the categories are true.', 'A proposed article should name its source owner, review date, audience, and exception path. Documentation is not complete when it only handles the easy case.', 'Privacy requires removing names, account identifiers, and unnecessary message content from an analysis extract.', 'The conclusion should state the sample boundaries and recommend the next check rather than claiming the entire support system has been measured.'], source: sources.sba, image: '/featured/customer-support-qa-workflow.png' },
  { slug: 'meeting-decision-log-research-philippines', published: '2026-08-13', keyword: 'meeting decision log virtual assistant Philippines', title: 'Meeting-decision log: what competitor evidence can reveal', excerpt: 'A careful method for comparing public help channels without inferring hidden staffing, quality, or customer outcomes.', service: 'public support-channel comparison research', question: 'Which public observations can inform a support brief while keeping unobserved operations and commercial conclusions separate?', finding: 'Public comparison is useful when the observation date, channel definition, sample, and inference limit are recorded for every finding.', angle: 'support-channel comparison', details: ['Define the comparison unit before collecting pages: contact route, response promise, help-center coverage, accessibility feature, or escalation instruction.', 'A public contact page shows what a visitor can see. It cannot establish internal staffing, actual response time, resolution quality, or customer satisfaction.', 'Capture the exact page, jurisdiction, observed date, and whether the route requires an account. Public information changes and should not be treated as timeless.', 'Compare like with like. A self-service article, a ticket form, and a phone number serve different purposes and should not be ranked by one score.', 'Use a small, declared sample of pages and repeat the check later if the decision depends on change over time.', 'Accessibility observations should describe the tested feature and limitation rather than certify conformance from a quick visual pass.', 'Do not copy private or gated content into a shared report. Public availability does not remove copyright, privacy, or context limits.', 'The resulting brief should support questions for an owner; it should not make claims about a competitor’s workforce or promise a response advantage.'], source: sources.access, image: '/featured/virtual-assistant-market-research-brief-philippines.png' },
  { slug: 'local-business-lead-source-research-philippines', published: '2026-08-13', keyword: 'local business lead source research virtual assistant Philippines', title: 'Local-business lead-source research: a bounded Philippines-based support role', excerpt: 'How to organize itinerary evidence while leaving bookings, identity, safety, and changing travel decisions with the traveler or owner.', service: 'travel-planning evidence research', question: 'What itinerary facts can be researched remotely without turning an administrative brief into travel, legal, or safety advice?', finding: 'A travel brief should separate observed schedule and policy details from assumptions, personal preferences, and decisions that need current confirmation.', angle: 'travel planning', details: ['Record the route, local date, time zone, source, and access time for each itinerary item. A date without a location can produce a dangerous ambiguity.', 'Availability and fare information are time-sensitive observations, not reservations. The owner must confirm the current terms before committing.', 'Accessibility, visa, health, border, and safety questions need official sources and an appropriate qualified decision maker; a support role should not improvise an answer.', 'Keep passport numbers, payment details, loyalty identifiers, and unnecessary traveler data out of general research notes.', 'A useful comparison states the criteria used, such as transfer count, arrival window, cancellation rule, or accessibility detail, rather than presenting a single unexplained recommendation.', 'Test the research task with an invented itinerary and include a changed schedule, a missing source, and a conflicting time zone.', 'A Philippines-based support arrangement should define the owner’s working hours, urgent-change channel, and who can authorize a booking or cancellation.', 'The limitation is rapid change: a well-sourced brief can become stale before the traveler acts, so rechecking is part of the handoff.'], source: sources.privacy, image: '/featured/virtual-assistant-appointment-setting-philippines.png' },
  { slug: 'nonprofit-program-research-philippines', published: '2026-08-13', keyword: 'nonprofit program research virtual assistant Philippines', title: 'Nonprofit-program research: organize compliance records without certifying a supplier', excerpt: 'A source-based boundary for collecting vendor documents, tracking expiry, and routing unresolved compliance questions.', service: 'vendor-document evidence research', question: 'How can administrative support organize supplier evidence without making a legal, security, or procurement certification?', finding: 'A vendor record becomes reviewable when document identity, issuing authority, validity period, source, and unresolved question are kept distinct.', angle: 'vendor evidence', details: ['List the required document types and the owner of each requirement before requesting files. A pile of attachments is not a compliance conclusion.', 'Record issuer, document number where appropriate, effective and expiry dates, received channel, and verification status.', 'A document can be authentic and still fail the organization’s requirement. Keep authenticity, completeness, suitability, and approval as separate states.', 'Do not treat a vendor’s assertion as evidence for a security control or legal obligation. Route specialized questions to the qualified reviewer.', 'Use least-privilege storage and avoid copying sensitive tax, banking, identity, or security material into chat or personal devices.', 'Test with fictional documents and include expired, unreadable, mismatched, and translated records. The expected result should be an exception, not a guess.', 'Track follow-up ownership and next check date. Silence does not mean a missing document was accepted.', 'Country context can inform language and time-zone planning but cannot establish a supplier’s compliance or the quality of its controls.'], source: sources.risk, image: '/featured/virtual-assistant-document-management-philippines.png' },
  { slug: 'healthcare-appointment-information-research-philippines', published: '2026-08-13', keyword: 'healthcare appointment information research virtual assistant Philippines', title: 'Healthcare-appointment information research: source boundaries for a Philippines-based support role', excerpt: 'How to prepare a guest brief from public evidence without inventing credentials, intent, or sensitive personal facts.', service: 'podcast-guest background research', question: 'What public evidence belongs in a guest brief, and where must the researcher stop?', finding: 'A responsible guest brief identifies the source, date, identity match, relevance, and uncertainty for each proposed talking point.', angle: 'guest background research', details: ['Begin with the episode question and audience. A biography is not useful merely because it is long; each fact should explain why it matters to the conversation.', 'Match identity carefully across official bios, publications, event pages, and professional profiles. Similar names are an unresolved check, not evidence.', 'Separate a person’s stated role from an interpretation of expertise or influence. Do not turn a title into a claim about results.', 'Use publication dates and original sources where possible. A copied profile can repeat an error without adding independent support.', 'Exclude sensitive personal information, speculation, family details, political assumptions, and allegations that do not belong to the interview purpose.', 'Mark facts needing guest confirmation, especially current roles, affiliations, spellings, pronunciation, and disclosed conflicts.', 'A safe sample can test identity matching, citation quality, neutral tone, and handling of a missing or contradictory source.', 'The host remains responsible for questions, framing, consent, and any public claim made during or after the episode.'], source: sources.sba, image: '/featured/executive-assistant-calendar-delegation.png' },
  { slug: 'property-maintenance-request-research-philippines', published: '2026-08-13', keyword: 'property maintenance request research virtual assistant Philippines', title: 'Property-maintenance request research: evidence for a bounded support role', excerpt: 'What a structured accessibility observation can document, and why it cannot substitute for a full conformance evaluation.', service: 'property maintenance request research', question: 'How can support collect useful accessibility observations without claiming a complete audit?', finding: 'An observation report is credible when it names the page, user path, test method, result, limitation, and qualified owner for remediation.', angle: 'accessibility observation', details: ['Define the user journey and pages tested before opening a tool. A scan of one homepage is not a test of a checkout, form, keyboard path, or document.', 'Record browser, device or assistive technology, date, steps, observed result, and whether the issue was reproduced.', 'WCAG principles and success criteria provide a vocabulary, but a checklist cannot prove conformance without the required context and evaluation method.', 'Separate an observed barrier from its cause. A researcher can report what happened without asserting a code-level diagnosis.', 'Include successful paths and limitations so the report does not become a list of alarming but unverified defects.', 'Do not enter real personal data into a form during a test. Use a safe environment or a preapproved test account.', 'Prioritize issues by user impact and route, not by the number of automated warnings alone.', 'The owner decides remediation, legal posture, release timing, and whether a qualified accessibility specialist must review the findings.'], source: sources.access, image: '/featured/virtual-assistant-reporting-template-philippines.png' },
  { slug: 'multilingual-customer-question-research-philippines', published: '2026-08-13', keyword: 'multilingual customer question research virtual assistant Philippines', title: 'Multilingual customer-question research: separate requirements from hopeful fit', excerpt: 'A research method for organizing grant notices and evidence without promising eligibility, funding, or application success.', service: 'grant-eligibility source research', question: 'How can a support role compare a grant notice with an organization’s facts while leaving eligibility and application decisions accountable?', finding: 'Grant research should preserve the funder’s jurisdiction, deadline, defined terms, required evidence, and unresolved interpretation instead of scoring fit by intuition.', angle: 'grant eligibility', details: ['Use the official notice and application instructions as the source of truth. A summary page may omit exclusions, amendments, or definitions.', 'Record the program year, applicant type, geography, eligible activity, deadline time zone, and submission channel exactly as stated.', 'Separate an explicit requirement from a possible alignment. Shared language with a program goal is not proof that the applicant qualifies.', 'Flag terms such as nonprofit, partnership, match, indirect cost, and service area for the responsible reviewer when their meaning affects eligibility.', 'Track amendments and questions to the funder; a static note can become wrong when the notice changes.', 'Use a redacted or fictional organization for a work sample and score source accuracy, date handling, citation, and escalation.', 'Never promise an award, award amount, selection probability, or outcome from the presence of a plausible match.', 'The owner decides whether to apply, what representations to make, and whether legal or accounting review is required.'], source: sources.sba, image: '/featured/virtual-assistant-market-research-brief-philippines.png' },
  { slug: 'policy-change-monitoring-research-philippines', published: '2026-08-13', keyword: 'policy change monitoring research virtual assistant Philippines', title: 'Policy-change monitoring: an administrative research boundary', excerpt: 'How to index dates, parties, notices, and open questions without interpreting clauses or giving legal advice.', service: 'contract-obligation index research', question: 'Which contract facts can be organized for review, and which conclusions must remain with counsel or the accountable owner?', finding: 'An obligation index is useful when it quotes or links the controlling section, labels the date type, and distinguishes extraction from interpretation.', angle: 'policy change monitoringing', details: ['Identify the agreement, version, parties, effective date, term, notice window, and source location before extracting any milestone.', 'A renewal date, termination notice date, delivery date, and payment date have different triggers. Preserve the contract’s labels rather than collapsing them into “due date.”', 'Quote the relevant short phrase or link the exact section so a reviewer can reproduce the entry. Do not paraphrase away a condition or exception.', 'Mark an item as extracted, owner-confirmed, disputed, or interpreted. These states should not be represented by one green check.', 'Conflicting versions require a hold and named owner; the index should not choose the more convenient document.', 'Use fictional agreements for a work sample and include missing signatures, amendments, conflicting dates, and a clause that needs legal interpretation.', 'Protect confidential agreements with named access, retention rules, and a clear offboarding action.', 'The owner or qualified counsel decides enforceability, breach, notice strategy, negotiation, and any legal consequence.'], source: sources.risk, image: '/featured/virtual-assistant-document-management-philippines.png' },
];

const makePost = (t: ReplacementTopic): ResearchPost => {
  const ids = [t.source.id, sources.privacy.id, sources.cisa.id];
  const paragraphs = [
    `This report examines ${t.service} for a business considering Philippines-based support. Its narrow question is: ${t.question} ${t.finding} The evidence supports a record design and review boundary; it does not measure an individual worker or promise an outcome.`,
    `The useful unit is one ${t.angle} item. Start with its input, source of truth, permitted action, stop condition, reviewer, and date. That makes a finding inspectable instead of allowing a polished summary to stand in for proof.`,
    'The cited authority is relevant to the principle under discussion, but it is not a study of this company, this support arrangement, or this sample. Treat the recommendation as bounded role design and test it with safe data before opening live access.',
    ...t.details,
    `The research question also determines what counts as a useful absence. In ${t.angle}, a missing field may mean that the source was unavailable, the owner has not decided, or the record was never requested. Those explanations should remain separate because each calls for a different next action.`,
    `Compare the proposed ${t.angle} record with the original source, not only with a previous summary. A summary can preserve the conclusion while losing a qualification, date, exception, or definition that changes how the finding should be used.`,
    `For ${t.service}, write the expected output before the sample begins. The output might be a cited row, a short comparison, an exception note, or a question for the owner. A vague deliverable makes it impossible to distinguish incomplete work from a reasonable limitation.`,
    'Where several sources disagree, preserve both statements and explain the disagreement. Do not choose the source that produces the easiest recommendation. Authority, scope, date, method, and directness all matter when weighing evidence.',
    'A reviewer should be able to reproduce the path from input to conclusion without relying on the researcher’s memory. Keep the source URL, access date, relevant passage or field, transformation, and unresolved question together in the record.',
    'Use a stop rule when the evidence no longer answers the defined question. More links do not automatically improve a report; they can introduce duplicate claims, stale context, or a new topic that belongs in a separate study.',
    'Review the negative cases deliberately. An article that describes only successful matches, complete documents, available channels, or clear requests will hide the conditions that create the most owner work.',
    'The support role should report uncertainty in plain language. “Not found in the checked source” is different from “does not exist,” and “requires confirmation” is different from “approved.” These distinctions protect the next decision.',
    'If the record contains personal, confidential, financial, health, employment, or contract information, restrict the research extract to the minimum needed for the question. Retention and deletion should have an owner before the assignment starts.',
    'A quality sample should include at least one item that tests the boundary of the role. The point is not to catch a person out; it is to learn whether the brief gives them a safe and observable way to stop.',
    'Interpret the result at the same level as the evidence. A page observation supports a page observation, a selected sample supports a selected-sample statement, and a source principle supports a control or question rather than a performance guarantee.',
    'The conclusion should name what the buyer can do next: approve a narrow lane, request a missing source, ask a qualified owner, repeat the observation, or hold the task. A conclusion that only restates the topic does not help the decision.',
    `A second reader should check whether the evidence actually matches ${t.service}, rather than merely mentioning a similar word. Relevance is about the decision, population, period, and record being examined, not keyword overlap.`,
    'Keep measurement language modest. Counts, proportions, elapsed times, and category totals should include their denominator or unit when that context changes interpretation. If the denominator is unavailable, say so instead of implying precision.',
    'Do not let the article’s practical recommendations outrun the sources. The recommendation may be sensible because it reduces ambiguity, but it should be presented as a bounded operating suggestion and not attributed to an authority that did not make it.',
    'Revisit the record when the underlying source, policy, schedule, owner, or user path changes. A dated access note makes refresh work possible and gives the next reviewer a reason to recheck rather than silently trusting an old conclusion.',
    'A first review should score factual accuracy, completeness, source traceability, clarity, handling of uncertainty, and escalation judgment. A pass on one sample is evidence about that sample only; it is not a forecast of future performance.',
    'For a Philippines-based arrangement, document overlap hours, outage communication, approved systems, language questions, and the accountable owner. Country context may help plan coordination, but it cannot prove a person’s availability, judgment, security practice, or fit.',
    'The main limitation is transfer from public guidance to a live business process. Source quality, workload, software, permissions, reviewer capacity, and changing records all affect results. Recheck time-sensitive evidence and hold work when the source or owner decision is missing.',
  ];
  return {
    slug: t.slug, featuredImage: t.image, primaryKeyword: t.keyword, title: t.title, metaTitle: t.title, excerpt: t.excerpt,
    published: '2026-08-13', updated: '2026-08-13', readingMinutes: 11, revision: `2026-08-13-${t.slug}-v1`,
    takeaways: [t.finding, 'Keep observations, interpretations, and owner decisions in separate fields.', 'Use a safe sample before live access.', 'Escalation is a quality control, not a failed answer.'],
    headlineStats: [
      { value: '1', label: 'Research question', context: t.question, sourceIds: ids },
      { value: '8', label: 'Topic-specific checks', context: `The report identifies eight checks for ${t.angle}.`, sourceIds: [t.source.id] },
      { value: '1', label: 'Named owner', context: 'Every unresolved exception needs an accountable decision owner.', sourceIds: [sources.risk.id] },
      { value: '0', label: 'Outcome promises', context: 'The sources support boundaries and methods, not guaranteed results.', sourceIds: [sources.privacy.id] },
      { value: '6', label: 'Review dimensions', context: 'Score accuracy, completeness, traceability, clarity, uncertainty, and escalation.', sourceIds: ids },
      { value: '1', label: 'Safe first sample', context: 'Begin with invented or redacted records before widening scope.', sourceIds: [sources.cisa.id] },
    ],
    sections: [
      { heading: 'What the evidence can answer', paragraphs: paragraphs.slice(0, 3) },
      { heading: 'Define the record before the task', paragraphs: paragraphs.slice(3, 7) },
      { heading: 'Test the boundary with safe data', paragraphs: paragraphs.slice(7, 11) },
      { heading: 'Review results without overclaiming', paragraphs: paragraphs.slice(11) },
    ],
    evidenceTable: t.details.slice(0, 3).map((finding, i) => ({ signal: ['Scope', 'Observable evidence', 'Exception path'][i], finding, buyerUse: `Put this check in the ${t.angle} brief and sample scorecard.`, limit: 'It does not prove a person, provider, or future result.', sourceIds: [t.source.id] })),
    implications: [
      { title: 'Define the lane', body: `List inputs, outputs, permitted actions, reviewer, and stop conditions for ${t.service}.` },
      { title: 'Protect the record', body: 'Use named accounts, minimum necessary access, source links, and explicit handling for uncertainty.' },
      { title: 'Test safely', body: 'Use invented or redacted records and include at least one conflict, omission, or changed source.' },
      { title: 'Keep decisions owned', body: 'Route legal, clinical, financial, safety, privacy, and commercial decisions to the responsible owner.' },
    ],
    methodology: [`This report uses the authoritative source shown below and supporting privacy, security, or risk principles, all accessed on August 13, 2026. The sources were selected for direct relevance to ${t.service}.`, 'The article distinguishes observed facts, bounded interpretation, and practical recommendation. It makes no claim about an individual, provider, customer, or business outcome.', 'The method is limited by the selected sources and sample. Qualified legal, clinical, accounting, accessibility, employment, or procurement review remains necessary where those duties apply.'],
    faq: [
      { question: `Can support own the final ${t.angle} decision?`, answer: 'Only when a qualified accountable owner has explicitly assigned it. Otherwise, support prepares the record and escalates.' },
      { question: 'What should a buyer test first?', answer: 'Use a short safe-data sample and score accuracy, completeness, traceability, clarity, uncertainty handling, and escalation.' },
      { question: 'Does a source prove a provider is suitable?', answer: 'No. It establishes relevant principles or facts; suitability requires role-specific evidence and review.' },
      { question: 'When should the work stop?', answer: 'Stop when the source is missing, records conflict, the request exceeds the permitted lane, or an owner decision is required.' },
      { question: 'What should the handoff contain?', answer: 'The question, sources, observed result, limits, unresolved exceptions, next check, and named owner.' },
    ],
    sources: [t.source, sources.privacy, sources.cisa],
    related: [
      { title: 'Research library', href: '/research', description: 'Read other source-led reports for Philippines-based support decisions.' },
      { title: 'Services', href: '/services', description: 'Review the support lanes available for a documented role plan.' },
      { title: 'Contact', href: '/contact', description: 'Share recurring work, tools, review rules, and owner decisions.' },
    ],
  };
};

export const august13ReplacementResearchPosts: readonly ResearchPost[] = topics.map(makePost);
