import type { BlogPost } from './data';

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20', note: 'Use named governance, protection, response, and recovery ownership.' },
  { name: 'CISA More than a Password', url: 'https://www.cisa.gov/mfa', note: 'Protect work accounts with multi-factor authentication.' },
  { name: 'Federal Plain Language Guidelines', url: 'https://www.plainlanguage.gov/guidelines/', note: 'Write operational records so the next reader can act without decoding them.' },
];

const topics = [
  ['virtual-assistant-property-inspection-photo-register','A property inspection photo register that keeps findings factual','property inspection photo register','address, inspection date, room or area, original photo link, visible condition, missing view, and reviewer','label what the image visibly shows without diagnosing a defect or estimating repair cost','Route safety concerns, tenant disputes, repair decisions, and legal notices to the property manager.'],
  ['virtual-assistant-clinical-trial-document-expiry-tracker','Track clinical-trial document expiry without making compliance calls','clinical-trial document expiry tracker','document owner, controlled identifier, approved repository link, effective date, expiry date, renewal state, and study contact','copy dates from the controlled record and flag conflicts instead of choosing one','Clinical, regulatory, ethics, and participant-safety judgments remain with qualified study staff.'],
  ['virtual-assistant-catering-event-allergy-question-log','Keep a catering allergy-question log without giving medical advice','catering allergy question log','event, guest wording, menu item, kitchen response status, approved reply, deadline, and escalation owner','preserve the guest’s exact question and distinguish an inquiry from a confirmed accommodation','The chef or authorized safety owner confirms ingredients, cross-contact controls, and any promise to a guest.'],
  ['virtual-assistant-fleet-maintenance-document-chase','Chase fleet maintenance documents without clearing a vehicle','fleet maintenance document chase','vehicle, service event, requested record, source workshop, received date, discrepancy, and fleet reviewer','match invoices and inspection records to the correct vehicle and service date','Only the fleet or safety owner can determine roadworthiness, approve repairs, or return a vehicle to service.'],
  ['virtual-assistant-architecture-rfi-response-register','Maintain an architecture RFI register without issuing design direction','architecture RFI response register','RFI number, drawing reference, question, sender, design owner, due date, response state, and issued version','record the issued response verbatim and retain superseded status without deleting history','Architects and designated consultants own design interpretation, instruction, and professional sign-off.'],
  ['virtual-assistant-pharmacy-wholesale-backorder-brief','Prepare a pharmacy wholesale backorder brief without recommending substitutes','pharmacy wholesale backorder brief','product identifier, supplier notice, order quantity, expected date, affected request, and pharmacist owner','separate supplier statements from local inventory records and mark uncertain dates','A pharmacist or authorized clinical owner decides substitution, patient communication, and dispensing action.'],
  ['virtual-assistant-podcast-sponsor-deliverable-proof-log','Build a podcast sponsor proof log without inventing performance','podcast sponsor deliverable proof log','campaign, approved copy, placement, episode URL, publication time, screenshot, correction, and account owner','capture delivery evidence against the signed brief, not memory or a draft','The commercial owner handles claims, make-goods, pricing, contract interpretation, and performance representations.'],
  ['virtual-assistant-nonprofit-grant-report-source-folder','Organize a nonprofit grant-report source folder without reshaping outcomes','nonprofit grant-report source folder','grant requirement, reporting period, source record, program owner, verification state, gap, and approval','keep reported figures tied to their source period and definition','Program and finance owners approve outcomes, allocations, certifications, and explanations to the funder.'],
  ['virtual-assistant-hotel-group-booking-rooming-list','Check a hotel group rooming list without changing guest commitments','hotel group rooming list','reservation reference, guest-supplied name, stay dates, room request, confirmation state, and exception owner','compare the latest approved list with hotel confirmations one field at a time','The event owner decides upgrades, concessions, cancellations, payment changes, and disputed commitments.'],
  ['virtual-assistant-manufacturing-calibration-certificate-index','Index calibration certificates without approving equipment use','calibration certificate index','asset identifier, certificate number, laboratory, calibration date, due date, scope, exception, and quality owner','link the original certificate and flag missing identifiers or inconsistent dates','Quality or engineering owners determine fitness for use, tolerances, quarantine, and release.'],
  ['virtual-assistant-literary-rights-submission-tracker','Run a literary rights submission tracker without accepting terms','literary rights submission tracker','work, territory, recipient, approved material, sent date, response, follow-up rule, and agent owner','record interest and requested materials in the recipient’s own terms','The author or rights agent chooses submissions and decides representation, licensing, exclusivity, and commercial terms.'],
  ['virtual-assistant-solar-permit-status-digest','Prepare a solar permit status digest without interpreting approval','solar permit status digest','project, jurisdiction, application identifier, portal status, last official notice, requested item, deadline, and permit owner','quote official status text and link the notice rather than translating it into a guarantee','Licensed, legal, engineering, and permitting owners interpret requirements and authorize responses.'],
] as const;

export const september9BlogPosts: BlogPost[] = topics.map(([slug,title,lane,finish,check,boundary], index) => ({
  slug, title, featuredImage: '/featured/publishing-contingency-routine.png', minutes: 9,
  excerpt: `A practical ${lane} routine for a Philippines-based virtual assistant, with source checks and a clear owner boundary.`,
  published: '2026-09-09', updated: '2026-09-09', displayDate: 'September 9, 2026',
  takeaways: [`Define the finished record as ${finish}.`, check, boundary, 'Leave the next shift a linked source, current state, exception, and named owner.'],
  sections: [
    { heading: 'Name the record before opening the queue', body: `A reliable ${lane} starts with one source of truth and a narrow finish line. For Virtual Assistant Provider, the completed record contains ${finish}. That definition keeps daily work reviewable instead of turning “updated” into an uncheckable status.` },
    { heading: 'Work from evidence, not memory', body: `Open the approved source, confirm the identifier, record the current state, and preserve the link another authorized person can inspect. ${check}.`, bullets: ['Distinguish requested, received, checked, and approved.', 'Keep conflicting facts visible.', 'Do not move sensitive details into an informal digest.'] },
    { heading: 'Keep authority where it belongs', body: boundary },
    { heading: 'Check the first five records', body: `Review five varied ${lane} examples against their sources. Classify corrections as a missing input, unclear rule, access gap, execution error, or owner delay. Revise the instruction when the same ambiguity returns.` },
    { heading: 'Protect access and recovery', body: 'Use named accounts, multi-factor authentication, and the smallest permission set that supports the task. NIST and CISA guidance provide a useful control frame, but the client’s system owner still approves access and recovery.' },
    { heading: 'Close with an actionable handoff', body: `List completed records, unresolved conflicts, deadlines, and the next permitted action. ${boundary} A good handoff lets the next person continue without private context or duplicated action.` },
  ],
  faq: [
    { question: `What can an assistant own in a ${lane}?`, answer: `They can maintain the factual record, run documented checks, and route exceptions. ${boundary}` },
    { question: 'What proof should remain?', answer: 'Keep the source link, identifier, previous state, action, check result, timestamp, exception, and reviewer decision.' },
    { question: 'When should the manager review every item?', answer: 'Review every item during launch, after a serious miss, and whenever the source, instruction, or permissions change.' },
  ],
  sources, relatedServices: [],
  articleLinks: [{label:'daily planning guide',href:'/blog/virtual-assistant-daily-planning-philippines'},{label:index % 2 ? 'handoff guide':'escalation rules guide',href:index % 2 ? '/blog/virtual-assistant-handoff-philippines':'/blog/virtual-assistant-escalation-rules-philippines'},{label:'NIST Cybersecurity Framework 2.0',href:sources[0].url,external:true}],
}));
