import * as data from './data';
const dataAny = data as any;
const site = dataAny.site || {};
const footerItems = (dataAny.services || dataAny.roles || dataAny.industries || dataAny.blogPosts || []).slice(0,6);
const getTitle = (item: any) => typeof item === 'string' ? item : (item.title || item.name || item.label || item.question || String(item));
const getSlug = (item: any) => typeof item === 'string' ? item.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') : (item.slug || getTitle(item).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));
const domain = site.domain || 'this site';
const year = new Date().getFullYear();
export function JsonLd({data}:{data: any}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(data)}} />}
export function LogoMark(){return <span className="logo-mark-wrap"><img className="logo-img" src="/logo.svg" alt="" aria-hidden="true"/><span className="logo-name">{site.brand || domain}</span></span>}
export function Header(){return <header className="nav"><div className="nav-inner"><a className="logo" href="/" aria-label={`${site.brand || domain} home`}><LogoMark/></a><nav className="links" aria-label="Main navigation"><a href="/#tasks">Services</a><a href="/#tasks">Task ideas</a><a href="/blog">Guides</a><a href="/contact">Contact</a></nav><a className="btn nav-cta" href="/contact">Request plan</a></div></header>}
export function Footer(){return <footer className="footer legit-footer"><div className="footer-grid"><div className="footer-brand"><a className="footer-logo" href="/" aria-label={`${site.brand || domain} home`}><LogoMark/></a><p>{site.brand || domain} helps business owners define a VA role, compare hiring options, and prepare the first handoff.</p><p className="footer-note">This is an independent information site. If you submit a request, a staffing team or service partner may follow up with you.</p></div><div><h3>Explore</h3><div className="footer-links">{footerItems.map((item:any,idx:number)=><a href={`/services/${getSlug(item)}`} key={idx}>{getTitle(item)}</a>)}</div></div><div><h3>Company</h3><div className="footer-links"><a href="/contact">Contact</a><a href="/blog">Guides</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms & Conditions</a><a href="/cancellation-policy">Cancellation Policy</a></div></div></div><div className="footer-bottom"><span>© {year} {site.brand || domain}. All rights reserved.</span><span>{domain}</span></div></footer>}
export function CTA(){return <section className="final-cta"><p className="eyebrow">Need help scoping the role?</p><h2>Write down the job before you hire.</h2><p>Send the tasks, tools, working hours, and parts that need a manager's approval.</p><a className="btn primary" href="/contact">Request staffing plan</a></section>}
