import { Header, Footer, CTA, JsonLd } from './components';
import { site, services, industries, stats, blogPosts, faq, providerCards, evidenceNotes } from './data';

export default function Home() {
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'Organization', '@id': `${site.url}/#organization`, name: site.brand, url: site.url, email: site.email },
      { '@type': 'WebSite', '@id': `${site.url}/#website`, name: site.brand, url: site.url, publisher: { '@id': `${site.url}/#organization` } },
      { '@type': 'WebPage', '@id': `${site.url}/#webpage`, url: site.url, name: 'Virtual Assistant Provider buyer guide', isPartOf: { '@id': `${site.url}/#website` }, publisher: { '@id': `${site.url}/#organization` }, mainEntity: { '@type': 'ItemList', itemListElement: services.map((service, index) => ({ '@type': 'ListItem', position: index + 1, name: service.name, url: `${site.url}/services/${service.slug}` })) } },
      { '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) },
    ],
  };

  return <><Header/><main>
    <JsonLd data={schema} />
    <section className="hero"><div className="container grid"><div><p className="eyebrow">virtual assistant provider</p><h1>Find the right assistant without guessing.</h1><p className="lead">Virtual Assistant Provider helps business owners compare managed VA providers, tasks, prices, risks, and onboarding steps in plain English.</p><p>Use this site to plan a safer first hire, avoid vague job posts, and hand off work with simple quality checks.</p><div style={{display:'flex', gap:12, flexWrap:'wrap', marginTop:22}}><a className="btn" href="/contact">Build my assistant plan</a><a className="btn secondary" href="/blog">Read hiring guides</a></div></div><div className="hero-panel"><img className="hero-img" src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80" alt="Business owner comparing virtual assistant provider options at a meeting table" /><div className="hero-score"><b>Provider shortlist check</b><span>screening · QA · backup · access rules</span></div><div className="card floating-card"><h3>Best first assistant tasks</h3><ul className="list"><li>Inbox sorting and calendar cleanup</li><li>Lead follow-up and CRM updates</li><li>Call answering and appointment setting</li><li>Customer support replies</li><li>Simple reports, research, and admin</li></ul><p className="quote">&quot;Start small, measure weekly, then add more work.&quot;</p></div></div></div></section>
    <section className="section" id="services"><div className="container"><p className="eyebrow">Services</p><h2>Assistant roles people compare most</h2><p className="lead">Each role guide explains what to hand off, what to keep with the owner, and how to test fit in the first week.</p><div className="cards image-cards">{services.map((r)=><a className="card service-card" key={r.slug} href={`/services/${r.slug}`}><img src={r.image} alt={r.imageAlt} /><div><h3>{r.name}</h3><p>{r.excerpt}</p><span className="pill">SOP ready</span><span className="pill">Remote friendly</span></div></a>)}</div></div></section>
    <section className="section navy-section"><div className="container"><p className="eyebrow">Provider shortlist</p><h2>Compare the support model before you compare rates.</h2><p className="lead">A low hourly rate can still be expensive if nobody checks the work. Start by comparing management, backup coverage, and access rules.</p><div className="cards">{providerCards.map((provider)=><div className="card dark-card" key={provider.name}><span className="mini-rating">{provider.rating}</span><h3>{provider.name}</h3><p>{provider.note}</p><a href="/contact">Build a shortlist</a></div>)}</div></div></section>
    <section className="section"><div className="container two"><div><p className="eyebrow">Who it helps</p><h2>Built for teams that need help but do not want a messy hire.</h2><p>A practical buyer guide for choosing a dependable VA provider with clear screening, task handoff, and pricing ranges.</p><p>We focus on job scopes, screening questions, training assets, time-zone fit, security basics, and weekly scorecards.</p></div><div className="card"><h3>Industry examples</h3>{industries.map((i)=><span className="pill" key={i}>{i}</span>)}<p style={{marginTop:12}}>The same rule applies in each niche: hand off repeatable work first and keep sensitive choices with the owner.</p></div></div></section>
    <section className="section" id="pricing"><div className="container"><p className="eyebrow">Costs and timing</p><h2>Realistic ranges before you talk to providers</h2><div className="cards">{stats.map((s)=><div className="card stat" key={s.label}><h3>{s.value}</h3><b>{s.label}</b><p>{s.note}</p></div>)}</div><div className="source-strip" aria-label="Planning sources">{evidenceNotes.map((note)=><a href={note.url} key={note.label}><b>{note.label}</b><span>{note.source}</span></a>)}</div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Buyer guide</p><h2>Ask these before you sign</h2><div className="table"><div className="row"><b>Question</b><b>Why it matters</b><b>Good answer</b></div><div className="row"><span>Who manages quality?</span><span>A low rate is not useful if you review every task twice.</span><span>A named manager, weekly QA, and replacement help.</span></div><div className="row"><span>Can we start small?</span><span>A pilot lowers risk and shows fit fast.</span><span>A 2-week or 20-hour test with a clear task list.</span></div><div className="row"><span>How is access handled?</span><span>Remote work needs safe tool access.</span><span>Named logins, limited permissions, and offboarding steps.</span></div></div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Comparison</p><h2>Three ways to hire assistant support</h2><div className="table"><div className="row"><b>Option</b><b>Best for</b><b>Watch out for</b></div><div className="row"><span>Local employee</span><span>In-person work and sensitive decisions</span><span>Higher cost and slower hiring</span></div><div className="row"><span>Freelance VA</span><span>Small task lists and flexible work</span><span>Training, backup, and QA are on you</span></div><div className="row"><span>Managed VA service</span><span>Recurring support with screening and replacement help</span><span>Ask exactly who manages quality</span></div></div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">FAQ</p><h2>Common VA provider questions</h2><div className="cards">{faq.map((item)=><div className="card" key={item.question}><h3>{item.question}</h3><p>{item.answer}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Guides</p><h2>Start with these hiring guides</h2><div className="cards">{blogPosts.slice(0,3).map((p)=><a className="card" href={`/blog/${p.slug}`} key={p.slug}><h3>{p.title}</h3><p>{p.excerpt}</p><span className="pill">{p.minutes} min read</span></a>)}</div></div></section>
    <CTA />
  </main><Footer/></>;
}
